### ISSUE TITLE
Print slowing down and causing blobing

### ISSUE THREAD

**Issue by AlexKlimaj** [OctoPrint/OctoPrint#118]
When I print from Octoprint running on an overclocked raspberry pi at 230400 baud rate, the print will randomly slow every so often and cause blobs. When I print the same gcode from my laptop at the same baud rate, the issue is not present.

**Comment by epoxi** [comment]
Sorry for reopening this case. I found this looking for a solition to blobbing on intrincated prints.
I'm using a RBpi B+ v1 with Octopi/Octoprint (up to date).
Custom Prusa i3 RUMBA board @115200bps. Marlin FW 1.1.0-RC7.

Let me do some tests, and watching _top_ while printing.

**Comment by ShadowBr0ther** [comment]
I also have this issue

Raspberry Pi 3B+
Trigorilla Board @115200bps Marlin 1.1.9 (Anycubic Kossel linear Plus)

Octoprint is great, but I have to reinstall Repetier Server because of this issue. On Repetier everything runs smoothly.

**Comment by RichyT** [comment]
Having the same issue here. Trying to eliminate throttling as an issue. Will let you know more.

It seems to be on "busy" prints where there are a lot of rapid commands (circles and such). Would it be worth niceing the process which talks to the USB to a higher priority?
