### ISSUE TITLE
 [Request] or [suggestion]: other symbols for retract and un-retract. 

### ISSUE THREAD

**Issue by rewolff** [OctoPrint/OctoPrint#1327]
I'm currently printing an object where the retract and un-retract (what's it called?) are exactly on the same spot. Thus you see only the retract because that's what happens last. 

Suggestion: Make the symbols instead of the red and blue circle that they are, a right-facing red pacman for retract and a left-facing blue pacman for un-retract. In my case I would see a red rightfacing pacman with a blue "mouth" indicating an un-retract happened at the same spot as the retract later on. The reverse situation is also recognizable (although I can't think of a situation where it would happen.)

**Comment by cp2004** [comment]
The retract/unretract marks have been alternate triangles for a long time now, implementing this.
