### ISSUE TITLE
GCode viewer doesn't correctly display GCode with relative-extrusion

### ISSUE THREAD

**Issue by jwygralak67** [OctoPrint/OctoPrint#136]
This is what I get viewing a g-code file which uses absolute extrusion:
![absolute-e](https://f.cloud.github.com/assets/1240702/564358/1af9b2ce-c55c-11e2-9a79-df9cd6797800.png)

This is the same STL sliced with identical settings, except using relative extrusion:
![relative-e](https://f.cloud.github.com/assets/1240702/564359/1c332aa8-c55c-11e2-9d6c-93a953ed0efc.png)

Both gcode files were produced by Slic3r, from the same STL file.
The relative-E gcode file prints just fine.

I put the two g-code files in a gist
https://gist.github.com/jwygralak67/5650484

**Comment by Fheilmann** [comment]
Just wanted to report that I have the same issue when using Simplify3D in relative mode. After my current print finishes I'll try absolute mode and see if that helps

**Comment by markwal** [comment]
@Fheilmann did you try the workaround given above and add the appropriate M82/M83 to your start gcode in Simplify3D?

**Comment by Fheilmann** [comment]
@markwal Simplify3D placed a M83 command right at the beginning of the gcode file.
Could the viewer become confused if i switch motion between relative and absolute mode in my start gcode ? (I'm doing a G91 to lift the head slightly and then go back to G90)

**Comment by markwal** [comment]
Good conjecture. You could test by putting another M83 after the G90.
