### ISSUE TITLE
[Request] Infinite Feed Rate Editing

### ISSUE THREAD

**Issue by cye604** [OctoPrint/OctoPrint#1389]
Hey, I really love Octoprint so far, has made things a lot easier. There is just one thing I'd recommend.

Currently, under "Control," you can set the Feed Rate from 50% to 150%. I commonly use anywhere from 50% to 250%. Is there any way to expand the range of the slider bar, or replace it with a box to type a number in? 

I tried looking for a plugin to fix this, but I couldn't find any in the repository (not sure if right word). 

Thanks for any help you can offer!

**Comment by cp2004** [comment]
# 🧹 *sweep* *sweep*
Don't mind me, just cleaning up old requests.
Feedrate is now unlimited in the number field
https://github.com/OctoPrint/OctoPrint/pull/3503
