### ISSUE TITLE
[Request] Resize Terminal Window?

### ISSUE THREAD

**Issue by gcormier** [OctoPrint/OctoPrint#1535]
Would be nice to be able resize the terminal window within a browser.

**Comment by Runolas** [comment]
What do you mean by resize the terminal window ? You want to adapt the terminal size depending on the browser size, or to resize it manually ?

**Comment by gcormier** [comment]
Yup, the window you enter commands and see the output. Either/or would be awesome!

**Comment by Runolas** [comment]
I found in my virtual environment directory, a css file named "octoprint.css". I can edit it to set the minimum height of the terminal, identified by the id "terminal-output" (default is 340 pixel). This change takes effect after restart octoprint server. However, when I connect my printer, the terminal size reset to the default value. I think it's due to the autoscroll of terminal. I tried to set the pixel maximal height of the autoscroll (id "pre-scrollable"), but it doesn't work.

**Comment by Runolas** [comment]
We can set manually the terminal size in the browser developer tools, but it's need to set it for each connection !

**Comment by JayceeB1** [comment]
Up! need this :)

**Comment by jneilliii** [comment]
Sounds like a plugin idea to me.

**Comment by jneilliii** [comment]
A quick test in the developer console, the following line seems to re-size properly so setting these css rules in Themeify may actually work.
```
$('#term,#terminal-output').css({'width':'800px','height':'800px','max-height':'800px'});
```

**Comment by jneilliii** [comment]
Yep, seems to work in Themeify....here are the settings.

| selector         | css-rule   | value |
|------------------|------------|-------|
| #terminal-output | max-height | 800px |
| #term            | height     | 800px |
| #term            | width      | 800px |

And here is the output....

![image](https://user-images.githubusercontent.com/5249455/82819353-3d48e500-9e6e-11ea-8abc-c1501c61f293.png)

**Comment by JayceeB1** [comment]
Wow, nice job!
Thanks a lot!

**Comment by corbolais** [comment]
Would be nice to have it in octoprint core. Or at least a hint on the terminal page that if you want to change settings/size you need to install the `themeify` plugin.

**Comment by cp2004** [comment]
This works in several plugins that can add custom CSS, and I remember @LazeMSS saying he might add it as an option from the UI customizer plugin 😉.

**Comment by LazeMSS** [comment]
> This works in several plugins that can add custom CSS, and I remember @LazeMSS saying he might add it as an option from the UI customizer plugin 😉.

Yes is already implemented in next version 🤗
