### ISSUE TITLE
[Request] Saving Modified Slicing Settings

### ISSUE THREAD

**Issue by cinderblock** [OctoPrint/OctoPrint#1618]
I'd like to be able to **save** my tweaks to the Cura slicer settings from within OctoPrint.

Currently, it is easy to edit the settings in a one-off way. They even seem to stick around if the browser window is not reloaded. Unfortunately, there is no "save" button.

#### Current Alternative

1. Open slicer settings in Cura 15.04
1. Edit settings
1. Save settings to ini file
1. Upload ini to OctoPrint

#### Related Issues
 - #477 Seems to have implemented the ability to change the settings in the interface but does not let you save them. (It looks like this feature was implemented and the issue never closed)
 - https://github.com/foosel/OctoPrint/pull/528#issuecomment-234853130 Looks like others may have been asking for this already.

#### Branch & Commit or Version of OctoPrint

`Version: 1.2.18 (master branch)`

I have read the FAQ. (There was no link to the FAQ in the docs that I could see. I didn't realize the wiki page was for this. Found it with google)

**Comment by donovan6000** [comment]
The [M33 Fio](https://github.com/donovan6000/M33-Fio) plugin kinda lets you do this. It lets you save a local copy of a slicer profile with all its current changes, and then that local copy can be uploaded to OctoPrint.
![alt text](https://raw.githubusercontent.com/donovan6000/M33-Fio/master/images/profile%20editor.png "Profile Editor")

**Comment by cp2004** [comment]
Since Cura was removed from the standard OctoPrint install, this issue doesn't make sense any more. The 'Legacy Cura' plugin is could provide this, but given slicing in OctoPrint is not really worked on anymore I doubt anyone would contribute such a feature.
