### ISSUE TITLE
[Request] USB Port "blacklist" in addition of the actual "whitelist"

### ISSUE THREAD

**Issue by docteurzoidberg** [OctoPrint/OctoPrint#1670]
I would love to be able to exclude some ports instead / in addition of whitelisting them.

Because the other machine connected on my Rpi is a CNC with a Laser and I don't want some Gcode to run on it by mistake :D

*I will do the pull-request for this feature if I see some people need this too*

**Comment by cp2004** [comment]
# 🧹 *sweep* *sweep*
Don't mind me, just cleaning up old requests.
No idea when this was implemented, but there are both blacklists & whitelists
