### ISSUE TITLE
All-on-one-page UI mode?

### ISSUE THREAD

**Issue by devzero** [OctoPrint/OctoPrint#173]
Would it be possible to display the side-bar, temperature screen, and webcam images (and possibly the g-code viewer and a few lines from the terminal) all on one page? Or does that chew up too much CPU?

**Comment by cp2004** [comment]
# 🧹 *sweep* *sweep*
Don't mind me, just cleaning up old requests.
[Consolidated Tabs](https://plugins.octoprint.org/plugins/consolidatedtabs/) implements this.
