### ISSUE TITLE
Cannot connect to printer

### ISSUE THREAD

**Issue by Lechpirat** [OctoPrint/OctoPrint#179]
Hi,
i recently installed OctoPrint on my RPi and i can access the Webinterface. But i cannot connect to my printer:
When i try to connect via /dev/ttyUSB0 i get the following terminal output:

Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: /dev/ttyUSB0
Connected to: Serial<id=0x1c20910, open=True>(port='/dev/ttyUSB0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from 'Opening serial port' to 'Connecting'
Changing monitoring state from 'Connecting' to 'Closed'
Connection closed, closing down monitor

I'm using Marlin firmware and baudrate 115200.
Any ideas?
Thanks

**Comment by ViliusKraujutis** [comment]
@Lechpirat, that was helpful to change to `115200`. Thank you very much.
