### ISSUE TITLE
Grbl support

### ISSUE THREAD

**Issue by PxT** [OctoPrint/OctoPrint#181]
Just wanted to let you know that I have forked a version to support the Grbl firmware which is used to run 3-axis CNC machines. There are still a couple of issues right now but for the most part it works.  CNC tends to be dusty, so if I can get Octoprint running reliably on a Raspberry Pi in this setup it would be a great help to keep my expensive laptop away from that environment!  

Just wanted to put it on your radar in case you are interested or if someone else searches this issue list looking for Grbl support.

https://github.com/PxT/OctoPrint

If you think this sort of thing is in-scope for your development branch I would be happy to send a pull request once it's at a base level of functionality.  If not that's fine too.

**Comment by Nandox7** [comment]
Hey, did this ever went ahead? I was looking for the same.
I have a 3D Printer already connected to Octoprint and it would be nice to plug my CNC as well.

**Comment by KC703** [comment]
Also interested in the status of this...

**Comment by PxT** [comment]
I haven't been keeping my branch up to date and it's pretty far behind now.  I don't have the time to work on it currently.  Someone could take the ideas from my fork and adapt them to the latest OctoPrint if they have time.

**Comment by pretenda** [comment]
This may also be an alternative: http://chilipeppr.com/tinyg

**Comment by pretenda** [comment]
This would be a better link: http://chilipeppr.com

**Comment by Nandox7** [comment]
@PxT thanks for your work.
I'll give a look into your repo and submit some PR's against it to bring it up to date.

**Comment by DaAwesomeP** [comment]
:+1:

**Comment by mic159** [comment]
There are two plugins for this now:

My plugin: https://github.com/mic159/octoprint-grbl-plugin
And one from @gt6796c: https://github.com/gt6796c/OctoPrint-grblplugin

I will push mine to pypi soon.

**Comment by foosel** [comment]
@mic159 great! Please not only push it to pypi but also register it in [OctoPrint's plugin repository](http://plugins.octoprint.org/help/registering/) so others can find it easily :)

**Comment by LazeMSS** [comment]
This is now implemented by plugins:
- https://github.com/mic159/octoprint-grbl-plugin
- https://github.com/gt6796c/OctoPrint-grblplugin
