### ISSUE TITLE
[Request] Notification upon print completion

### ISSUE THREAD

**Issue by karma0** [OctoPrint/OctoPrint#1855]
It would be really helpful if the browser could emit a sound indicating print finish while passively monitoring a print.

**Comment by foosel** [comment]
[Write a plugin](http://docs.octoprint.org/en/master/plugins/index.html) :)

**Comment by Erutan409** [comment]
@karma0 also - if you're an Android user, I highly recommend [Printoid](https://play.google.com/store/apps/details?id=fr.yochi76.printoid.phones.trial).  It'd give you what you're looking for.

**Comment by LazeMSS** [comment]
There are many plugins for this:
https://plugins.octoprint.org/search/?q=notification
