### ISSUE TITLE
Switch printer on/off through a solid state relay and GPIO pin

### ISSUE THREAD

**Issue by agentsmithitaly** [OctoPrint/OctoPrint#218]
It would be great to have the ability to remotely power on/off the printer's power supply.
Many printers, like the Solidoodle, comes without any kind of power switch.

Additionally, an idle timer could put the printer in "standby" mode, when certains conditions are met (i.e. bed and extruder temperature set to zero, x minutes passed since last print), and turn the printer back on automatically.

The easiest way would be to control a solid state relay through a GPIO pin from the Raspberry. Of course this means the Raspberry should get its power from an indipendent power supply.

**Comment by megator** [comment]
Hi Guys,

I am trying to implement this on my printer and am not having a lot of luck. I followed the wiki ( https://github.com/foosel/OctoPrint/wiki/Controlling-a-relay-board-from-your-RPi )but seem to be missing something.

I get the following error when I select the option to turn the printer on/off  (note i do not have a relay attached to the Pi at the moment)

Error
The command "Turn on the printer" could not be executed.
Reason:
Command failed with return code 1: 

Now I am not sure i did the portion with octoprint config file.

I am confused by the line --> In /etc/init.d/octoprint, add the following (gpio export 18 out) at line 77, before RETVAL="$?"

Should that be

gpio export 18 out
RETVAL="$?"

or 

gpio export 18 out RETVAL="$?"

Thanks for the help!
