### ISSUE TITLE
[REQUEST] Add power output monitoring to the temp graph.

### ISSUE THREAD

**Issue by andrewsil1** [OctoPrint/OctoPrint#2194]
I have read the FAQ.

It'd be a nice-to-have if the temperature graph was able to display power output levels returned in Repetier firmware (perhaps Marlin too?)

Temp format for a single head printer with heated bed (both PWMed) looks like:
`Recv: T:180.00 /185 B:65.19 /65 B@:0 @:154`
The power output is a 0-255 integer, in this case showing the tool at slightly over 50% power and the bed in an off state.  Repetier Host has similar graphing functionality.  It's mildly useful when PID tuning to get a sense for how power is being applied.

**Comment by LazeMSS** [comment]
Available in plugins:
https://github.com/jneilliii/OctoPrint-PlotlyTempGraph
https://plugins.octoprint.org/plugins/toptemp/
