### ISSUE TITLE
[REQUEST] REST API: get path to currently printed .gcode file

### ISSUE THREAD

**Issue by aurror** [OctoPrint/OctoPrint#2210]
It would be nice to be able to get the path of the currently printed file somehow,
for example as an extra entry in  [GET /api/printer](http://docs.octoprint.org/en/master/api/printer.html#retrieve-the-current-printer-state) or with a new [file operation command](http://docs.octoprint.org/en/master/api/files.html) .

Edit: I'm currently in the process of adding this, I'll submit a pull request once it's done.

**Comment by foosel** [comment]
It is actually returned on [`api/job`](http://docs.octoprint.org/en/master/api/job.html#retrieve-information-about-the-current-job) (even though the example in the documentation doesn't yet include it, that should indeed be fixed). E.g.:

``` json
{
  "job": {
    "averagePrintTime": null, 
    "estimatedPrintTime": 4855.383235247895, 
    "filament": {
      "tool0": {
        "length": 1736.3539000000453, 
        "volume": 0.0
      }
    }, 
    "file": {
      "date": 1508423977, 
      "display": "3DBenchy_.25.gcode", 
      "name": "3DBenchy_.25.gcode", 
      "origin": "local", 
      "path": "test/3DBenchy_.25.gcode", 
      "size": 2978760
    }, 
    "lastPrintTime": null
  }, 
  "progress": {
    "completion": 0.027830372369710882, 
    "filepos": 829, 
    "printTime": 0, 
    "printTimeLeft": 4854, 
    "printTimeLeftOrigin": "analysis"
  }, 
  "state": "Printing"
}
```
