### ISSUE TITLE
Tabular Arrangement of custom buttons

### ISSUE THREAD

**Issue by hp-bioing** [OctoPrint/OctoPrint#224]
Situation:
If got a ~15 custom buttons on by "control" tab and even more ideas for more. So I have scroll down for reaching the position of the last button, because they are all listed in a vertical order.

Aim of issue:
Would be really handy if there would be an option while defining the buttons to  arrange the buttons more in a table or matrix like way with rows and columns.  

Further ideas for improvement:
Additional useful ad-dons to the table
- if the first cell of such a table could be used for naming and even more 
- if it would be possible to add a small icon/pic/gif into a cell for an easier recognition of purpose of a set of buttons
- if it would be possible to define colors for the buttons, e.g. red for "Emergency stop" etc.

**Comment by LazeMSS** [comment]
@hp-bioing long time since you wrote but this should be possible by using this plugin:
https://plugins.octoprint.org/plugins/customControl/
