### ISSUE TITLE
[Request] Addition of Monitor/Dashboard Page

### ISSUE THREAD

**Issue by wescrockett** [OctoPrint/OctoPrint#2391]
Once a print begins, I find myself switching between CONTROL (for camera), GCode Viewer, and Temperature pages. Unless the sheer number of web requests and refreshes alone would cause a bottleneck, it would be awesome to add a 'MONITOR' page that features a side-by-side of the GCode Viewer and the camera, as well as current temperature information. Essentially, a dashboard view for use during print.

Thank you for your consideration on this request.
-Wes Crockett

**Comment by cp2004** [comment]
@foosel - this one can be closed too (sorry for tagging you in them, just thought I'd clean up)
This is possible through the [Consolidated Tabs](https://plugins.octoprint.org/plugins/consolidatedtabs/) plugin now.
