### ISSUE TITLE
Allow different protocols to be used instead of plain gcode-over-serial

### ISSUE THREAD

**Issue by koenkooi** [OctoPrint/OctoPrint#251]
Some control boards don't use gcode-over-serial, but something else. TinyG supports wrapping g-code in JSON and has a really neat config and reporting interface in JSON mode. Makerbot has s3g and x3g as data format.

**Comment by LazeMSS** [comment]
This seems like a feature with a limited audience/user base and can be handle by using the solution @Wallacoloo posted.

Closing for now.
