### ISSUE TITLE
[Request] Gcode Script: Before Print Job Starts

### ISSUE THREAD

**Issue by OutsourcedGuru** [OctoPrint/OctoPrint#2594]
# This could be a bug instead of a FR, but I like to err on the side of caution

#### What were you doing?
I did a fresh install of OctoPrint (from the OctoPi curated nightly image) onto a Raspberry Pi 3+ computer and brought up the instance. After using the Control panel to preheat the extruder and to prime the hotend, I then started a print job.

1. X/Y Home
2. Z Home
3. Preheat for PLA
4. Extrude 5mm, etc until primed
5. Upload small print job
6. Start print job

#### What did you expect to happen?
I expected the first layer to have a thin layer of plastic. It did not have any plastic in the hotend upon starting the print job.

#### What happened instead?
Immediately upon starting the job, the extruder did an unwanted retraction of about 100mm, almost ejecting the filament from the top. This resulted in no heated filament ready for the print job.

This is repeatable since it _did_ this every print job start. I managed to work around this, however.

By adding a `G92 E0` to the _Before print job starts_ section in the settings it behaves now as expected, btw.

I'm guessing that including this would cause little harm to those otherwise unaffected and would allow the printer to work for those who need it.

#### Did the same happen when running OctoPrint in safe mode?
Just getting started and I don't know how to start in safe mode yet... (I'll research that)

#### Version of OctoPrint
OctoPrint 1.3.8

#### Operating System running OctoPrint
OctoPi 0.15.0

#### Printer model & used firmware incl. version
Robo C2

#### Browser and version of browser, operating system running browser
Safari 11.1, OSX El Capitan 10.11.6

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
So... what is it that you are requesting here? Adding this `G92 E0` to the script by default? To be honest I'm a bit surprised this isn't already part of your slicer start code (which it really should be).

The thing is, I try to keep the preconfiguration of injected GCODE to a minimum. Otherwise you can bet on people opening tickets to the tune of "why is it doing this?!"

**Comment by FormerLurker** [comment]
@OutsourcedGuru, perhaps you should post your start/end gcode for OctoPrint and your slicer here:  https://discourse.octoprint.org/

I'll keep an eye out and will look over your post if/when you create it.  Cheers!

**Comment by OutsourcedGuru** [comment]
Fair points all around... I tend to document things for the few people who have less knowledge than I do in case they're also chasing their tails. I think I might have been suggesting to add that G92 by default.

My Cura's start/end code appear to be empty for the printer profile, for what it's worth.  I'll take this to discourse, as suggested.
