### ISSUE TITLE
gcode 3D viewer

### ISSUE THREAD

**Issue by ochorocho** [OctoPrint/OctoPrint#267]
Hey ....

i saw octoprint is using gCodeViewer.
https://github.com/hudbrog/gCodeViewer

gCodeViewer is able to show the uploaded file in 3D.

Was this function removed for some reason or just not implemented?

Thanks.

**Comment by jneilliii** [comment]
There's a new player in the plugin space for this if you haven't seen it on the Community Forum. From what I've seen over there it seems to work perfectly fine.

https://github.com/Kragrathea/OctoPrint-PrettyGCode
