### ISSUE TITLE
[Request] Documentation for file information is missing properties

### ISSUE THREAD

**Issue by mamoit** [OctoPrint/OctoPrint#2682]
The [file-information](http://docs.octoprint.org/en/master/api/datamodel.html#file-information) documentation is missing (at least) the following properties:
- `prints`
- `statistics`
- `notes`
- `links`

I may be missing some more, this is based on the replies Octoprint `1.3.8` gives me, not on the source code itself.

I have read the FAQ.

**Comment by foosel** [comment]
That's not a bug, that's missing documentation ;) 

As always, any help is welcome - I have my hands already full with maintenance and development, so stuff like this has a very low priority on my TODO list.
