### ISSUE TITLE
[REQUEST] Temperature graph: display the temperature differental from Target.

### ISSUE THREAD

**Issue by IgottaFind** [OctoPrint/OctoPrint#2695]
It would be helpful, in my opinion, to have an option for the Temperature Graph to display the number of degrees from the Target.  This would allow both the nozzle and bed to be displayed on top of one another and the range on the graph could be 10°C,for example, instead of 250°C.  Having the graph zoomed in would allow a nice visualization of the actual temperature and the changes that occur.

#### Printer model & used firmware incl. version
OctoPrint 1.3.8 Running on OctoPi 0.15.1.
Printing on CCR-10

#### Browser and version of browser, operating system running browser
WaterFox 56.2.1,  Windows 10.

**Comment by LazeMSS** [comment]
There are now plugins that can handle this - take a look at:
https://plugins.octoprint.org/search/?q=temp
