### ISSUE TITLE
Request: Upload & Print

### ISSUE THREAD

**Issue by davr** [OctoPrint/OctoPrint#272]
Might be nice to upload a file and have it immediately start printing, so you don't have to sit there and wait for the upload & "saving" (whatever happens during that process that always seems to take longer than the upload for me) to finish, then click the print button.

It should either be an option in settings, or a 3rd button next to the 'upload' and 'upload to sd' buttons.

**Comment by foosel** [comment]
Related: #540

**Comment by foosel** [comment]
As requested in #1520: not only look into a third upload option with regards to the upload buttons but also with regards to the drag-n-drop overlay.

**Comment by ntoff** [comment]
What about your plugin that auto selects a fresh upload? Could you just whack an option in that to also print?

**Comment by foosel** [comment]
I could, but the same problem as described above applies: user communication. If at all you want this on a per-print basis, not as a kind of general setting that always applies, that would lead to accidents.

**Comment by quintesse** [comment]
Right now with version 1.3.5 this seems to be done automatically. Are others seeing this as well? Either with Upload or Drag&Drop it will immediately start printing. THis is _not_ what I want. Is there a way to turn it off?

**Comment by CapnBry** [comment]
I've never seen it do this. I just tested a drag and drop and an upload from the button and it does what is expected (no auto-select no auto-print). Are you sure you don't have a plugin doing this?

**Comment by quintesse** [comment]
@CapnBry I don't have any plugin installed that can be removed, so I guess they're all built-in plugins.

**Comment by LazeMSS** [comment]
This is now implemented by plugins:
https://plugins.octoprint.org/plugins/AutostartPrint/
https://plugins.octoprint.org/plugins/autoselect/
