### ISSUE TITLE
[Request] Add support to Kiri:Moto

### ISSUE THREAD

**Issue by patrickelectric** [OctoPrint/OctoPrint#2754]
It would be pretty nice to add support to [Kiri:Moto](https://grid.space/kiri) a free online slicer in octoprint.
- It appears that Kiri:Moto can send the gcode to octoprint, it would be nice to store the slicer settings on it also.

**Comment by cp2004** [comment]
@foosel -  thought I'd flag this one to be closed. Just scrolling through the plugin ideas, this is [now a thing.](https://plugins.octoprint.org/plugins/gridspace/)
