### ISSUE TITLE
[Request] Support for Marlin Unified Bed Leveling (UBL)

### ISSUE THREAD

**Issue by dvankley** [OctoPrint/OctoPrint#2786]
Unified Bed Leveling is [implemented in Marlin](http://marlinfw.org/docs/features/unified_bed_leveling.html); it would be great to see an interface in Octoprint for running through the leveling process without an LCD or separate machine.

**Comment by jneilliii** [comment]
This shouldn't be too difficult to create using getAdditionalControls in a plugin, but for the standard UBL steps you can do it manually from the octoprint terminal. Better yet; you can put the below into a blank gcode file and just run it when you want to run UBL.

```
M190 S70        ; Not required, but having the printer bed at temperature helps accuracy
G29 P1          ; Do automated probing of the bed.
G29 P3 T        ; Repeat until all mesh points are filled in.
G29 S1          ; Save UBL mesh points to EEPROM.
G29 F 10.0      ; Set Fade Height for correction at 10.0 mm.
G29 A           ; Activate the UBL System.
M500            ; Save current setup. WARNING: UBL will be active at power up, before any `G28`.
```

**Comment by L0stCh1ld** [comment]
Helpful, however does not support manual probing for points outside the areas reachable by the probe
as an example i have the firstY row and X column that cannot be reached by the probe, so i need to manually do the movements and probing
eg.
G42 I0 J0
G29 P4
G42 I0 J1
G29 P4

etc etc

Having support for the "G29 P4" and "G42 Ixx Jxx" commands would be significantly more than useful

**Comment by ManuelMcLure** [comment]
You can still send those via the terminal. And usually the ``G29 P3`` gives you a mesh that's good enough that you can run a ``G26`` top print a test pattern and then tweak with ``M421``.

**Comment by jneilliii** [comment]
So there are two possible plugins that can be utilized for this. You could use [Bed Level Visualizer](https://plugins.octoprint.org/plugins/bedlevelvisualizer/) and put the commands in the settings to run through the process for you and give you a nice display of the bed once complete. You could even split up the stages within that plugin as custom buttons if you want a wizard approach.

There is also the [OctoPrint-UBLMeshEdit](https://plugins.octoprint.org/plugins/ublmeshedit/) that gives you the ability to adjust the mesh live within the OctoPrint interface. 

I think with either of these two options this is sufficient to close this issue.
