### ISSUE TITLE
Request: "Upload -> print -> delete" feature for stl's using cura

### ISSUE THREAD

**Issue by Duckle29** [OctoPrint/OctoPrint#298]
Hello, I'd very much like a feature that would allow me to upload an stl file, use the cura engien that as it is currently being tested, and then deleting the files when done printing. This would really help, as the printer in question is at a school, and being the only one who knows how to setup a slicer, having people being able to just hit "upload -> print -> delete" would help a ton. As this is to be used on a school, a feature to have this permanently enabled in the settings tab would be nice too :)

**Comment by jneilliii** [comment]
OctoPrint Connection plugin in Cura can upload and auto start the print, and [DeleteAfterPrint](https://plugins.octoprint.org/plugins/DeleteAfterPrint/) can do the remainder, closing.
