### ISSUE TITLE
[Request] Upload 'n Print! checkbox

### ISSUE THREAD

**Issue by HenryAlfredo** [OctoPrint/OctoPrint#3152]
First of all thanks for this software i really like using it.

My request is to add a checkbox which toggles to immediately start printing as soon as the .gcode upload has finished. 

Maybe somewhere near this text: _Hint: You can also drag and drop files on this page to upload them_

In the long run this will save some time, especially for people printing many design iterations daily.

**Comment by foosel** [comment]
I'm not gonna add something like this to core since it can be dangerous (uncleared build plate). However it's something that someone could easily add through a plugin.

**Comment by HenryAlfredo** [comment]
Yes i can understand that, had my fair share of collisions. Thanks again for the software and the new label.

**Comment by dovecode** [comment]
@HenryAlfredo what I found useful was the [Autoselect plugin](https://github.com/OctoPrint/OctoPrint-Autoselect). It loads the last uploaded file, so all you need to do is click Print after uploading.

**Comment by evanquinnalaska** [comment]
If you use Slic3r PE it has it avaliable out of the box :)
![image](https://user-images.githubusercontent.com/20997794/58713568-b1de6600-8377-11e9-9c8f-dccded59d04a.png)

**Comment by LazeMSS** [comment]
Like this: https://plugins.octoprint.org/plugins/AutostartPrint/
