### ISSUE TITLE
Laser Engraver Support

### ISSUE THREAD

**Issue by NinjaJake86** [OctoPrint/OctoPrint#322]
Hey! I'm building a combined 3D printer and laser engraver, i want to use the same boards for control and operation, i plan to use a RAMPS 1.4 to control the 3D printer, i am going to try and set it up with a 3rd extruder which is the laser, it would be good to be able to upload bitmap files to it for it to begin laser etching/engraving

**Comment by LazeMSS** [comment]
Closed - as @foosel  wrote it should work and also there are now plugins to make it even better:
https://plugins.octoprint.org/plugins/bettergrblsupport/
