### ISSUE TITLE
[Request] In the files list show filament usage in grams alongside/instead of length and volume

### ISSUE THREAD

**Issue by CodilX** [OctoPrint/OctoPrint#3231]
**Is your feature request related to a problem? Please describe.**
In my opinion tracking filament usage in grams is easiest and most reliable. I also use [FilamentManager](https://github.com/malnvenshorn/OctoPrint-FilamentManager) that allows you to track remaining filament for your spools - in grams. Every time I export a model from Simplify3D I also take into account the filament usage in grams, but for some reason length and volume are the two values used in OctoPrint with no option to use weight in the files section. I find both values useless and I keep downloading my .gcode files and put them back into S3D to re-check the required filament needed for my prints. 

![Untitled-1](https://user-images.githubusercontent.com/476633/61570275-3b670600-aa94-11e9-89fc-1fef06ae2001.png)

**Describe the solution you'd like**
Add an option to choose between the desired filament usage methods. I'd love to just have filament usage in grams and hide length and volume as they're totally useless to me. Having grams in the files section alongside using the FilamentManager plugin would be bliss - checking your spools remaining filament and how much the model will use would take literally a few seconds.

**Additional context**
Thank you to everyone who contributes to OctoPrint, it really makes 3D printing that much better.

**Comment by fieldOfView** [comment]
In order to calculate the weight from the volume (which is calculated from the length), OctoPrint would have to know the exact density of the filament you are printing with. Out of the box, OctoPrint does not know (or care) about which material you are printing with.

The filament manager plugin seems to do what you want: https://plugins.octoprint.org/plugins/filamentmanager/
