### ISSUE TITLE
[Request] Change slugify behavior for files/folders name 

### ISSUE THREAD

**Issue by Rejdok** [OctoPrint/OctoPrint#3333]
**Descriprion**
Hello. I use octorpint on raspberry/orange pi. Slugify renames all files and directories in upload folder. So if I create mount point for usb stick in upload folder it renames all files on it and changes files timestamp. If I dont give write access, some files/folders doesn't show. 

**Possible solutions**
Create layer, which resolves slugify name and name on disc.
Change file operation api(not very good idea).

**Alternatives**
It doesn't resolve full problem. But much more easier solution is rename folders witch contains files with allows extension and rename file with allowed extension with restoring it timestamp.

**Comment by cp2004** [comment]
This issue is no longer relevant as OctoPrint doesn't slugify filenames by default any more.
