### ISSUE TITLE
GCode viewer shows "empty" layer, but other viewers interpret the GCode fine. Actual print via OctoPrint is also laying no filament on the "problematic" layer.

### ISSUE THREAD

**Issue by UberEclectic** [OctoPrint/OctoPrint#3339]
#### What were you doing?

1. Send Print to OctoPrint (Cura -> OctoPi via plugin in this case)
2. Observe in GCode viewer that one of the early layers is being interpreted with very few commands (e.g. 6), instead of 100's and that while the Z-axis increments, there is no filament rendered in the display.
3. Use another GCode viewer from similar codebase, a la gcode.ws, and check the GCode tab to see what's really going on.
4. Observe that on the "problematic" layer the GCode tab shows a few commands (e.g. 6) from early in the source file instead of the hundreds of commands from the actual missing layer.
5. Use another GCode viewer such as Repetier Host and observe no issues with the GCode.

#### What did you expect to happen?

Render and more specifically, print correctly.

#### What happened instead?

Both the GCode view and the actual print reflect the misinterpreted layer.
In the case of the actual print the Z-axis was incremented without laying any filament, so the next layer was printing "in thin air" and the whole print was utterly failed as a result.

#### Did the same happen when running OctoPrint in safe mode?

Did not try because same GCode uploaded directly to OctoPrint UI without the Cura plugin is showing all the same bad behavior.

#### Version of OctoPrint

OctoPrint 1.3.12 running on OctoPi 0.16.0

#### Operating System running OctoPrint

Raspberry Pi:
Linux octopi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

#### Printer model & used firmware incl. version

Lulzbot TAZ Workhorse
v2.0.0.144 (Marlin)

#### Browser and version of browser, operating system running browser

Safari (latest).  Mac, iPad Pro, etc.

#### Link to octoprint.log

https://gist.github.com/UberEclectic/b149487e6f76bb5d4836e7ce5938afee

#### Link to contents of terminal tab or serial.log

Not enabled.

#### Link to contents of Javascript console in the browser

I'll come back to this (so I don't lose these edits).

#### Screenshot(s)/video(s) showing the problem:

I'll come back to this (so I don't lose these edits).

I have read the FAQ.

**Comment by UberEclectic** [comment]
Ugg. My submission was reset when I logged into the OctoPrint host to get the uname -a version.
I'll have to start the whole report over.  :-/

**Comment by UberEclectic** [comment]
I am happy to share the gcode, but it's quite large and I do not see how to include a compressed binary archive to either of the mentioned file-sharing sites.

**Comment by foosel** [comment]
I fear I'll really need access to GCODE with which to reproduce this. Do you maybe have a smaller minimal example file in your collection that shows the same behaviour?

**Comment by foosel** [comment]
> In the case of the actual print the Z-axis was incremented without laying any filament, so the next layer was printing "in thin air" and the whole print was utterly failed as a result.

Also just for the record, that is very interesting. OctoPrint really just takes the GCODE file and streams it line by line to the printer. If no filament was layed down, either there were no commands in the file to lay it down or the firmware misinterpreted something. The only modification stock OctoPrint does to GCODE files as it sends them is tack on a line number and checksum during transmission to be able to compensate for errors.

Please also share a full `serial.log` of a failing print so we can compare what's in the file with what goes over the line.

Also please try safe mode - the GCODE viewer issue and the printing issue happen at different parts of the codebase and the backend can *definitely* be influenced by plugins.

**Comment by UberEclectic** [comment]
Hi, @foosel!  I wondered about that.  Really my assumption was that you are passing the gcode straight through, so I was surprised that printing via OctoPrint vs. gcode on SD card had a different result.  I had 5 failed attempts, which I at first blamed on finicky filament before I started carefully inspecting the gcode in OctoPrint's built-in viewer and saw the "emtpy" layer.

**Comment by UberEclectic** [comment]
Looks like I can just drag the gcode file into a comment.  =D

If you check it out on gcode.ws and step through the layers (cursor up/down) in the GCode viewer tab (click the tab to have the line jump to the current layer), and watch what happens between layer 6 and 7 and from layer 8 back down to 7, you'll see that it jumps to line 44 for layer 7.  Very strange.

Using Repetier Host to step through the layers, while looking at the GCode is properly showing layer 7 in tact.  That matches what Cura shows in its layer viewer, where the GCode was generated.

[TAZWHE05MM_CDK125-FocuserDustCover v6.gcode.gz](https://github.com/foosel/OctoPrint/files/3846746/TAZWHE05MM_CDK125-FocuserDustCover.v6.gcode.gz)

**Comment by UberEclectic** [comment]
Incidentally, I came across this forum post, which I can't help but suspect is related.
I have some printer setup code at the start of every job...

https://community.octoprint.org/t/octoprint-inserts-do-nothing-layer-2/9969/3

**Comment by foosel** [comment]
So I just took a look into the file, and the empty layers here are caused by "sort layers" being enabled by default:

![image](https://user-images.githubusercontent.com/83657/69043265-0bece980-09f3-11ea-9da8-704a40f86049.png)

If you disable it so that the viewer doesn't sort by Z height but shows the layers in the order they appear in the file (which isn't default because it can confuse the heck out of people) you see that all those layers are part of the nozzle cleaning routine at the start of the print.

Note that the sorting *only* happens in the viewer on the frontend, strictly on client side. There's nothing done to the file as it gets streamed to the printer by OctoPrint, at least not in core OctoPrint. It could be a thirdparty plugin causing this however, so please try in safe mode. Also enable `serial.log` and if it continues to happen in safe mode share that please.

**Comment by foosel** [comment]
@UberEclectic Any outcome for the above suggestions?

**Comment by foosel** [comment]
Closing due to lack of response.
