### ISSUE TITLE
[Request] Option to disable external access notification at login

### ISSUE THREAD

**Issue by Valinwolf** [OctoPrint/OctoPrint#3406]
I have my OctoPrint instance set behind 2 different firewalls. My router only allows my off-site server to access my OctoPrint instance and my off-site server only allows a select number of IPs to access it over SSL with HTTP basic auth. I have security covered, and the little notification is incredibly annoying every time I log in. I would like a way to disable this pestering non-stop non-issue security notice.

**Comment by cp2004** [comment]
This has been a thing for a long time, and is in the documentation. https://docs.octoprint.org/en/master/configuration/config_yaml.html#server
