### ISSUE TITLE
[Request] please add a 16:9 screen layout - best auto-switched.

### ISSUE THREAD

**Issue by dothebart** [OctoPrint/OctoPrint#3412]
Most computer displays nowadays are 16:9 - 4:3 s vanished. Octoprints UI however mostly shows 4:3 layout. The most anoying result of that is that the file upload button and the file selector dialog is out of reach when using the rest of the UI. 
Please use the full available screen realestate for octoprint.

**Comment by tedder** [comment]
@dothebart how are your css/responsive skills?

**Comment by dothebart** [comment]
Well, if they'd be anywhere near mentionable I'd have sent a pr ;) I'm a C/C++ Backend guy.

**Comment by LMS0815** [comment]
Might be possible to add something to:  [Themeify plugin](https://plugins.octoprint.org/plugins/themeify/)

**Comment by jneilliii** [comment]
Details on the community forum. 
 https://community.octoprint.org/t/pimp-my-web-interface/3349

Also, the widescreen plugin allows you to micr some things around.

**Comment by dothebart** [comment]
Ah, thanks for the sugestions, I was searching the plugins, but didn't find these. 
Can any of these be made the sane default in future?

**Comment by tsmes** [comment]
It seems like the UI depends on Bootstrap v2.3.1 released in 2012. I could take a crack at updating the UI to a newer layout but before taking on a task like that it would be nice to know what the target browser support is.

**Comment by fieldOfView** [comment]
@tsmes: Not an answer to your question, but nevertheless a discussion with some possible directions here:
https://github.com/foosel/OctoPrint/issues/2420

**Comment by LMS0815** [comment]
Themeify plugin / Try this to dynamically use the full screen width:
![Anmerkung 2020-01-09 142128](https://user-images.githubusercontent.com/8235214/72071078-42582e00-32eb-11ea-87f6-d6c9301f90b7.png)

`calc(95% - 340px)`

**Comment by stantond** [comment]
A slight tangent... maybe this raises the need for a tech debt issue to update to the latest version of Bootstrap (currently v4.4.1 at https://getbootstrap.com/).

@foosel maybe some of the 1.4.x iterations could be updating other components and dependencies before adding features, given it's the Python 3 release? Or maybe it's best to leave 1.4 to stabilise after release, and think of other dependency updates from 1.5? (P.s. let me know if you could use a hand building a roadmap, can't contribute production quality code but can certainly help with product management).

**Comment by johankvint** [comment]
@tsmes I would be happy to help.
Updating to bootstrap 4 should not be "that" hard.
And we could also keep the grid classes from old bootstrap to support most plugins.

Main reason I started looking in here was to see if there where any plans for better file management, but this could be a fun project too :)

**Comment by jasonbcox** [comment]
I've come across this issue as well. I can look into authoring a patch myself, but the backwards compatibility requirement may negatively impact code quality until the next major release (I imagine lots of inlined if-statements. not good). I'm not sure if this is something the maintainers are ok with, and such an impactful change will likely require closer coordination.

Some thoughts:
* Is there any data to indicate how many plugins (and by extension, users) are impacted specifically by reflowing the UI horizontally?
* How many of the above plugins can be safely eliminated with a better UI? Any "wide layout" type plugins would be no longer necessary, for example.
* Is there a reason to keep Bootstrap at all? Many projects use [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) directly. This would eliminate a dependency and flexbox is supported on all modern browsers these days.

**Comment by cp2004** [comment]
There is work ongoing to prepare for a UI re-write. For example, creating https://bundleviewer.octoprint.org React and Material UI were used. Plugins like OctoPrint widescreen work with most plugins, so there shouldn't be much of an issue just re-sizing things per se. But it is a decent change to the look and feel that there is little enthusiasm for when a complete redesign is on the horizon.

Backwards compatibility is a huge issue here, such that the plan is to use [UI plugins](https://docs.octoprint.org/en/master/plugins/mixins.html#uiplugin) to allow us to test concepts and create a gradual switch over.

**Comment by LazeMSS** [comment]
Possible by plugin:

https://plugins.octoprint.org/plugins/uicustomizer/

**Comment by jneilliii** [comment]
Don't forget [Consolidated Tabs](https://plugins.octoprint.org/plugins/consolidatedtabs/) or [Widescreen](https://plugins.octoprint.org/plugins/widescreen/) plugins, there may be more.
