### ISSUE TITLE
[Request] Adding a Web App Manifest for "Add to Homescreen" (Android Chrome).

### ISSUE THREAD

**Issue by JohnEdwa** [OctoPrint/OctoPrint#3420]
**Is your feature request related to a problem? Please describe.**
Using Octoprint with a mobile browser has the URL bar and such at the top, obscuring the view, and it is also just another tab. But it could be better.

**Describe the solution you'd like**
Adding a [Web App Manifest](https://developers.google.com/web/fundamentals/web-app-manifest) that includes "display": "standalone" will allow (Android Chrome at least) to properly utilize the "Add to Homescreen" functionality which will create an app shortcut that will then launch Octoprint in a completely UI-less browser window, mimicking a native app. As a bonus, it will register itself to the app-switcher too.

Something like this works: 
```
<link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">

{
  "name": "OctoPrint",
  "icons": [
  {
    "src": "static/img/apple-touch-icon-144x144.png",
    "type": "image/png",
    "sizes": "144x144"
  }
  ],
  "start_url": "/",
  "background_color": "#000000",
  "display": "standalone",
  "orientation": "landscape"
}
```

~~The background colour is non-negotiable, any app that starts with a blinding white splash screen should be destroyed and the devs burned at the stake.~~

**Additional context**
Without the manifest, just a browser tab:
![Screenshot_Chrome_20200106-223132](https://user-images.githubusercontent.com/5417183/71847486-a73a3b00-30d5-11ea-8beb-5d496bdd4ad5.png)

With the manifest, after using the "Add to Homescreen" in Chrome:
![Screenshot_Chrome_20200106-223219](https://user-images.githubusercontent.com/5417183/71847523-be792880-30d5-11ea-857c-1f96ad5a3972.png)

The splash-screen:
![Screenshot_Chrome_20200106-223900](https://user-images.githubusercontent.com/5417183/71847546-ca64ea80-30d5-11ea-974f-1c5b74cfb608.png)

**Comment by foosel** [comment]
Pushed to `maintenance` and ready for 1.4.1.

**Comment by fieldOfView** [comment]
Why a black background though, when the default interface is bright white?

**Comment by foosel** [comment]
At least the devices that I know lean towards dark stock UI schemes (notification bar and such). In that case a black background feels more "native". With so many people out there using Themeify with a dark theme it doesn't hurt in that regard either. And frankly, it's visible for such a short fraction of time that I don't feel like spending too much time on that decision ;)

**Comment by fieldOfView** [comment]
ok

**Comment by foosel** [comment]
1.4.1 has just been released
