### ISSUE TITLE
Artillery Sidewinder X1 SW-X1

### ISSUE THREAD

**Issue by prokazzzzza** [OctoPrint/OctoPrint#3441]
Hello. Is it possible to add printers to the list
Artillery 3d printer Sidewinder X1 SW-X1

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
