### ISSUE TITLE
[Request] adding a function to distinguish between heated chamber, autochamberfan and only a "chamber"/room tempsensor

### ISSUE THREAD

**Issue by docgalaxyblock** [OctoPrint/OctoPrint#3469]
BIG EDIT:

Okay, so I'm gonna try it again.
I suggest to have a possibility to distinguish between the different types of heated chambers

 1. no chamber
 2. a sensor as chamber/room temperature sensor
 3. no internal heater (at most the heating board) and only one automatic exhaust fan
 4. an internal heater, but no exhaust fan
 5. an internal heater and an exhaust fan

Perhaps these five scenarios are a little overly detailed... 3-5 can be summarized under one point.

For case two I would like to see no temperature control in the temp tab and thus no target temperature in the graph.
Case three to five should have the temperature control again.

I hope I have now explained my idea well and understandably.

@foosel Issue updated

**Comment by fieldOfView** [comment]
> I think this says it all in a nutshell

I don't think it does. Apart from showing those two checkboxes, what would this do? Would anything change in the OctoPrint interface or how the temperatures are shown in the graph?

**Comment by foosel** [comment]
Agreed, this really does not "say it all in a nutshell". More details please. What where why.

**Comment by docgalaxyblock** [comment]
@foosel Request updated

**Comment by jneilliii** [comment]
So I think my PlotlyTempGraph plugin can handle all these requests of labeling, hiding/showing temps, etc. closing.
