### ISSUE TITLE
[feature request] Simple delay before starting print option.

### ISSUE THREAD

**Issue by TomekBrz** [OctoPrint/OctoPrint#349]
I was hoping there would be a way to "start print in X hours." I keep my printer in my dorm apartment, and wake up often earlier than others in the apartment.   I suppose many people find this the exact moment Octoprint shines, because they can just SSH later and start the print. However, I cannot access my octoprint outside of my home for various reasons [I think this is not so unusual]

I looked towards inserting a "dwell" command at the start of my file's code,  "G4 S7200" to wait for two hours before starting the print. But it seems gCode cannot be edited within Octoprint, although commands can be sent through the terminal (I dont want to heat up the bed and wait two hours, i want it to be the first command.)

I don't know if this is a problem for enough people, but if there were a feature to "start print in X hours" I am at least bringing up that the G4 command would be a relatively simple way to implement it. 

Thanks!! Octoprint is snazzy and wonderful. I'm overall really enjoying it.

**Comment by erplanes** [comment]
Seconding this request

**Comment by LazeMSS** [comment]
This is now implemented by:
https://plugins.octoprint.org/plugins/procastinator/
