### ISSUE TITLE
[Request] Add default state for terminal tab filter settings

### ISSUE THREAD

**Issue by Sembazuru** [OctoPrint/OctoPrint#3542]
**Is your feature request related to a problem? Please describe.**
I almost never want to have the temperature messages not filtered. When I load OctoPrint in a browser for the first time (or force a refresh) when I first go to the terminal tab I have to re-enable the temperature message filter. The setting seems to be persistent as long as I don't close or force a refresh on the window/tab that is showing OctoPrint.

**Describe the solution you'd like**
I'd like to see in the terminal filter settings a checkbox for each configured filter that has the default setting of the filter, on or off.

This is a low priority request, but hopefully it is easy enough to be handled quickly as low-hanging-fruit. ;-)
With my luck, this "simple" request can only be reasonably done by refactoring 75% of the code base...

**Comment by jneilliii** [comment]
There's a plugin for this (shameless plug, it's mine).

https://plugins.octoprint.org/plugins/active_filters_extended/

**Comment by Sembazuru** [comment]
> There's a plugin for this (shameless plug, it's mine).
> 
> https://plugins.octoprint.org/plugins/active_filters_extended/

I've installed this plugin, and it works as advertised. Thanx.

**Comment by foosel** [comment]
Closing then since there's a plugin.
