### ISSUE TITLE
[Request]  API File Upload Local Destination Watched Folder

### ISSUE THREAD

**Issue by chrishilbert** [OctoPrint/OctoPrint#3543]
Current the Cancel Object plugin reads from the watched folder.  However, the API only allows uploads to the upload folder.  When using the Cura OctoPrint Connection, it sends files directly to the upload folder using the API.  It would be great if the API allowed files being uploaded to the watched folder so the Cancel Object plugin would see it.

**Comment by fieldOfView** [comment]
> Current the Cancel Object plugin reads from the watched folder. 

As I have explained on the forum, this is not true.

**Comment by foosel** [comment]
Closing, seems invalid based on the discussion.
