### ISSUE TITLE
[Request] - "Download Selected" in Timelapse

### ISSUE THREAD

**Issue by KenLucke** [OctoPrint/OctoPrint#3544]
Can you please add a button to "Download All Selected" timelapse videos on the Timelapse tab, instead of having to do them one at a time (unless I'm missing an existing way to do this).  The files could be selected in the already existing way as they are for the "Delete" function but instead, it would allow all selected ones to be pulled at the same time.

**Comment by foosel** [comment]
1.6.0 has just been released including this.
