### ISSUE TITLE
[Request] Clean hotend / change filament command

### ISSUE THREAD

**Issue by rlaferla** [OctoPrint/OctoPrint#3548]
OctoPrint needs to be more user-friendly.  Currently, to change filament to a different color, you have to heat up the hot end and extrude the old color.  There should be a command in the UI to do this.  Perhaps, each printer has a different temp setting for it, extrude length/time, etc...

**Comment by jneilliii** [comment]
This is exactly what [Custom Controls](https://docs.octoprint.org/en/master/features/custom_controls.html#sec-features-custom-controls) are for. If not comfortable with editing config.yaml manually there is a plugin called [Custom Control Editor](https://plugins.octoprint.org/plugins/customControl/) that will allow you to add the buttons you need.

**Comment by rlaferla** [comment]
It's not that you can't get this functionality.  It's that it should be easy and accessible without any configuration by the average user.  OctoPrint is too complex for the average user and is geared for advanced users.  There's no reason why the UI can't accommodate both types of users.

**Comment by foosel** [comment]
There is. Someone needs to maintain all this. That someone is mostly me.

Help is welcome. Especially in the form of an externally maintained plugin that does this.

**Comment by BeatSlayer** [comment]
There is an existing plugin for that: [Change Filament](https://plugins.octoprint.org/plugins/Change_Filament/)

**Comment by foosel** [comment]
Even better, closing.
