### ISSUE TITLE
[Request] Backups Saved to USB Storage

### ISSUE THREAD

**Issue by shatteredsite** [OctoPrint/OctoPrint#3556]
A simple file manager system to select a location/folder to save backups to. SD cards have a limited lifespan and have always been a weak spot on the Raspberry Pi's reliability. Since the _Raspberry Pi 4_ does not currently/natively support booting from a USB device, having the option to set a folder on a connected USB device for backups ensures that SD card corruption does not affect those backups.

**Comment by tedder** [comment]
Hi shatteredsite, you can certainly symlink the backup dir. As a test, I did this:
```
rm -rf .octoprint/data/backup
mkdir -p /tmp/backup/
ln -s /tmp/backup .octoprint/data/backup
```

If you're very concerned, you should probably move other bits off the SD card too- timelapses, uploads, and logs are some of the noisiest.

I'm closing this. It's certainly a valid request, but OctoPrint (and even the Pi-specific distro OctoPi) don't really worry much about filesystems.
