### ISSUE TITLE
[Request] History of Prints

### ISSUE THREAD

**Issue by bryannevega** [OctoPrint/OctoPrint#3565]
If would be awesome if we could see a history of prints, including the time it took, the finalized print (3D view) and details of costs (electricity, material (possibly some added costs like: glue, alcohol or cleaning supplies).

Thank you for making this the best project I've seen!

![image](https://user-images.githubusercontent.com/56166962/81625031-c61f4580-93c5-11ea-84f5-476484f4f6c3.png)

**Comment by jneilliii** [comment]
There is a plugin in development for this, you may want to check it out.

https://github.com/OllisGit/OctoPrint-PrintJobHistory
