### ISSUE TITLE
Plugin stuck in install loop

### ISSUE THREAD

**Issue by Eros** [OctoPrint/OctoPrint#3577]
#### What were you doing?

Updating ABL Expert Plugin

1. Login
2. Wait for the popup to update plugin to show
3. Click the update
4. Wait for it to finish
5. Restarts the plugin install

#### What did you expect to happen?

Update the plugin from the old version (0.5) to the new version (0.6)

#### What happened instead?

Stuck in install loop of installing 0.5 not new version

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
Latest

#### Operating System running OctoPrint
OctoPi 0.17.0

#### Printer model & used firmware incl. version
Creality Cr10S

#### Browser and version of browser, operating system running browser
All

#### Link to octoprint.log
https://pastebin.com/PkJuuCL0

#### Link to contents of terminal tab or serial.log
https://pastebin.com/RxbhqwfD

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.
Yes

**Comment by jneilliii** [comment]
This is a plugin issue, not an octoprint issue.
