### ISSUE TITLE
[Request] Processing Gcode, while streamed to the printer

### ISSUE THREAD

**Issue by TheMrPhantom** [OctoPrint/OctoPrint#3584]
To display things like what type of line the printer is printing at the moment (e.g. perimeter, supports, infill...) a feature that allows to intercept the gcode between octoprint and the printer would be nice, since the gcode might contain these informations if the slicer added comments.

Maybe storing the data in an sql database for easy access from outside of octoprint or something in python to manually store these informations read from the gcode in an sql database

**Comment by foosel** [comment]
There have been hooks for that for 5 years now:

https://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-gcode-phase

They don't include comments but with a bit of file preprocessing on upload and custom codes that could also be aslch8eved already.
