### ISSUE TITLE
[Request] Addditional Gcode Viewer Controls

### ISSUE THREAD

**Issue by KenLucke** [OctoPrint/OctoPrint#3595]
Because the gcode viewer's "Center viewport on model" and "Zoom in on model" apparently do their position and size calculations based upon the full width and depth of the model throughout all layers, it throws the centering and size of the model off because of the purge line that I start every print with along the edge of the buildplate.  

Thus, even if the model is only, say, a  centered 20mm calibration cube, it includes my 200mm long purge line 5mm in from the edge of my 310mm build plate, and calculates a model 200mm x 160mm in size, and "zooms" or "centers" on that calculated model.  Also, this fails to take into account the fact that some layers may be wildly differently placed in reference to the center or size of the model  than the overall calculation.

My proposal:  Add a couple of dropdowns for the zoom and center controls:
```
[] Center viewport on: [ model  ]
                       [ layer  ]
[] Zoom in on: [ model  ]
               [ layer  ]
```

OR a couple of radio buttons to do the same:
```
[] Center viewport on:  O Model  O Layer
[] Zoom in on:  O Model  O Layer
```

**Comment by ManuelMcLure** [comment]
Another (maybe easier to implement) possibility would be to add a setting (maybe via a plugin) that would tell the gcode viewer to ignore anything in the gcode file before (a) specific comment(s) that could be added to the slicer's start gcode (or which the slicer generates already). If none of the understood comments are in the file then it would behave as it does now.

**Comment by KenLucke** [comment]
> Another (maybe easier to implement) possibility would be to add a setting (maybe via a plugin) that would tell the gcode viewer to ignore anything in the gcode file before (a) specific comment(s) that could be added to the slicer's start gcode (or which the slicer generates already). If none of the understood comments are in the file then it would behave as it does now.

No, I'd rather it be capable of focusing on a particular layer (and the previous/next layer as it does now) so that if a print, say, starts out the first few layers in bed center, but as it gets higher, its center of the printed layer moves off to the front right, back center, left rear, or wherever, the viewport center focus stays on it, if that's what you choose in the options.

**Comment by foosel** [comment]
This has been implemented by #3880 and will be part of 1.6.0.

**Comment by KenLucke** [comment]
Awesome.  Thank you, you Devs are great.

**Comment by foosel** [comment]
1.6.0 has just been released.

**Comment by richfelker** [comment]
This change broke the ability to follow how layers stack on each other while scrolling in Z, since it now recenters to each layer. Could it please be made optional to restore the old behavior?
