### ISSUE TITLE
[Request] Add safety shutdown sensors to PSU Control Plugin

### ISSUE THREAD

**Issue by wrpetersen** [OctoPrint/OctoPrint#3605]
**Is your feature request related to a problem? Please describe.**
The PSU Control plugin is excellent as it has the ability to remotely power down the whole printer when not in use. I would like it to be able to shut down if safety sensors trigger in my 3d printer's enclosure as well.

**Describe the solution you'd like**
I would like to use an inexpensive MQ-135, MQ-2 or similar detector board that can be found readily on Ebay as well as a thermocouple inside my 3d printer enclosure. These sensors would feed back to unused pins on the raspberry pi and trigger the PSU Control plugin to cut power to the printer if smoke/hydrocarbons are present or if the enclosure goes above a user defined temperature level. I also think it would be nice if there was a heater cut off option at a lower sensor threshold to hopefully allow the extruder fan to cool everything down before the hazard escalates in the event of a thermistor failure for example. The full PSU shutdown if the situation gets worse would cover a situation where a stuck heater relay is causing a thermal runaway or an electrical short. I would also like the ability for the server to push a notification via Email and/or SMS if the safety sensors detect a hazard to get the user's attention of a possible fire or smoldering condition. 

**Describe alternatives you've considered**
N/A.

**Additional context**

**Comment by fieldOfView** [comment]
This issue queue is for OctoPrint, not for its contributed plugins. Please post this issue on the PSU Control issue queue, which can be found here:
https://github.com/kantlivelong/OctoPrint-PSUControl/issues
