### ISSUE TITLE
Lcd displaying print finished

### ISSUE THREAD

**Issue by Commiccannon** [OctoPrint/OctoPrint#3611]
#### What were you doing?

1. Flashed Marlin 2 after having Klipper running for some time and now LCD after about 2 mins will go to the print finished screen

#### Link to octoprint.log
[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/4808994/octoprint.log)

#### Link to contents of terminal tab or serial.log
[serial.log](https://github.com/OctoPrint/OctoPrint/files/4808993/serial.log)

#### Screenshot(s)/video(s) showing the problem:
![Printer](https://user-images.githubusercontent.com/63322372/85218222-7fb50180-b3db-11ea-8af0-f6c02cd68f11.jpg)
Sorry for the line on the left that dosnt work

I have read the FAQ.

**Comment by jneilliii** [comment]
That's not an octoprint issue.

**Comment by fieldOfView** [comment]
This issue tracker is strictly for bugs in OctoPrint. This seems to be a firmware issue. Perhaps you can get better support at the OctoPrint community forum (https://community.octoprint.org), which is more suitable for support requests than this issue tracker. But you may also want to check out fora that are more catered towards Creality printers and/or Marlin. 

This issue can be reopened if you convince us OctoPrint is doing something wrong.
