### ISSUE TITLE
[Request] View only permissions

### ISSUE THREAD

**Issue by 4sfaloth** [OctoPrint/OctoPrint#3612]
Hi all,

I wanted to have a way to access octoprint in view-only mode, that is, I'd like to see the video feed and the printer's temperatures etc... but I would like to have all controls (including cancel print) disabled. This is so I can monitor a print while doing other stuff in any device (phone, tablet, etc...) without fear of inadvertedly pressing and key and messing it up.

I thought this was possible with the user permissions' feature, but the only possibilities it gives me is 'admin' or 'non-admin', and it seems to only have an impact on what I can do to the octoprint instance itself (ie: without being 'admin' I cannot order the pi to shutdown for instance).

Has this been considered before? Do you feel it would be a nice addition?

Thanks in advance

**Comment by foosel** [comment]
Known issue, already tracked in #3547, going to be fixed with 1.4.1
