### ISSUE TITLE
Total layers in progress bar needs additional space for value

### ISSUE THREAD

**Issue by jcwren** [OctoPrint/OctoPrint#3613]
#### What were you doing?
Printing a print with more than 999 layers.

#### What did you expect to happen?
Total layer count text not to overwrite 'Height' text.
#### What happened instead?
Total layer count test overwrote 'Height' text.
#### Did the same happen when running OctoPrint in safe mode?
Irrelevant 

#### Version of OctoPrint
1.4.0

#### Operating System running OctoPrint
OctoPi 0.17.0

#### Printer model & used firmware incl. version
Prusa Mk3 w/ 3.9.0

#### Browser and version of browser, operating system running browser
Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)

#### Screenshot(s)/video(s) showing the problem:
![StatusBar](https://user-images.githubusercontent.com/529578/85306767-f7873880-b47c-11ea-865f-74c68b67084f.png)

I have read the FAQ.

**Comment by foosel** [comment]
That is not part of core OctoPrint but rather a third party plugin. You need to report that on the issue tracker of the plugin, not here.
