### ISSUE TITLE
List of cameras that work with octoprint missing

### ISSUE THREAD

**Issue by Tech559** [OctoPrint/OctoPrint#3614]
where did the list go of compatible cameras go this link no longer works
https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work
it was a page that had a list of all the cameras where did it go?

**Comment by foosel** [comment]
Forum, like everything else that is "knowledgebase material".

https://community.octoprint.org/t/usb-webcams-known-to-work-with-mjpg-streamer/21149

**Comment by Tech559** [comment]
thanks!!
