### ISSUE TITLE
[Request] Ability to support multiple printers

### ISSUE THREAD

**Issue by posicat** [OctoPrint/OctoPrint#3618]
**Is your feature request related to a problem? Please describe.**
I've setup multiple printers manually, but it's a pain to do every time a new installed needs to be loaded on the SD.

**Describe the solution you'd like**
It would be great if the instances of the video and octoprint were setup in such a way that there was a simple command line option to add a second instance of Octoprint.  Especially on the new Pi 4's there's more than enough resources to run 3 or 4 at once.  Myself I have 2 printers, soon to have a 3rd.

**Describe alternatives you've considered**
I don this manually, but it's not a fun process.  And it seems a waste to buy a second Pi just to run a second instance.

**Comment by foosel** [comment]
This is not going to happen any time soon as the challenges with the current architecture and the expected support overhead are enormous.

**Comment by Moorviper** [comment]
You can use https://github.com/paukstelis/octoprint_deploy to setup multiple instances.

**Comment by jneilliii** [comment]
Interesting script @Moorviper, does it clear API keys, salt ,etc.?

**Comment by Moorviper** [comment]
No this is something you have to do manually.

**Comment by tedder** [comment]
[Here's the community-supported megathread](https://community.octoprint.org/t/multiple-printers-per-server-megathread/7778). It isn't supported (by Gina et al) for a good reason. If you are _really_ motivated, you could consider making a variant of OctoPi that sets things up.

**Comment by fieldOfView** [comment]
> If you are really motivated, you could consider making a variant of OctoPi that sets things up.

You could call it HexaDecaPi
