### ISSUE TITLE
OctoPrint Web Interface stops receiving temperature information/receives wrong information

### ISSUE THREAD

**Issue by Nufflee** [OctoPrint/OctoPrint#3621]
#### What were you doing?

1. Open OctoPrint in browser
2. Connect to printer
3. Observe

#### What did you expect to happen?
Correct temperature information displayed.

#### What happened instead?
Web interface completely stops receiving temperature messages after about 10 seconds and/or just displays wrong data. The rest of the interface seems to be functional during this time.
I can see the messages received correctly in the `serial.log` and I also noticed that it resumes to display temperatures very briefly every few minutes. The printer is otherwise functioning normally and correct temperatures are displayed on the LCD.

Also, all of this is using basically fresh Raspbian, OctoPrint and printer firmware installation.

#### Did the same happen when running OctoPrint in safe mode?
Yes.

#### Version of OctoPrint
1.4.0

#### Operating System running OctoPrint
Raspbian Buster on a Pi 3B+

#### Printer model & used firmware incl. version
CR-10, Marlin 2.0.5.3 

#### Browser and version of browser, operating system running browser
Chrome, Windows 10

#### Link to octoprint.log
https://gist.github.com/Nufflee/74ba6fe6445e99db13c4aae0fc3819b4

#### Link to contents of terminal tab or serial.log
https://gist.github.com/Nufflee/74ba6fe6445e99db13c4aae0fc3819b4

#### Link to contents of Javascript console in the browser
https://gist.github.com/Nufflee/1362d750f1f36df341ac259c976a49d3

#### Screenshot(s)/video(s) showing the problem:
This is an image based on the uploaded logs - you can see the sharp jumps in temperature:
![image](https://user-images.githubusercontent.com/19150550/86303575-7cf0b280-bc0c-11ea-8b2c-4ba650b5569b.png)

This is another image from an older run:
![image](https://user-images.githubusercontent.com/19150550/86303612-9f82cb80-bc0c-11ea-802a-2e3bc1a3794b.png)

I have read the FAQ.

**Comment by tedder** [comment]
That is strange, especially the jump on the X axis. However, there are a bunch of connection errors in your connection log (note you didn't link your serial log). However, until this a known bug, please post to [the discussion forums](https://community.octoprint.org/c/support/7), it's the best place to confirm a bug, especially when there are oddities like that.

Thanks,
tedder
