### ISSUE TITLE
Proxy [Request]

### ISSUE THREAD

**Issue by ItsTImetoforget** [OctoPrint/OctoPrint#3623]
Hello,
we need to config a proxy. We can´t find any settings with this option.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
