### ISSUE TITLE
 [1.4.1rc1] High CPU load 

### ISSUE THREAD

**Issue by hamster65** [OctoPrint/OctoPrint#3633]
Hi foosel,

I switched from German to English and to manual port settings. Fine so far, but, even in safe mode, I see this:

 PID USER      PR  NI    VIRT    RES    SHR S  **%CPU**  %MEM     TIME+ COMMAND
 1569 pi        20   0  257288  64428   8640 S **106.9**   7.2   6:45.44 octoprint
  647 pi        20   0   25904   5156   4260 S  **68.3**   0.6  10:12.74 mjpg_streamer
 1141 root      20   0    8180   2984   2368 R   0.7   0.3   0:05.86 top

Not sure if mjpg_streamer was that high before the update, might be. But octoprint certainly was not.

**Comment by jneilliii** [comment]
Have you restarted your pi and tried running OctoPrint in safe mode, just to be sure it's not plugin related or some artifact post upgrade?

**Comment by hamster65** [comment]
I rebooted several times since the upgrade but not after switching to safe mode.

I think is has got something to do with the printer connection: 
When I click disconnect, octoprint immediately reconnects!
I unplugged the usb connection to the printer -> load now 5%.

**Comment by foosel** [comment]
Please fill out the full ticket template.

**Comment by hamster65** [comment]
What were you doing?
Upgraded to 1.4.1rc1

#### What did you expect to happen?
cpu load around 5-10 %

#### What happened instead?
cpu load > 100 %, slow start, slow response from web interface

#### Did the same happen when running OctoPrint in safe mode?
yes

#### Version of OctoPrint
1.4.1rc1

#### Operating System running OctoPrint
4.19.118-v7+
OctoPi version    : 0.15.1
Raspian buster

#### Printer model & used firmware incl. version
corexy Marlin 2.0 bugfix

#### Browser and version of browser, operating system running browser
Firefox 78.01, Linux Debian sid

#### Link to octoprint.log
https://pastebin.com/x8H2gzKv

#### Link to contents of terminal tab or serial.log
https://pastebin.com/La2d3E3i

#### Link to contents of Javascript console in the browser
https://pastebin.com/M0dTE97C

#### Screenshot(s)/video(s) showing the problem:
![grafik](https://user-images.githubusercontent.com/36369379/86620903-7e7bfb00-bfbd-11ea-864c-b4543cbd50f9.png)

I have read the FAQ.

**Comment by Reperiel** [comment]
I have the same problem. For me it's related to the printer connection. Connected -> CPU > 100%, disconnected -> CPU < 10%.

**Comment by foosel** [comment]
Fix ready for 1.4.1rc2

**Comment by foosel** [comment]
1.4.1rc2 has been released.
