### ISSUE TITLE
[Request] Turn off "Internal" filename display

### ISSUE THREAD

**Issue by KenLucke** [OctoPrint/OctoPrint#3636]
Is there a way, or could you add a way (in the general preferences), to turn off the display of the "internal filename" in the list of files?  It takes a lot of room (my filenames are long and show a bunch of information about the file, using the "GCODE Filename Format" plugin in Cura, and I've never understood, nor needed, the ability to display the internal filename.

![CR-10v2 (Blue)  OctoPrint](https://user-images.githubusercontent.com/57936294/86654471-d3f2e080-bf9a-11ea-8701-1d84ea676d45.jpg)

**Comment by cp2004** [comment]
PR #3783 to implement this 🙂
