### ISSUE TITLE
[1.4.1rc2] JS minification can cause issues with third party plugins, nuking all of packed_plugins.js

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint#3640]
### Problem

New default of minifying JS assets from third party plugins can cause issues if that triggers Syntax Errors inside one or more third party plugins. As SyntaxErrors cannot be caught, any such issue will effectively nuke the whole `packed_plugins.js` bundle.

See also Sebclem/OctoPrint-SimpleEmergencyStop#14 and FormerLurker/Octolapse#567

### Solution

Disable minification again by default, at least for anything involving third party plugins, as it was prior to 1.4.1.

### Note

The old behaviour can be enforced again and thus the above problem avoided by setting 

``` yaml
devel:
  webassets:
    minify: false
```

in `config.yaml`.

**Comment by FormerLurker** [comment]
@foosel, could you stuff the JS from each plugin into a separate file and minify each separately?

**Comment by foosel** [comment]
I could, but that would defeat the whole point of bundling the assets together to avoid a flood of requests needed to load the page. And we really want to avoid that as it increases page load times (and server load) significantly.

**Comment by foosel** [comment]
1.4.1rc3 has been released
