### ISSUE TITLE
Remote access failing using nginx Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by Commiccannon** [OctoPrint/OctoPrint#3644]
#### What were you doing?

Setup nginx with a basic password and whenever i try to load octoprint page i a socket error
Chromes browser log is constantly saying "Error during WebSocket handshake: Unexpected response code: 400"

####
[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/4930335/octoprint.log)

#### 

#### 
[octoprintcommic.ddns.net-1594889022488.log](https://github.com/OctoPrint/OctoPrint/files/4930337/octoprintcommic.ddns.net-1594889022488.log)

#### 
![OctoPrint - Google Chrome 16_07_2020 6_44_11 PM](https://user-images.githubusercontent.com/63322372/87650021-62821180-c794-11ea-9760-406f5f5300b4.png)

Here is my NGINX config file 
[NGINX.txt](https://github.com/OctoPrint/OctoPrint/files/4930367/NGINX.txt)

I have read the FAQ.

**Comment by foosel** [comment]
Your NGINX configuration doesn't match what's suggested at https://community.octoprint.org/t/reverse-proxy-configuration-examples/1107. Most importantly it's missing `proxy_http_version 1.1;`. Try adding that. If that doesn't fix it, please open a thread on the forums - this is more an issue with your environment and your reverse proxy configuration than a bug in OctoPrint and hence the bug tracker is not the right place.
