### ISSUE TITLE
Build ARM64 Octopi

### ISSUE THREAD

**Issue by ss8688** [OctoPrint/OctoPrint#3663]
Build ARM64 Octopi .Now there is a ARM64 Raspberry pi os,so it is possiable to build  ARM64 Octopi

**Comment by foosel** [comment]
This is the bug tracker of the 3d print server OctoPrint, not the OS image [OctoPi](https://github.com/guysoft/OctoPi) that ships with it. See also https://community.octoprint.org/t/what-is-the-difference-between-octoprint-and-octopi-are-they-the-same-thing/185
