### ISSUE TITLE
[Request] Turn SD card monitoring off if not printing from SD card

### ISSUE THREAD

**Issue by mrseeker** [OctoPrint/OctoPrint#3665]
**Is your feature request related to a problem? Please describe.**
I am getting multiple messages from my printer saying "Not SD printing" during a print. This is correct since the printer is not printing from the SD card, but also annoying since the printer keeps spamming this every 3 seconds.

**Describe the solution you'd like**
When printing from octoprint (and not from SD), if the "Not SD printing" message pops up, disable status reporting by replying with "M27 S0".

**Describe alternatives you've considered**
I thought about adding M27 S0 to the startup script, however when I do print from SD card this option should be enabled and not turned off.

**Additional context**
See https://marlinfw.org/docs/gcode/M027.html

**Comment by foosel** [comment]
That would break detecting SD prints initiated from the printer's controller, which a lot of people out there truly on. You can filter the messages from the log if they annoy you, but they serve a crucial purpose in host-printer-synchronization.
