### ISSUE TITLE
[Request] Make top bar fixed, not scrolling

### ISSUE THREAD

**Issue by Jeff5263** [OctoPrint/OctoPrint#3669]
**Is your feature request related to a problem? Please describe.**

I WOULD LIKE TO SEE THE TOP BAR (WITH MY PROFILE, SETTINGS, SHUTDOWN, ETC.) FIXED SO IT DOESN'T SCROLL WITH THE REST OF THE PAGE. -THANKS

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
Install the [Floating Navbar](https://plugins.octoprint.org/plugins/floatingnavbar/) plugin.

**Comment by foosel** [comment]
Like @jneilliii said, there's a plugin for that. Also, please don't use all caps, it's reads as if you were screaming and hence gives a quite rude first impression ;)
