### ISSUE TITLE
WIFI connection

### ISSUE THREAD

**Issue by Puffymania** [OctoPrint/OctoPrint#3681]
When ever I install Octoprint everything works perfect for about 3 - 4 weeks then it starts to sometimes loose the WiFi connection to then reconnect after a period of time, until finally one day it just stops connecting to the WiFi all together. The only ways I can get it to work again is by cable or reflash Octoprint to sd.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
