### ISSUE TITLE
Help "Communication timeout"

### ISSUE THREAD

**Issue by VASAPOL** [OctoPrint/OctoPrint#3684]
Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.

**Comment by VASAPOL** [comment]
Logs

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/5045116/octoprint.log)

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
