### ISSUE TITLE
[feature request] Filament database

### ISSUE THREAD

**Issue by HamOP** [OctoPrint/OctoPrint#371]
It would be great to be able to set up a kind of filament database where you can store your different filament types with the specific settings like speed, flow rate and temperature offsets - so you will not have to remember them or write them down on the spools. You would just choose e.g. "PLA, Vendor XYZ, Color blue" and OctoPrint would automatically set your temperature offset and so on to the values you specified before when adding the filament entry. This could also be combined with the filament odometer requested before.

**Comment by rothnic** [comment]
@ariporad I see your last commit on Aug 24th. What was the state of this plugin where you left it?

**Comment by ariporad** [comment]
@rothnic, it's a work in progress. I haven't had time to work on it recently.

**Comment by probonopd** [comment]
What happened to the Uniform Filament Identification system (UFID)?
