### ISSUE TITLE
[Request] Collapse Printer Notification preference

### ISSUE THREAD

**Issue by KenLucke** [OctoPrint/OctoPrint#3716]
Would it be possible to add a preference to the Printer Notification settings to initially show it or collapse it?  

I like the functionality of having the notifications there, but don't always need to see the list every time I reload OctoPrint, and it gets a little old having to manually collapse the list every time

**Comment by jneilliii** [comment]
Stateful Sidebar plugin.

**Comment by KenLucke** [comment]
Thanks, had not seen that one.
