### ISSUE TITLE
[Request] Download multiple logs at once.

### ISSUE THREAD

**Issue by KenLucke** [OctoPrint/OctoPrint#3746]
**Is your feature request related to a problem? Please describe.**
Annoyance rather than problem.  When downloading logfiles and backups, you have to do so one at a time.

**Describe the solution you'd like**
There already exists a mechanism for selecting multiple files at one time (for deletion).  Please add the ability to download the selected files all at once (preferably with an option to zipfile them prior to download, but just a bulk download would make me ecstatic).  An optional "Save To" folder on the local machine (instead of just automatically going into the Downloads folder) would be tremendous, too.

**Describe alternatives you've considered**
Continuing to do it the old, PITA way :)

**Additional context**

**Comment by foosel** [comment]
1.6.0 has just been released.
