### ISSUE TITLE
http basic auth broken

### ISSUE THREAD

**Issue by bzed** [OctoPrint/OctoPrint#3747]
Hi,

since one of the 1.4 releases (as far as I can tell) - wild guess: since the update of flask-login, http authentication is broken, even with

```
accessControl:
    checkBasicAuthenticationPassword: false
    trustBasicAuthentication: true
```
in the config. Basic auth headers just seem to be ignored and the normal login is being displayed.

Still did not have the time to debug it - sorry.

Bernd
P.S. using uptodate maintenance branch.

**Comment by foosel** [comment]
Fixed. And it was a 1.5.0 only bug, thus I'm actually closing this now since it hasn't yet been shipped in form of a release.
