### ISSUE TITLE
[Request] Hi res images for timlapse

### ISSUE THREAD

**Issue by carcamerarig** [OctoPrint/OctoPrint#3757]
**Is your feature request related to a problem? Please describe.**
I cannot configure octopi.txt to take 1 high res still image per trigger with the command -usestills -fps1 using the raspi cam, instead it is using raspivid at "whatever resolution and frame rate is set) to grab a single frame from the video stream. 

**Describe the solution you'd like**
I would like to be able to have single images at full sensor resolution at a low frame rate like 1fps and those images stored in the snapshot folder. 
**Describe alternatives you've considered**
Using the external camera configuration to do the above and try to configure it to use the gpu attached raspi cam.

**Additional context**
- Created an octopi issue/request, claimed octoprint issue. 
- Created an octolapse issue/request claimed mjpg-streamer issue. 
- Created an mjp-streamer issue/request claimed octoprint issue

I would really appreciate some help.

Pi4b8Gb
Raspi cam v2.1
Octopi .17
Octoprint 1.43
Octodash
Octolapse.

**Comment by foosel** [comment]
OctoPrint itself doesn't have any way to influence the webcam resolution. That's all done inside the third party webcam server bundled with OctoPi.

If you want to get into a discussion on how to maybe achieve what you want to with that, best get in touch on the community forums. The OctoPrint bug tracker which you are at here is the wrong location.
