### ISSUE TITLE
[Request] trigger start from printer

### ISSUE THREAD

**Issue by mrseeker** [OctoPrint/OctoPrint#3775]
**Is your feature request related to a problem? Please describe.**
Marlin 2.0.7 added a feature to start prints from the LCD screen. This is particularly handy when there are multiple prints that need to be printed out, and manual intervention between prints is necessary (clearing the print from the bed). Going to the website and restarting is usually not needed. This helps the "automation" of the print. A print "queue" could handle the octoprint part loading, while the operator just has to start a new print.

**Describe the solution you'd like**
When a file is loaded and the printer sends the following command:
//action:start
Then start the printjob.

**Describe alternatives you've considered**
Using a plugin to check for the command, and starting it that way.

**Comment by foosel** [comment]
Already on the `maintenance` branch and will be part of 1.5.0. See https://docs.octoprint.org/en/maintenance/features/action_commands.html
