### ISSUE TITLE
[Request] Possibility to suppress terminal messages

### ISSUE THREAD

**Issue by chimcen** [OctoPrint/OctoPrint#3779]
**Is your feature request related to a problem? Please describe.**
Actually i can suppress printers terminal messages like temperature, sd and wait messages in octoprint. But i‘ve to set them everytime again when my printer restarts.

**Describe the solution you'd like**
Is it possible to save them and octoprint tells the printer on every start/reconnect the needed commands for this again?

Thank you :)

**Comment by cp2004** [comment]
There's a plugin that will save these across a reload for you:
 https://plugins.octoprint.org/plugins/active_filters_extende/
