### ISSUE TITLE
[BUG]: 1.5.0 internal server error with files.get

### ISSUE THREAD

**Issue by jneilliii** [OctoPrint/OctoPrint#3805]
#### What were you doing?

Testing 1.5.0rc1...when selecting files in the file list an api error is occurring, causing issues with PrusaSlicerThumbnails.

1. Install PrusaSlicer Thumbnails
2. After restart/reload, upload a file that includes a thumbnail (attached for convenience)
3. In plugin's settings enable `Show thumbnail in state panel.`
4. Select a file, which runs js `OctoPrint.files.get('local',data)` as part of a knockout subscribe binding `self.printerStateViewModel.filepath.subscribe(function(data)`
5. error generated in logs (attached) and metadata is not loaded to get thumbnail property.

[LampCylinder.gcode.txt](https://github.com/OctoPrint/OctoPrint/files/5520712/LampCylinder.gcode.txt)

#### What did you expect to happen?

File data to be retrieved and thumbnail to show in state panel.

#### What happened instead?

Error and no thumbnail.

#### Did the same happen when running OctoPrint in safe mode?

Not entirely sure, but can test shortly. 

#### Version of OctoPrint

1.5.0rc1

#### Operating System running OctoPrint

any, tested in both windows dev environment and octopi 0.18.

#### Printer model & used firmware incl. version

virtual printer

#### Browser and version of browser, operating system running browser

Google Chrome Version 86.0.4240.193 (Official Build) (64-bit) on windows 10.

#### Link to octoprint.log

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/5520695/octoprint.log)

#### Link to contents of terminal tab or serial.log

N/A

#### Link to contents of Javascript console in the browser

[developer_console.log](https://github.com/OctoPrint/OctoPrint/files/5520702/developer_console.log)

#### Screenshot(s)/video(s) showing the problem:

![image](https://user-images.githubusercontent.com/5249455/98744603-00bb6800-2380-11eb-93e0-7b223cda3d32.png)

thumbnail should be just below the first `<hr>`.

I have read the FAQ.

**Comment by jneilliii** [comment]
I can confirm, simply running `OctoPrint.files.get('local','LampCylinder.gcode')` with all plugins disabled causes the same error.

**Comment by foosel** [comment]
I fear that got introduced by the more aggressive caching on the file api down into the file manager that I now do. Have to investigate. A `dict` check doesn't appear to be the right way, as `children` now seem to be a list in general.

**Comment by foosel** [comment]
Fixed by the above commit, ready for 1.5.0rc2

**Comment by foosel** [comment]
1.5.0rc2 is out
