### ISSUE TITLE
[Request] Please add new action command.

### ISSUE THREAD

**Issue by AndKe** [OctoPrint/OctoPrint#3834]
**Is your feature request related to a problem? Please describe.**
the printer is in >100m away from my workstation..
I go to the printer, remove previous print, and want to restart another batch.
or:
I go to printer, remove some mess, refill filament, and want to start job over, stay and see it start well.

**Describe the solution you'd like**
I would like to be able to restart last print job from the printer

**Describe alternatives you've considered**
https://docs.octoprint.org/en/master/features/action_commands.html
Add action command "printlast" that starts the last job, (be it a successful, or failed one)

**Additional context**
The command should simply repeat the "print" action on whatever job was the last one the user clicked "print" on.

**Comment by foosel** [comment]
1.5.0 will already come with support for the `start` action that starts the currently selected print job (which will be the same one again if one already finished)

https://docs.octoprint.org/en/maintenance/features/action_commands.html

So - already implemented.

**Comment by AndKe** [comment]
fantastic.. just fantastic.  :)
