### ISSUE TITLE
upgrade to Octoprint 1.5

### ISSUE THREAD

**Issue by Drummerboy2** [OctoPrint/OctoPrint#3841]
#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by Drummerboy2** [comment]
I did not download any logs or messages yet. First I wanted to find out if there is an issue. I upgraded to v 1.5 and immediately my Prusa thumbnail does not show any thumbnails and if I click on the icon nothing comes up. I changed nothing else.
Thanks Brian

**Comment by jneilliii** [comment]
Related to the upgrade, but is an issue with the plugin, not octoprint. There is already one issue opened on it's repo for the state panel not getting the thumbnails in 1.5.0.

**Comment by Drummerboy2** [comment]
Thank you

Sent from my iPad

On Nov 30, 2020, at 1:34 PM, jneilliii <notifications@github.com<mailto:notifications@github.com>> wrote:


Related to the upgrade, but is an issue with the plugin, not octoprint. There is already one issue opened on it's repo for the state panel not getting the thumbnails in 1.5.0.
