### ISSUE TITLE
When UI Customizer enabled, screen is blank.

### ISSUE THREAD

**Issue by holocronology** [OctoPrint/OctoPrint#3850]
#### What were you doing?
After login, screen is blank, info bar at top still present.

When UI Customizer plugin is active, screen is blank. All other 3rd party plugins deactivated.

Safe Mode

#### Screenshot(s)/video(s) showing the problem:
https://i.imgur.com/cE8YnZT.png
https://i.imgur.com/lOkSsNo.png

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
connectivity.connection_check: 8.8.8.8:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1400
env.hardware.ram: 915709952
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 3 Model B Plus Rev 1.3
env.plugins.pi_support.octopi_version: 0.17.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 20.2.4
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.0

**Comment by jneilliii** [comment]
This is an issue with that plugin and should be reported on that plugin's repository not here. I have received reports of the same thing when it is installed in conjunction with my Bed Level Visualizer plugin and the plugin author is investigating on his end what might be causing that.

**Comment by cp2004** [comment]
As @jneilliii said, this is a 3rd party issue, there is nothing we can do about that here. And in the future, please fill out the template when you create a bug report.

**Comment by holocronology** [comment]
Okay, thanks. I assumed since it was installed as part of the update that it was part of the base.

**Comment by cp2004** [comment]
> I assumed since it was installed as part of the update

Wasn't related, it was probably coincidence since it was released at a similar time on the repository, you got the 'new plugin available' and 'octoprint update' notices at the same time.

**Comment by holocronology** [comment]
Right, now that you mention it. Odd thing is that even after deleting all the other plug-ins, it still misbehaves in the same manner.
