### ISSUE TITLE
After version 1.5.0 update the web interface does not display on ipad 2

### ISSUE THREAD

**Issue by huseman21** [OctoPrint/OctoPrint#3851]
#### What were you doing?

1. Go to '...'IP address of octopi

#### What did you expect to happen?
the web page load.
#### What happened instead?
just a blank white page.  It does make the connection.  it does  work on my pc.
#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by cp2004** [comment]
The issue template is supposed to be filled in **fully**. If this information is not provided within the next 2 weeks then this issue will have to be closed. Please fill it in completely.

**Comment by cp2004** [comment]
Since the rest of the information requested in the report has not been provided, I'm going to close this.

@huseman21 if this is still an issue, feel free to provide the requested information and we will decide if it needs re-opening.
