### ISSUE TITLE
Deleting existing filament temperature settings does not work.

### ISSUE THREAD

**Issue by MartinMajewski** [OctoPrint/OctoPrint#3855]
Version: 1.5.1

Issue description:

In "Settings" → "Temperatures" → "Preset" Section.
When deleting an existing temperature preset and saving the dialog, the changes are not applied.

Adding a new material, or changing existing materials works. As soon as new material is added, it cannot be removed anymore.

The "bug" was possibly introduced after 1.4.2, as it worked there. I've upgraded directly to 1.5.1 today and discovered this behavior.

I will provide logs shortly!

I have read the FAQ ;-)

**Comment by foosel** [comment]
@OctoPrint/octoprint-triage I've told @MartinMajewski to open an abridged bug report, he's reported this in length via chat.

**Comment by foosel** [comment]
![image](https://user-images.githubusercontent.com/83657/101163703-447a5800-3634-11eb-81be-3894e0069573.png)

![image](https://user-images.githubusercontent.com/83657/101163712-47754880-3634-11eb-9a38-4a235d1e3fd4.png)

![image](https://user-images.githubusercontent.com/83657/101163720-49d7a280-3634-11eb-9738-8de9fc2314c6.png)

**Comment by foosel** [comment]
Can reproduce. Weirdly enough I can only reproduce if I try to delete every custom added temperature.

**Comment by foosel** [comment]
Fixed by the above commit, and this ticket actually turned out to be a general issue with how array settings are being processed in the frontend, see #3867 for details. I'll look into providing a quick workaround plugin for this.

**Comment by foosel** [comment]
This plugin should work as a fix for now: https://github.com/OctoPrint/OctoPrint-FixSettingsDeepMerge

Install via plugin manager, get more, from this URL: https://github.com/OctoPrint/OctoPrint-FixSettingsDeepMerge/archive/master.zip

**Comment by foosel** [comment]
About to release 1.5.2 after all (third party dependency released a breaking update), so this fix gets a hotfix release after all.
