### ISSUE TITLE
[Request] Remember (and restore) last opened folder in Files list

### ISSUE THREAD

**Issue by akewea** [OctoPrint/OctoPrint#3868]
Currently, the "Files" list is reset (at the root of files) each time octoprint is loaded.
I'd like it to be restored on the last opened folder.

**Comment by foosel** [comment]
Implemented by PR #4291, merged and to be included in 1.8.0. Note that the behaviour will be hidden behind a feature flag that defaults to off.

**Comment by cp2004** [comment]
1.8.0 has been released 🎉
