### ISSUE TITLE
Anonymous usage tracking wizard shows before connectivity check

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#3895]
#### What were you doing?

1. Read https://github.com/guysoft/OctoPi/issues/692#issuecomment-748156276
2. Determine that these screens need to be switched

#### What did you expect to happen?
No problems were reported (we live in hope)

#### What happened instead?
A problem was reported

#### Did the same happen when running OctoPrint in safe mode?
Initial setup wizard, have to assume that it does - since this is before any plugins are installed.

#### Version of OctoPrint
1.4.2? (Need to check this is still applicable in future versions, I think it is but if not then )

#### Operating System running OctoPrint
OctoPi 0.18

#### Printer model & used firmware incl. version
VIRTUAL

#### Browser and version of browser, operating system running browser
NA

#### Link to octoprint.log
Log excerpt was provided here: https://github.com/guysoft/OctoPi/issues/692#issuecomment-746371533

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

### Further notes
I'll try and reproduce this, and then figure out how to change the order - need to check if wizard plugins are sortable, and if so prioritize the corewizard one.

**Comment by foosel** [comment]
Merged (woot!) and ready for 1.6.0 (woot!)
