### ISSUE TITLE
Octoprint briefly flashes "Server is currently offline. Reconnect..." when logging in

### ISSUE THREAD

**Issue by timur-tabi** [OctoPrint/OctoPrint#3938]
#### What were you doing?

Whenever I log in, the Octoprint login screen briefly (fraction of a second) shows the error message, "Server is currently offline. Reconnect..." before successfully logging in.  I suppose technically this is a cosmetic issue, but it is disconcerting and should be fixed.

Problem also occurs in safe mode.

OctoPrint 1.5.2
Python 2.7.13

OctoPi 0.15.1

Prusa MK3s with latest firmware

Firefox 84.0.2 (64-bit) running on Kubuntu 20.04.

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/5798347/octoprint.log)

[console-export-2021-1-11_15-12-43.txt](https://github.com/OctoPrint/OctoPrint/files/5798370/console-export-2021-1-11_15-12-43.txt)

![vlcsnap-2021-01-11-13h06m30s562](https://user-images.githubusercontent.com/1065860/104226819-01b75700-540e-11eb-8e7d-59a78f4ff944.png)

I have read the FAQ.

**Comment by jasonbcox** [comment]
I've encountered this as well. It's jarring. A quick look at the code and it looks like the socket is kicking off the onDisconnect callback erroneously (but probably harmlessly) in some cases.

**Comment by foosel** [comment]
Fix should be ready for 1.6.0
