### ISSUE TITLE
Placeholder for the current user + optional email field in user config

### ISSUE THREAD

**Issue by hampussandberg** [OctoPrint/OctoPrint#394]
I've been using various Events to send email with error messages, success messages, pictures etc. and I find it really useful!

But at the moment the email address which it sends to is hardcoded in config.yaml like this:
`command: echo "Email message... {__data}" | mail -s "Subject..." email@example.com`
I would rather have something like this:
`command: echo "Email message... {__data}" | mail -s "Subject..." {__email}`
Where {__email} is the email address of the logged in user.

So far I've managed to make a new parameter {__email} in events.py which I can use in the config.yaml but I can't find a way to get the data for the current user. Is there an easy way to do this?

The user class has to be expanded of course with a new data field for email.

**Comment by cp2004** [comment]
There's the OctoText plugin that allows for full configuration of sending emails for printer events available now.
