### ISSUE TITLE
[Request] Improve logging debug settings to be less confusing

### ISSUE THREAD

**Issue by eyal0** [OctoPrint/OctoPrint#3947]
**Is your feature request related to a problem? Please describe.**
The users of my plugin are often confused by the logging settings screen.

It sometimes appears as if debug logging has been set when it hasn't.  Here are the steps that they try:

1. Go to logging settings and set the logging level (they forget to press the plus sign):

![image](https://user-images.githubusercontent.com/109809/104482489-39e0a600-5584-11eb-8902-0a352c5843cf.png)

2. Click Save.
3. Do something that tries logging.  Notice that no logging was done.
4. Go back to the settings and see that it's still there, so they assume that the logging is broken.  But no, it's actually the settings that are confusing the user.

**Describe the solution you'd like**

I suggest that the comboboxes for "Name" and "Level" always be blank.  And as soon as any of them are modified, a new row is created below immediately.  There is no danger that the settings will take place before clicking "Save" because the settings are only applied on "Save".  The user can still delete the row.

**Describe alternatives you've considered**

I thought about just making sure that the comboboxes for the new row are always blank when opening the settings dialog.  This would at least solve the problem where a user closes the settings dialog, opens it again, and still sees their settings.  However, it just takes more work form the user and they'll still be confused.

**Additional context**

Seen in https://github.com/OctoPrint/OctoPrint-Slic3r/issues/60

**Comment by eyal0** [comment]
I'll work on this.

**Comment by foosel** [comment]
Thanks for the PR! It's merged and will be part of 1.6.0!
