### ISSUE TITLE
Logging level for "octoprint" appears on Logging levels even though it isn't been logged

### ISSUE THREAD

**Issue by eyal0** [OctoPrint/OctoPrint#3950]
#### What were you doing?

1. Click on settings.
2. Click on "Logging"
3. See this:

![image](https://user-images.githubusercontent.com/109809/104495293-d4e17c00-5594-11eb-9d79-097c2873b11d.png)

It appears as if I have debug logging set for both `octoprint.events.fire` and `octoprint`.  However, only the first one is set.  The second one hasn't yet been added.

#### What did you expect to happen?

I expected only `octoprint.events.fire` to be listed because that's the only one that I have set.

#### What happened instead?

I saw `octoprint` listed for `DEBUG` even though I didn't enable that logging.

#### Version of OctoPrint

OctoPrint 1.6.0.dev178+g498463f5c Python 3.7.3

#### Operating System running OctoPrint

Linux

#### Browser and version of browser, operating system running browser

Chrome

I have read the FAQ.

**Comment by eyal0** [comment]
This is related to #3949 
This is also related to #3948

**Comment by eyal0** [comment]
I will fix this.

**Comment by foosel** [comment]
Thanks for the PR! It's merged and will be part of 1.6.0!
