### ISSUE TITLE
Logging levels are saved even when there are no changes

### ISSUE THREAD

**Issue by eyal0** [OctoPrint/OctoPrint#3952]
#### What were you doing?

1. Open settings
2. Click on "Logging"
3. Add or modify any logging level (if you add, don't forget to click the blue plus sign!)
4. Click "Save" to save the changes.
5. Observe that `ConfiguredLoggers has changed. Saving!` is in the console log.
6. Open the settings dialog again.
7. Without changing anything, click "Save" again.

#### What did you expect to happen?

I expected not to see `ConfiguredLoggers has changed. Saving!` in the console log.

#### What happened instead?

I saw `ConfiguredLoggers has changed. Saving!` in the console log.

#### Version of OctoPrint

OctoPrint 1.6.0.dev178+g498463f5c Python 3.7.3

#### Operating System running OctoPrint

Linux

#### Browser and version of browser, operating system running browser

Chrome

I have read the FAQ.

**Comment by eyal0** [comment]
I will fix this.

**Comment by foosel** [comment]
Thanks for the PR! It's merged and will be part of 1.6.0!
