### ISSUE TITLE
It's possible to add the same logging level twice

### ISSUE THREAD

**Issue by eyal0** [OctoPrint/OctoPrint#3955]
#### What were you doing?

1. Configure at least one logging level in Setting -> Logging.  Don't forget to press the blue plus sign.
2. Click on "Save"
3. Reload Octoprint by pressing F5 in the browser.
4. Open settings and go to the Logging settings
5. Notice that it is possible to add the same logging level that already exists in the list.

#### What did you expect to happen?

It should not be possible to re-add a logging level

#### What happened instead?

It was possible to re-add a logging level

#### Version of OctoPrint

OctoPrint 1.6.0.dev178+g498463f5c.dirty Python 3.7.3

I have read the FAQ.

**Comment by eyal0** [comment]
I will fix this.

**Comment by cp2004** [comment]
Is this a duplicate, or is #3954 a duplicate? Either way they are about the same issue, so one should be closed as far as I see.

**Comment by eyal0** [comment]
It's a duplicate.  Github wigged out on my when I tried to save it the first time.  Sorry.

This is a duplicate of #3954
