### ISSUE TITLE
[Request] Ability to suppress the "blocked command" popup

### ISSUE THREAD

**Issue by fluffy-critter** [OctoPrint/OctoPrint#3969]
**Is your feature request related to a problem? Please describe.**

One of the slicers I use (Canvas3D) sends M0 as its initial command, which is blocked. There doesn't seem to be any way to get the slicer to not send this command, but every time I load a gcode file with that I get another little popup message in the corner of my Octoprint UI, which gets in the way of things and is kind of annoying to clear due to the small click target.

**Describe the solution you'd like**

I'd like to be able to have those "suppressed command" popups have configuration for how long they stick around, with the ability to turn them off entirely if so desired.

**Comment by cp2004** [comment]
This is already an option! So you are in luck.

Here's a screenshot, find it under Settings > Serial connection > Behaviour tab, scroll down a little to find it.

![image](https://user-images.githubusercontent.com/31997505/104857297-4f9cf500-590f-11eb-92b9-cba076f16fbc.png)

**Comment by fluffy-critter** [comment]
Ah, thanks! I had looked around for it all over but I never thought to look in the "serial connection" tab.
