### ISSUE TITLE
[feature request] Control multiple printers

### ISSUE THREAD

**Issue by r4v5** [OctoPrint/OctoPrint#397]
For those of us in group settings, it would be incredibly convenient to be able to use Octoprint as a print server for multiple 3D printers at a time on one embedded board, but I currently see no way to do this. Would it be a lot of hassle to allow the configuration, selection, and use of multiple printers of varying settings within one running Octoprint session?

**Comment by jhayes321** [comment]
Also would like this. Already have several printers and several octoprint. Found a work around but sure we be nice to have some part of this native to the app.

**Comment by brotherchris** [comment]
Check this out. https://youtu.be/7Saa1HpLRoM

**Comment by jhayes321** [comment]
Thank you for the info and this is great.  Got to think a lot of people are into multiple printers and it would sure be nice to have only one instance running.

**Comment by brotherchris** [comment]
This has proved to be very handy for me.

**Comment by jhayes321** [comment]
I just finished the config and it works great - do you need to update each instance when new versions come out?

**Comment by brotherchris** [comment]
Yes, in this config you have to upgrade each one through the GUI
separately.

**Comment by VanKurt** [comment]
Is this feature coming to Octoprint anytime soon? The current situation is rather dissatisfyctory when you have more than one printer...

**Comment by foosel** [comment]
No.

On the multicore Pis you can run multiple instances, but this is a non trivial feature to implement due to the current architecture in combination with the used language and its limitations.

**Comment by foosel** [comment]
I'm not sure how much easier I could make it other than `--basedir /some/other/basedir` as command line argument to the executable. Singular install, multiple instances with different configuration directories. Should work (and update) just fine.

Other than that - this is an open source project. Everyone can contribute their time and skills to make it better.

**Comment by jhayes321** [comment]
I guess if that doesn't work, then that's not great. I made a financial contribution instead of sweat equity.




On Thursday, September 20, 2018, 6:29 AM, Gina Häußge <notifications@github.com> wrote:


I'm not sure how much easier I could make it other than --basedir /some/other/basedir as command line argument to the executable. Singular install, multiple instances with different configuration directories. Should work (and update) just fine.

Other than that - this is an open source project. Everyone can contribute their time and skills to make it better.

**Comment by NotExpectYet** [comment]
> For those of us in group settings, it would be incredibly convenient to be able to use Octoprint as a print server for multiple 3D printers at a time on one embedded board, but I currently see no way to do this. Would it be a lot of hassle to allow the configuration, selection, and use of multiple printers of varying settings within one running Octoprint session?

I've been working on this, still very wet around the ears but it works!

https://git.notexpectedyet.com/NotExpectedYet/OctoFarm

**Comment by z3dev** [comment]
Not to spoil the fun, but why not just open more tabs, and control each printer through a specific URL or port?

**Comment by LazeMSS** [comment]
Is possible using:
https://octofarm.net/
