### ISSUE TITLE
Temperature can not be set

### ISSUE THREAD

**Issue by ma-mod** [OctoPrint/OctoPrint#3979]
Hello,
Unfortunately I have problems with octoprint and my Ender 5 Plus Printer.

I am not able to set a temperature via GUI, also it is not working if I start a print. It will then timeout with an error message.
If I dont use OctoPI (disconnect the PI from the Printer), and set the temperature manually on the printer, it is working fine.
Sporadically I can get the Printer to heat when set via OctoPrint, but then it will not stop to heat. 
As example I've set it to 65°C Bed Temperature. It starts to heat the bed, but never will stop. After 5 minutes it had 95°C bed temperature and I've had to reset the printer to stop it.

Does anyone have a clue why this is happening or how I could fix it?
Let me know if you need further information. Sorry for my english.

Ender 5 Plus has an silent board with newest firmware from their webpage: V1.70.2
OctoPrint Version: 1.5.3
Python 2.7.16
OctoPi 0.17.0
Running on a Raspberry Pi 4 (4GB) 
OctoPi was installed yesterday and I've just added Bed Level Visualizer. Except of this, it is a clean install.

Here a small part of the log file where it was going to 95°C:

`Send: M140 S0  
Recv: ok  
Recv:  == T:24.02 /0.00 == B:49.06 /0.00 @:0 B@:127  
Recv:  == T:23.95 /0.00 == B:49.42 /0.00 @:0 B@:127  
Recv:  == T:24.02 /0.00 == B:49.75 /0.00 @:0 B@:127  
Recv:  == T:24.06 /0.00 == B:50.13 /0.00 @:0 B@:127  
Recv:  == T:24.06 /0.00 == B:50.45 /0.00 @:0 B@:127  
Recv:  == T:24.06 /0.00 == B:50.75 /0.00 @:0 B@:127  
Recv:  == T:24.02 /0.00 == B:51.11 /0.00 @:0 B@:127  
Recv:  == T:24.22 /0.00 == B:51.35 /0.00 @:0 B@:127  
Recv:  == T:24.22 /0.00 == B:51.72 /0.00 @:0 B@:127  
Recv:  == T:24.02 /0.00 == B:51.99 /0.00 @:0 B@:127  
Recv:  == T:24.14 /0.00 == B:52.26 /0.00 @:0 B@:127  
Recv:  == T:24.26 /0.00 == B:52.61 /0.00 @:0 B@:127  
Recv:  == T:24.22 /0.00 == B:52.93 /0.00 @:0 B@:127  
Recv:  == T:24.34 /0.00 == B:53.20 /0.00 @:0 B@:127  
Recv:  == T:24.34 /0.00 == B:53.51 /0.00 @:0 B@:127  
Recv:  == T:24.34 /0.00 == B:53.85 /0.00 @:0 B@:127  
Recv:  == T:24.37 /0.00 == B:54.11 /0.00 @:0 B@:127  
Recv:  == T:24.34 /0.00 == B:54.40 /0.00 @:0 B@:127  
Recv:  == T:24.37 /0.00 == B:54.76 /0.00 @:0 B@:127  
Recv:  == T:24.41 /0.00 == B:55.01 /0.00 @:0 B@:127  
Recv:  == T:24.41 /0.00 == B:55.26 /0.00 @:0 B@:127  
Recv:  == T:24.37 /0.00 == B:55.60 /0.00 @:0 B@:127  
Recv:  == T:24.45 /0.00 == B:55.85 /0.00 @:0 B@:127  
Recv:  == T:24.41 /0.00 == B:56.13 /0.00 @:0 B@:127  
Recv:  == T:24.53 /0.00 == B:56.43 /0.00 @:0 B@:127  
Recv:  == T:24.45 /0.00 == B:56.67 /0.00 @:0 B@:127  
Recv:  == T:24.53 /0.00 == B:56.93 /0.00 @:0 B@:127  
Recv:  == T:24.53 /0.00 == B:57.29 /0.00 @:0 B@:127  
Recv:  == T:24.53 /0.00 == B:57.49 /0.00 @:0 B@:127  
Recv:  == T:24.69 /0.00 == B:57.79 /0.00 @:0 B@:127  
Recv:  == T:24.57 /0.00 == B:58.07 /0.00 @:0 B@:127  
Recv:  == T:24.57 /0.00 == B:58.32 /0.00 @:0 B@:127  
Recv:  == T:24.65 /0.00 == B:58.57 /0.00 @:0 B@:127  
Recv:  == T:24.61 /0.00 == B:58.85 /0.00 @:0 B@:127  
Recv:  == T:24.65 /0.00 == B:59.13 /0.00 @:0 B@:127  
Recv:  == T:24.73 /0.00 == B:59.39 /0.00 @:0 B@:127  
Recv:  == T:24.73 /0.00 == B:59.60 /0.00 @:0 B@:127  
Recv:  == T:24.80 /0.00 == B:59.92 /0.00 @:0 B@:127  
Recv:  == T:24.65 /0.00 == B:60.19 /0.00 @:0 B@:127  
Recv:  == T:24.77 /0.00 == B:60.41 /0.00 @:0 B@:127  
Recv:  == T:24.80 /0.00 == B:60.69 /0.00 @:0 B@:127`

**Comment by cp2004** [comment]
Broken firmware and/or printer control board most likely.  There are broken temperature reports (with the double equals) - which is identified in the [Printers known to ship with broken or unsafe firmware, or broken electronics](https://community.octoprint.org/t/printers-known-to-ship-with-broken-or-unsafe-firmware-or-broken-electronics/25911) post here.

The only way to fix it would be flash your own version of Marlin or replace the control board of the printer. There's nothing here broken with OctoPrint, if you need further help please seek support on the [community forums](https://community.octoprint.org) or [discord server](https://discord.octoprint.org) - we try and keep GitHub reserved for issues with OctoPrint itself and general help can be found in those places.

Thanks
