### ISSUE TITLE
[Request] Offer to upgrade OctoPrint if backup being imported is from a newer version of OctoPrint

### ISSUE THREAD

**Issue by reedy** [OctoPrint/OctoPrint#3990]
**Is your feature request related to a problem? Please describe.**

Upgrading OctoPi, and trying to import a backup from a newer version of OctoPrint.

Backup made on 1.8.3. Installed OctoPi 0.18.0 (to get python3 related benefits). Tried to restore backup from 1.8.3, told it's too new, as OctoPi 0.18.0 came with 1.8.2.

Had to use the manual `~/oprint/bin/pip install -U octoprint` and then import the backup again

**Describe the solution you'd like**
If a backup is "too new", offer to upgrade OctoPrint, and then try the backup import again

**Describe alternatives you've considered**
None

**Additional context**
n/a

**Comment by cp2004** [comment]
This is very similar/covered by #3936, further discussion should be there. I already said this was something I wanted, maybe I can be bothered to contribute it 😄.
