### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ingo916** [OctoPrint/OctoPrint#3992]
#### What were you doing?

I have two raspberry pi 4 running OctoPrint, I use the TP-Link Smartplug plugin to turn off the printers after x amount of idle time.
The plugin turns off the printer however octoprint keeps polling the printer.
The next day when I try to connect to the Octoprint web interface and I get the error

500 Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I cannot connect over HTTP however I can SSH to the Octopi servers.

#### What did you expect to happen?

I should be able to access OctoPrint over HTTP at any time. 

#### What happened instead?

Something is causing the HTTP service to stop. I can SSH into them and restart the Octoprint service and that fixes the issue.

#### Did the same happen when running OctoPrint in safe mode?

No, then it must be a plugin that is causing the issue

#### Version of OctoPrint

     OctoPrint 1.5.3
	 Python 3.7.3
	 OctoPi 0.18.0

#### Operating System running OctoPrint

	OctoPi 0.18.0

#### Browser and version of browser, operating system running browser

Firefox, Chrome, Safari

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
Please fill out the full template. Without logs and version and also the test in safe mode this can't be looked into.

**Comment by ingo916** [comment]
problem did not happen in safe mode, must be a plugin. I will close this now.
