### ISSUE TITLE
Octorpint resume after M600 command

### ISSUE THREAD

**Issue by bartoszwas** [OctoPrint/OctoPrint#3998]
I have a filament runout sensor on my Marlin 2.0.7 on my ender 3. Is it possible to make orctoprint resume when I click button on my 3d printer after filament change process?

My sensor pauses the printer, filament change process is ok but when I hit "continue print" on my machine it goes to last position and waits for resume from octoprint...

EMERGENCY_PARSER is enabled

orctoprint 0.18 on Raspberry Pi 4

**Comment by cp2004** [comment]
You must enable 'HOST_PROMPT_SUPPORT` and `HOST_ACTION_COMMANDS` in configuration_adv.h when you compile the firmware. If this is not working, then open a **bug report** with all the requested information. OctoPrint can't work on things that it doesn't know are happening, if the printer never reports back that it has resumed there is nothing that can be done.
