### ISSUE TITLE
[Request] Disable wifi sleep

### ISSUE THREAD

**Issue by hawkeyexp** [OctoPrint/OctoPrint#4012]
During using octoscreen i noticed sometimes reconnects by octoscreen which was caused by wifi sleep policy.

I disabled it with "iw dev wlan0 set power_save off" inside /etc/rc.local and the disconnects was gone.
I recommend disabling wifi sleep in sdcard image :-)

**Comment by cp2004** [comment]
This is the issue tracker for Octo*Print*, not Octo*Pi*, please report issues regarding OctoPi to [it's own repository](https://github.com/GuySoft/OctoPi).

See also - [What is the difference between OctoPi and OctoPrint?](https://community.octoprint.org/t/what-is-the-difference-between-octoprint-and-octopi-are-they-the-same-thing/185?u=charlie_powell) - if you didn't already know.
