### ISSUE TITLE
Could not update printer profile

### ISSUE THREAD

**Issue by dchamb55** [OctoPrint/OctoPrint#4019]
Having a problem trying to create a custom bounding box for the Prusa MK3S profile. I go to the "Print bed & build volume" tab, click the "Custom bounding box" box and enter -4 for Y coordinates minimum. Then click "Confirm" and the rotating circle on the Confirm button never goes away. 

If I abort and go back to printer profiles, the edit profile button is greyed out.

Restarting the server is the only way to get the edit profile button to return. During shutdown this pops on on the screen: 

Could not update profile
There was unexpected error while updating the printer profile, please consult the logs
[octoprint (7).log](https://github.com/OctoPrint/OctoPrint/files/5976741/octoprint.7.log)

**Comment by foosel** [comment]
Please create a bug report from your desktop computer and be sure to fill out the form: https://github.com/OctoPrint/OctoPrint/issues/new?assignees=&labels=&template=bug_report.yml&title=
