### ISSUE TITLE
[Request] Dark Mode (Natively)

### ISSUE THREAD

**Issue by 3DStyle** [OctoPrint/OctoPrint#4025]
**Describe the solution you'd like**
I would like to see support for dark mode in OctoPrint system, natively, without plugins involved.
When I'm at my caveman during night and print stuff, the bright OctoPrint interface makes it difficult to watch. 
A dark mode that will turn ON and OFF automatically by time zone/configured times will be very appreciated.

**Describe alternatives you've considered**
I tried Themeify but honestly didn't like it too much, in addition it doesn't have a feature to apply a theme automatically by time.

**Comment by fieldOfView** [comment]
This is something that can be implemented as a plugin. With early plans to refactor the whole UI in the future, I don't think this should be implemented in the core of OctoPrint at this point.

Apart from Themify which you already mentioned, there is also [UI Customizer](https://plugins.octoprint.org/plugins/uicustomizer/)
