### ISSUE TITLE
Hitting 'Reload non-conflicting changes' when settings are externally modified emits deprecation warning

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4030]
**The problem**

Problem code:

https://github.com/OctoPrint/OctoPrint/blob/2fc287768bb097035cd26826362016c50d0701a7/src/octoprint/static/js/app/viewmodels/settings.js#L770-L775

Seems to use something that's deprecated by itself, should this be changed?

```
settings.js:844 The callback parameter of SettingsViewModel.requestData is deprecated, the method now returns a promise, please use that instead. Stacktrace: Error
    at SettingsViewModel.self.requestData (http://192.168.1.158/static/js/app/viewmodels/settings.js:843:27)
    at HTMLAnchorElement.<anonymous> (http://192.168.1.158/static/js/app/viewmodels/settings.js:773:22)
    at HTMLAnchorElement.dispatch (http://192.168.1.158/static/js/lib/jquery/jquery.min.js:2:43090)
    at HTMLAnchorElement.v.handle (http://192.168.1.158/static/js/lib/jquery/jquery.min.js:2:41074)
```

**Did the issue persist even in safe mode?**

I cannot test this issue in safe mode (state why below)

**If you could not test in safe mode, please state why**

_No response_

**Version of OctoPrint**

1.5.3/1.6.0.dev

**Operating system running OctoPrint**

Windows 10, OctoPi 0.18

**Printer model & used firmware incl. version**

VIRTUAL

**Browser and version of browser, operating system running browser**

Microsoft Edge Version 88.0.705.74 (Official build) (64-bit)

**Checklist of files to include below**

- [X] octoprint.log
- [ ] serial.log or contents of your terminal tab (always include in cases of issues with printer communication)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

![image](https://user-images.githubusercontent.com/31997505/109062507-eebbc600-76df-11eb-9400-032012dbd2ef.png)

**Comment by foosel** [comment]
Should be fixed for 1.6.0 👍
