### ISSUE TITLE
[maintenance] 404 errors downloading logs

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4045]
### The problem

Click download on a log file, find 404 errors

Just heading to http://localhost:5000/downloads/logs/octoprint.log sends to a 404.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

 OctoPrint 1.6.0.dev379+gb5b1e8a81

### Operating system running OctoPrint

Windows 10

### Printer model & used firmware incl. version

NA

### Browser and version of browser, operating system running browser

NA

### Checklist of files to include below

- [X] octoprint.log
- [ ] serial.log or contents of your terminal tab (always include in cases of issues with printer communication)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

https://pastebin.com/5sudVTSv

Problem code is here:
https://github.com/OctoPrint/OctoPrint/blob/b5b1e8a812570b23ce3adc1f972744b59cb21982/src/octoprint/server/__init__.py#L769-L775

* Hidden path passes
* log ending passes
* `os.path.realpath(os.path.abspath(path))` gave me `'C:\\Program Files\\JetBrains\\PyCharm 2020.2.1\\jbr\\bin\\octoprint.log'`

Will look and see if I can fix this now.

**Comment by foosel** [comment]
Fixed by your PR, thank you!
