### ISSUE TITLE
"Server is offline" after minutes of idling

### ISSUE THREAD

**Issue by rkarlsba** [OctoPrint/OctoPrint#4056]
<img width="955" alt="Skjermbilde 2021-03-22 kl  16 36 26" src="https://user-images.githubusercontent.com/4253147/112016518-13635c00-8b2d-11eb-9648-8ad5d482c9bc.png">

Three different pi machines on different networks all report this after some idle time. I beleive this only happens when not printing, but I'm not quite sure. I haven't seen interrupted prints because of this, but it's rather annoying.

Is this a known problem?

**Comment by cp2004** [comment]
Please seek support through the community for issues with your setup. You can find help at the [community forums](https://community.octoprint.org) or on the [Discord server](https://discord.octoprint.org), where many helpful people are around.

This issue tracker is for bugs, and when you report bugs there is a reporting form [for you to fill in](https://github.com/OctoPrint/OctoPrint/issues/new?assignees=&labels=&template=bug_report.yml&title=) - this helps you to provide as much information as possible to help us solve the problem. We need more information than is present here.

If you have a bug to report, feel free to fill in the form but your issues is far more suited to the community forums.
