### ISSUE TITLE
[Request] Timelapse rendering: Adjust -b to match current ffmpeg docs

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint#4059]
the option -b should be used as -b:v or -b:a (video/audio),
but maybe for the resulting command-line it should not be empty..

fiddling with my error i found that this option-value seems also depend on the encoder, too:
![image](https://user-images.githubusercontent.com/5937811/112725928-007ccd00-8f1b-11eb-9658-7faa984fd872.png)

_Originally posted by @ozett in https://github.com/OctoPrint/OctoPrint/issues/3972#issuecomment-808751090_

**Comment by foosel** [comment]
- [ ] Find out what `-b` is actually supposed to be doing these days. `man ffmpeg` on OctoPi 0.18.0 and https://ffmpeg.org/ffmpeg.html does only mention it in the examples and it is otherwise completely undocumented, not even `-b:v` or `-b:a` are mentioned outside of examples.
- [ ] Find out if the codec options are indeed overridden via `-b` and if the different units apply here

**Comment by ozett** [comment]
dont forget that leaving -b blank in the gui seems to me breaking the resulting ffmpeg command.
also -b seems to requires not only numbers like "10000k" (so maybe gui-check this input?)

**Comment by foosel** [comment]
Switched to `b:v` and also added more sanity checking for the bitrate parameter at both API level and timelapse processing. Ready for 1.7.0.
