### ISSUE TITLE
Arduino Camera Stops Working after Update. (recommended fix doesn't work)

### ISSUE THREAD

**Issue by jameswis01** [OctoPrint/OctoPrint#4063]
### The problem

Fresh install of Octoprint 0.18.0 on Rasp4B... Setup Wifi... Logged in and went through 1st run setup.  Verified camera was working..
Received notification that there was an update available for Octoprint, and allowed the system to download the update and restart.  After restart, the camera no longer worked, and received an error stating the server wasn't running.  I was unable to get the server running again.  Tried to edit ocotpie.txt (forgot exact file name) and add -y to camera lines... Tried removing # from different camera line options.  All with same NON-Functional results.  To fix the issue I ended up reflashing the SD card with 0.18.0 again.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

No plugins installed yet.  Clean Install of Octoprint.

### Version of OctoPrint

0.18.0 (plus update that was downloaded)

### Operating system running OctoPrint

Octopi

### Printer model & used firmware incl. version

Ender3 (not connected to printer yet)

### Browser and version of browser, operating system running browser

Chrome 89.0.4389.90 

### Checklist of files to include below

- [X] octoprint.log
- [ ] serial.log or contents of your terminal tab (always include in cases of issues with printer communication)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

No longer have octoprint.log as I already wiped the card and reloaded fresh 0.18.0...

**Comment by cp2004** [comment]
This is not really an OctoPrint bug, since it does not deal with the webcam server *at all*. If you got to the 'Webcam server is not currently running' page, then something in mjpg streamer has crashed, haproxy is still working and so is OctoPrint. These are 3 different processes and 3 different pieces of software. I've replied to the question on discord about this issue.
