### ISSUE TITLE
[Request] Add a comment/notes-Box to store snippets for the instance

### ISSUE THREAD

**Issue by ozett** [OctoPrint/OctoPrint#4068]
### Describe the solution you'd like

i want to memorize some settings/text-snippets for the octoinstance. i want to store some infos directly on my octoprint to have it accessible with login to the gui. 

i would like to see a free-text box like this one, where i now type this in, to save comments for my octo-instance in the webgui, could be on front of the gui or in the settings.

### Describe alternatives you've considered

i cannot save text on my octoprint-instance .
i found no usable input-field in all settings-options.

**Comment by jneilliii** [comment]
There's my [Sticky Pad](https://plugins.octoprint.org/plugins/stickypad/) plugin.
