### ISSUE TITLE
the funding link on PyPI is broken

### ISSUE THREAD

**Issue by jugmac00** [OctoPrint/OctoPrint#4090]
The funding link on PyPI is broken as the funding subdomain uses the wrong certificate.

**Comment by jneilliii** [comment]
Interesting, it appears to be related to full domain name matching instead of the use of wildcard cert. The thing is that the link is just a redirect to https://www.octoprint.org/support-octoprint/ which does match the cert.

**Comment by foosel** [comment]
Should actually have been support.octoprint.org instead of donate, that's why there was a mismatch. I've just added that one as a redirect as well (and will fix the URL in upcoming releases). Thanks for the heads-up!
