### ISSUE TITLE
Lerdge K board RPi3B+ M114 error

### ISSUE THREAD

**Issue by Tarjei85** [OctoPrint/OctoPrint#4091]
Keep getting "Your printer does not support M114, and is incompatible with Octolapse" error when using octolaps.
If I send M114 through terminal I do get position in return. The specs sheet for the motherboard clearly states support for M114.

Running:
OctoPrint 1.5.3
Octolapse 0.4.1+u.8cae0c9
Lerdge K (4.3.1 B)
Raspberry Pi 3B+
Microsoft LifeCam Studio (through a powered USB hub)

Any idea how I can get this to work?

Attatched some screenshots as well as a log-file
[plugin_octolapse.log](https://github.com/OctoPrint/OctoPrint/files/6292407/plugin_octolapse.log)

![Screenshot_20210411-192234_Chrome](https://user-images.githubusercontent.com/82332849/114315284-92313080-9afe-11eb-8c48-28230a02864a.jpg)
![Screenshot_20210411-192218_Chrome](https://user-images.githubusercontent.com/82332849/114315287-93625d80-9afe-11eb-833f-b522e1e2d813.jpg)

**Comment by cp2004** [comment]
This is the bug tracker for OctoPrint, not for issues with plugins or to get help using OctoPrint. For bugs with plugins, please use the plugin's own issue tracker. For help and support using OctoPrint or plugins, please get in contact on the [community forums](https://community.octoprint.org/) or the [discord server](https://discord.octoprint.org).
