### ISSUE TITLE
After latest upgrade can't get rid of setup wizard

### ISSUE THREAD

**Issue by szabocs** [OctoPrint/OctoPrint#4097]
PSU Control just prompted me for upgrade, so I did it. 
After reboot I am getting a setup wizard with only a finish button on it.
If i click this button the screen stays and won't go away, basically rendering my 
octoprint installation unusable and I cannot print at the moment.
I will try to manually remove the plugin for now because i need to print.

![image](https://user-images.githubusercontent.com/1743531/115005906-9d8eae00-9ea8-11eb-9b4b-08710c2cb3c9.png)

**Comment by cp2004** [comment]
Not an OctoPrint issue, a plugin issue.

**Comment by cp2004** [comment]
You can use the recovery page (add /recovery to your URL) to remove it.

**Comment by szabocs** [comment]
Thanks managed to start the printing. 
Also sorry I didn't realize I was opening the issue on the octoprint git, 
the plan was to do it on the plugin's git.
