### ISSUE TITLE
PSU Control Stopped working after upgrade

### ISSUE THREAD

**Issue by joevj** [OctoPrint/OctoPrint#4100]
### The problem

1. I was using PSU control along with Relay connected to GPIO pin to switch the printer on and off, I was working fine until I upgraded today. I tried to download the support plugin "PSU Control- RPi GPIO" but that plugin has no config and is blank. I tried to select that in the PSU Control but that is not listed as a Plugin in that either.  Please help.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

I dont know how

### Version of OctoPrint

Version 1.5.3

### Operating system running OctoPrint

OctoPi | Version 0.17.0, running on Raspberry Pi 3 Model B Plus Rev 1.3

### Printer model & used firmware incl. version

Ender 3 Pro

### Browser and version of browser, operating system running browser

Chrome | Version 89.0.4389.128 (Official Build) (64-bit)

### Checklist of files to include below

- [X] octoprint.log
- [ ] serial.log or contents of your terminal tab (always include in cases of issues with printer communication)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

-

**Comment by cp2004** [comment]
This is not an issue with OctoPrint but an issue with the plugin.
