### ISSUE TITLE
Bug Report Issue Template Broken

### ISSUE THREAD

**Issue by kantlivelong** [OctoPrint/OctoPrint#4104]
Received a report about the bug report issue template not working.

`https://github.com/OctoPrint/OctoPrint/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml`
```
title must be a type of String. Learn more. 
```

Not seeing anything wrong so perhaps this is an issue w/ the github yaml template alpha?

@lukehefson Apologies if this isn't the right place for this but noticed you're on the commit history.

**Comment by foosel** [comment]
Yeah, some deployment on GitHub's end broke something, I just posted a workaround.
