### ISSUE TITLE
[Question] ttys0 since OP 1.6.0

### ISSUE THREAD

**Issue by Jack77777777** [OctoPrint/OctoPrint#4123]
I have ttys0 beside Auto and ttyUSB0 in OP since update to 1.6.0. What is this for?

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)

**Comment by Jack77777777** [comment]
I will try and see if someone answers ;)
