### ISSUE TITLE
Support for more than 10 Extruders

### ISSUE THREAD

**Issue by flinke-flasche** [OctoPrint/OctoPrint#4149]
### Describe the solution you'd like

adding the ability to adjust more extruder. 

### Additional context

I have a tool changer for 12 Filaments and can only use 10 colors with Octoprint, because i only can setup 10 extruders.

**Comment by foosel** [comment]
OctoPrint actually already supports an arbitrary number of extruders. However, the printer profile editor (and *only* the editor) had a max setting of the count of 10 and marked anything above as an error. You *can* however still submit it regardless of this mark up and thus create profiles with 12, 16, 200 extruders if you want. 

The HTML `max` will be removed in 1.7.0.

Note also that OctoPrint will also let you happily select tools out of the range of your printer profile's configured extruder count if you disable Settings > Serial Connection > Behaviour > Sanity Checking > Sanity check tool commands. That is about the only thing that I can think of that would make a printer with more than 10 extruders *not* work with OctoPrint right now (you sadly failed to communicate *what* doesn't work, so I'm guessing here).

In any case, change is pushed and will be in 1.7.0 and that should hopefully remove all confusion.
