### ISSUE TITLE
[Request] Add ability to customize backup file name

### ISSUE THREAD

**Issue by emklein** [OctoPrint/OctoPrint#4150]
### Is your feature request related to a problem? Please describe.

When using a version control system to store your backup files, it is very tedious to constantly have to delete the old backup files as they are deprecated. This is necessary because every backup file is named with the timestamp, so it is impossible to overwrite/version the latest backup file without manually renaming (which comes with its own complications depending on where you store/move the files to for versioning. 

### Describe the solution you'd like

A great solution would be to allow optional configuration of the filename in the Backup Plugin settings interface. This would allow to filename to cascade to any plugins that use it as well. 

### Describe alternatives you've considered

It would also be possible to deal with this feature on a plugin specific basis, but I could see that resulting in all of the backup related plugins adding it separately, which would lead to unnecessary duplicate code throughout the plugin repository. Depending on how Octorprint first creates the backup file though (I'm not versed enough to know how to find this in the code), I can imagine that it might be problematic for it to try to create a file with the same name as something that is already in the directory. If that is truly a problem, then having the plugin deal with it as it relocates it for backup would be the better option. I would rely on experienced programmers' feedback for the best solution. If it is decided to be best located at a plugin, that's fine, I can move my request there. Thanks!

### Additional context

None

**Comment by cp2004** [comment]
It is possible for plugins to create backups with custom names already, using the helpers. (https://docs.octoprint.org/en/master/bundledplugins/backup.html#octoprint.plugins.backup.BackupPlugin.create_backup_helper)

It's just not exposed in the UI and I'm not sure what happens if you try and use a name that is already in use.

**Comment by emklein** [comment]
Great, I'll approach this from a plugin pov. Thanks!
