### ISSUE TITLE
[Request]Disable Stepper Driver Motor

### ISSUE THREAD

**Issue by dumbozo** [OctoPrint/OctoPrint#4170]
### Is your feature request related to a problem? Please describe.

On the Ender 3v2 (but probably most printers) you can disable the stepper driver motors so you can manually change x, y and z-axis. This feature is not found in Octoprint so I have to turn to the printer display to disable these while other functions as extrusion, homing, changing x, y an z-axis through GUI is possible

### Describe the solution you'd like

just a button in the control page which disables the stpperdriver motors.

### Describe alternatives you've considered

use printer display

**Comment by cp2004** [comment]
This already exists:
![image](https://user-images.githubusercontent.com/31997505/121912664-aecd2d00-cd28-11eb-9df5-fd08d7c9f249.png)

**Comment by dumbozo** [comment]
just see motors off... hmm wonder if I am so blind... lol

**Comment by dumbozo** [comment]
sorry and thank you... I've clearly missed it while now looking for a logical location I found it. I think the bells din't ring... just looking for stepper driver or so
