### ISSUE TITLE
Terminal "Suppress movement messages" does not suppress G2/G3

### ISSUE THREAD

**Issue by Taomyn** [OctoPrint/OctoPrint#4172]
### The problem

Enabling "Suppress Movement Messages" for the terminal does not suppress G2/G3 commands (ARC) so they still get shown

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.6.1

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Ender 3 Pro

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20210618125823.zip](https://github.com/OctoPrint/OctoPrint/files/6676568/octoprint-systeminfo-20210618125823.zip)

![image](https://user-images.githubusercontent.com/4365929/122551252-03c4b800-d035-11eb-8988-3f1c7d936a6b.png)

**Comment by cp2004** [comment]
This is not one of the default filters:
https://github.com/OctoPrint/OctoPrint/blob/4c1152c70b5cb09158574eb5d3a14ec44695bb56/src/octoprint/settings.py#L426-L440

You need to adjust the regex in the settings.
