### ISSUE TITLE
Ender 3-Pro Stop from printer's UI is not working.

### ISSUE THREAD

**Issue by strfr** [OctoPrint/OctoPrint#4177]
### Is your feature request related to a problem? Please describe.

I can't stop printing from Ender 3-pro's UI. it continues and my computer is kind of far away from it when something went wrong.

### Describe the solution you'd like

I don't know if that is a bug or not but when something wrong on my printer(Ender 3-Pro) sometimes I need to stop it from printer UI because of computer is far away. But when I clicked stop print from UI it basically stops for couple of seconds and continue again. Is it possible to stop from UI or not? Thank you...

**Comment by foosel** [comment]
This doesn't sound like a general issue with OctoPrint but more like a problem with your specific setup. Please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
