### ISSUE TITLE
[Request] Disable webcam autofocus

### ISSUE THREAD

**Issue by PuaNow** [OctoPrint/OctoPrint#4182]
### Is your feature request related to a problem? Please describe.

the placement of my camera is in front of the print bed and the lack of a background and moving printed causes a focus issue. Autofocus kinda messes up octoprint and time-lapse videos

### Describe the solution you'd like

Turn off auto focus or focus on one point

### Describe alternatives you've considered

changing camera position

**Comment by foosel** [comment]
OctoPrint didn't directly control the camera, it merely embeds it. In OctoPi it is controlled via mjpg steamer, There are configuration options documented for that:

https://community.octoprint.org/t/how-can-i-change-mjpg-streamer-parameters-on-octopi/203

Also there are plugins for further tuning.
