### ISSUE TITLE
[Docker] Older version scheme breaks auto-updaters

### ISSUE THREAD

**Issue by Ornias1993** [OctoPrint/OctoPrint#4183]
Currently the dockerhub containers an old version scheme following the following format:
5512.0.0

Basically:
Highnumer.0.0

This leads to a situation where auto-updating systems like Renovate, will assume those old version numbers are newer than the actual latest release. (as 5512.0.0 is a higher version number than 1.6.1).

I would request those versions to be removed or retagged in such a way that they won't cause issues with updating systems.

**Comment by foosel** [comment]
Wrong repository, the one related to the docker builds is [here](https://github.com/OctoPrint/octoprint-docker).

**Comment by Ornias1993** [comment]
> Wrong repository, the one related to the docker builds is [here](https://github.com/OctoPrint/octoprint-docker).

Thanks, sorry for the misunderstanding (octoprint/octoprint and all)
