### ISSUE TITLE
Wi-Fi settings not working on fresh 0.18.0 installation

### ISSUE THREAD

**Issue by patoberli** [OctoPrint/OctoPrint#4184]
Hello
I've done a fresh installation of Octoprint 0.18.0 from here https://octoprint.org/download/. I've burned it to SD, put it into PI, booted it up, logged in and edited the /boot/octopi-wpa-supplicant.txt and rebooted. Wireless didn't work. I did various variants but none worked. 
In the end I run raspi-config and made my wireless configuration there and it instantly worked and is working since. No idea what went wrong, maybe the octopi-wpa-supplicant.txt file is only read at the very first boot?

Regards
Patrick

**Comment by cp2004** [comment]
I have no idea what went wrong either - and there's nothing here that's going to help us find out. I have no info on how you flashed the image, edited the wifi file, what editor was used, what kind of network you are trying to connect to, etc. Also, this is not to do with Octo*Print* but instead Octo*Pi*.

*Side note*: I am aware of an issue that if you use Raspberry Pi Imager to add your network details, then `octopi-wpa-supplicant.txt` may not work.

This issue tracker is for bugs & feature requests for OctoPrint. For help and support in using OctoPrint, plugins, and your general setup please get in touch on the [community forums](https://community.octoprint.org) or the [discord server](https://discord.octoprint.org) helpful people are around that can answer your questions. For bug reports please fill in the bug reporting form providing all of the requested information, as set out in the [contributing guidelines](https://github.com/OctoPrint/OctoPrint/blob/master/CONTRIBUTING.md).
