### ISSUE TITLE
[Request] Display Raspberry Pi processor temperature

### ISSUE THREAD

**Issue by ArnieO** [OctoPrint/OctoPrint#4197]
### Is your feature request related to a problem? Please describe.

It would be great to have the RasPi processor temperature displayed.

### Describe the solution you'd like

It can be read by using shell command `/opt/vc/bin/vcgencmd measure_temp`

**Comment by cp2004** [comment]
Doable with several plugins already:

https://plugins.octoprint.org/plugins/resource_monitor/
https://plugins.octoprint.org/plugins/toptemp/
https://plugins.octoprint.org/plugins/navbartemp/
