### ISSUE TITLE
[1.7.0rc2] Delete timelapse progress label is not placed properly

### ISSUE THREAD

**Issue by The-EG** [OctoPrint/OctoPrint#4210]
### The problem

One of the labels on the Delete Timelapses progress bar isn't placed properly:
![image](https://user-images.githubusercontent.com/7342077/129192313-08e61fd0-c4aa-441d-a8c0-c2593ec99e13.png)

It looks like it's the 'front' label that isn't centered:
![image](https://user-images.githubusercontent.com/7342077/129192402-1533cf4a-56c9-4134-af06-a786f16393ac.png)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.0rc2

### Operating system running OctoPrint

Raspberry Pi OS

### Browser and version of browser, operating system running browser

Waterfox G3.2.4.1

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20210812075555.zip](https://github.com/OctoPrint/OctoPrint/files/6975231/octoprint-systeminfo-20210812075555.zip)

No errors or additional output in the javascript console:
![image](https://user-images.githubusercontent.com/7342077/129192853-65e9b6db-d4c0-46ca-a1ec-8824d039b669.png)

**Comment by cp2004** [comment]
Was as a result of #4105, the JavaScript progress modal component needs to be updated in the same way the rest of the progress bars were from what I can see. 
https://github.com/OctoPrint/OctoPrint/blob/19388fc11f6fb62b8840d51ded7498c7b0028e49/src/octoprint/static/js/app/helpers.js#L998-L1163

**Comment by foosel** [comment]
Fix ready for 1.7.0rc3.
