### ISSUE TITLE
[Request] Disable mouse scrolling when panning on the gcode canvas

### ISSUE THREAD

**Issue by MarcelloTheArcane** [OctoPrint/OctoPrint#4218]
### Is your feature request related to a problem? Please describe.

When I'm zoomed in close to the gcode canvas, I often use the middle mouse button (mouse wheel) to pan around, as force of habit from various CAD programs.

This has the effect of showing the mouse wheel scroll feature on the whole page, which means it scrolls up and down when panning.

The panning still works, but the page moves around too.

### Describe the solution you'd like

I ran the following Javascript in the console, and I think it fixed the issue:

```js
function preventDefaultOnMouseWheel (event) {
    if (event.which === 2) { // Middle mouse button
        event.preventDefault() // Don't pan!
    }
}
const gcodeCanvasElement = document.getElementById('gcode_canvas')
gcodeCanvasElement.addEventListener('mousedown', preventDefaultOnMouseWheel)

// Clean up:
// gcodeCanvasElement.addEventListener('mousedown', preventDefaultOnMouseWheel)
```

I'm not sure if there are any side effects I need to consider, or where this could be added.

**Comment by MarcelloTheArcane** [comment]
Here's a video of what I mean:

https://user-images.githubusercontent.com/21159570/130263940-1c1ea3d1-10c8-49d9-8677-be4736059dd6.mp4

**Comment by thelastWallE** [comment]
add done label pls
