### ISSUE TITLE
Use utf-8-sig for bom_aware_open

### ISSUE THREAD

**Issue by flaviut** [OctoPrint/OctoPrint#4228]
This simplifies our code and allows us to avoid opening the same file twice.

Context:

> Looks like even python 2.7 supports `utf-8-sig`, which deals with Notepad's dumb little thing. Is there a reason `bom_aware_open` was written instead of using that?

IIRC (and mind you, the introduction of `bom_aware_open` was over six years ago so my memory is a bit fuzzy), simply using `utf-8-sig` didn't work at the time because it would then *require* the presence of the BOM and thus fail on files without it, which is why I went through the hassle of first detecting if the `-sig` encoding was needed before using it (which is pretty much all that `bom_aware_open` does). However, I currently cannot reproduce this with my local 2.7 environment anymore, so either I'm misremembering things here, or this behaviour back then was actually buggy and got fixed since, or behaviour simply got changed when switching from `codecs.open` to `io.open` during the big Python 3 compatibility refactoring.

Considering that it no longer seems to be an issue, I guess `bom_aware_open` can be retired (though since there might be plugins out there using it it needs a deprecation annotation and then turned into a transparent wrapper around `io.open` with `-sig` attachment to the `encoding` value as needed).

> Also, is there a particular reason `bom_aware_open`'s default encoding is ascii?

IIRC, back then `open` calls defaulted to ascii, so I did too.

_Originally posted by @foosel in https://github.com/OctoPrint/OctoPrint/pull/4222#discussion_r706026141_

**Comment by foosel** [comment]
Deprecated `octoprint.util.bom_aware_open` for 1.8.0. Slated for removal with 2.0.0. 

Can be replaced with `io.open` and using the corresponding `-sig` encoding, e.g. `io.open(path, encoding="utf-8-sig", mode="rt")`
