### ISSUE TITLE
Cursor stays in password field after incorrect login attempt

### ISSUE THREAD

**Issue by reedy** [OctoPrint/OctoPrint#4242]
### The problem

If you login with an invalid username/password (by hitting enter, rather than clicking "Log in"), the page refreshes, and the username and password fields are cleared. This is fine, but the cursor stays in the password box if it was there before logging in. It should either move back to the username box, or focus from either the elements removed completely.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.6.1

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

n/a

### Browser and version of browser, operating system running browser

macOS 11.6, FF 92.0.1

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [x] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20211001153534.zip](https://github.com/OctoPrint/OctoPrint/files/7267951/octoprint-systeminfo-20211001153534.zip)

https://user-images.githubusercontent.com/67615/135638605-8f00d085-335e-4f94-b0a8-1091b0de8718.mov

**Comment by thelastWallE** [comment]
I have a fix. To which branch should i create a PR? master?

**Comment by cp2004** [comment]
Sorry, should have specified - maintenance.
