### ISSUE TITLE
Can't upload files 15mb and above 

### ISSUE THREAD

**Issue by Model505** [OctoPrint/OctoPrint#4243]
### The problem

As the title states, I can't upload files 15mb and above, I've tried safe mode and I've googled everything I can think of but everything either includes something my version doesn't have or is to old to be relevant

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.6.1

### Operating system running OctoPrint

MacOS

### Printer model & used firmware incl. version

Ender 5

### Browser and version of browser, operating system running browser

Google

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20211001194429.zip](https://github.com/OctoPrint/OctoPrint/files/7269465/octoprint-systeminfo-20211001194429.zip
[CE5_Wizard_Tray_Lg_Tx_Circle_12h_51m.gcode.zip](https://github.com/OctoPrint/OctoPrint/files/7269486/CE5_Wizard_Tray_Lg_Tx_Circle_12h_51m.gcode.zip)
[WizardDiceRoofTwentyThreeHoursThirtyThreeMinutes.gcode.zip](https://github.com/OctoPrint/OctoPrint/files/7269487/WizardDiceRoofTwentyThreeHoursThirtyThreeMinutes.gcode.zip)
)

**Comment by cp2004** [comment]
Do you get any errors? What happens when you try and upload them? Can you post the contents of the browser console after you attempt to upload these files?

There's an option to configure the maximum size for file uploads, but the default is 1GB which should be sufficient. Could you check this is not configured in your config.yaml, located at `~/.octoprint/config.yaml`. It would be under [`server.uploads.maxSize`](https://docs.octoprint.org/en/master/configuration/config_yaml.html#server).

Otherwise, I can upload both your files to my OctoPrint instances fine, so it is likely some conflict somewhere, a setting or maybe a browser extension.

Please try and get access to the browser console - how you get there is dependent on the browser. You've said you are using 'Google' - that is a search engine found at https://google.com... so I'll assume you are using Chrome, the browser made by Google instead 😉. In that case, see [this guide I found](https://balsamiq.com/support/faqs/browserconsole/#google-chrome) that has some pictures to help find it.

**Comment by Model505** [comment]
The error was Could not upload the file. Make sure that it is a readable, valid file with one of these extensions: .g, .gco, .gcode, I just updated Google Crome so let me try to upload it again.

**Comment by Model505** [comment]
It didn't work, let me try to get to the browser console

**Comment by Model505** [comment]
i found this 
Failed to load resource: net::ERR_CONNECTION_RESET
{"files":[{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"16"},"date":1632934689,"display":"CE5_dice2_5.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":3.4,"width":127.65200000000002},"estimatedPrintTime":1330.8788352643933,"filament":{"tool0":{"length":1147.2292299999963,"volume":0.0}},"printingArea":{"maxX":137.752,"maxY":200.0,"maxZ":3.4,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"981461795ec90621d24ade4a7633cd219e233b54","name":"CE5_dice2_5.gcode","origin":"local","path":"CE5_dice2_5.gcode","prints":{"failure":1,"last":{"date":1632938727.092394,"printTime":2440.5541559509993,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_dice2_5.gcode","resource":"http://octopi/api/files/local/CE5_dice2_5.gcode"},"size":2385471,"statistics":{"averagePrintTime":{"_default":2440.5541559509993},"lastPrintTime":{"_default":2440.5541559509993}},"type":"machinecode","typePath":["machinecode","gcode"]},{"children":[],"display":"D&D minis","name":"D-D_minis","origin":"local","path":"D-D_minis","refs":{"resource":"http://octopi/api/files/local/D-D_minis"},"size":1824284668,"type":"folder","typePath":["folder"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"31"},"date":1630865669,"display":"Dragon_Scale_Test.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":6.4,"width":116.539},"estimatedPrintTime":1821.3108919609094,"filament":{"tool0":{"length":1653.932500000001,"volume":0.0}},"printingArea":{"maxX":126.639,"maxY":200.0,"maxZ":6.4,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"e0019ddce5f5c3865aed2125cb8b1836d35fe739","name":"Dragon_Scale_Test.gcode","origin":"local","path":"Dragon_Scale_Test.gcode","prints":{"failure":1,"last":{"date":1630868928.267979,"printTime":2993.363307462074,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/Dragon_Scale_Test.gcode","resource":"http://octopi/api/files/local/Dragon_Scale_Test.gcode"},"size":2214808,"statistics":{"averagePrintTime":{"_default":2993.363307462074},"lastPrintTime":{"_default":2993.363307462074}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"19"},"date":1632505413,"display":"CE5_dice2_1.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":4.0,"width":127.65200000000002},"estimatedPrintTime":1184.7094304992145,"filament":{"tool0":{"length":1027.291720000006,"volume":0.0}},"printingArea":{"maxX":137.752,"maxY":200.0,"maxZ":4.0,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"cbd6a852f1e02c59b046fc6e462f01800e299c77","name":"CE5_dice2_1.gcode","origin":"local","path":"CE5_dice2_1.gcode","prints":{"failure":0,"last":{"date":1632507962.100051,"printTime":2100.484461716,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_dice2_1.gcode","resource":"http://octopi/api/files/local/CE5_dice2_1.gcode"},"size":1701883,"statistics":{"averagePrintTime":{"_default":2100.484461716},"lastPrintTime":{"_default":2100.484461716}},"type":"machinecode","typePath":["machinecode","gcode"]},{"children":[],"display":"LEGO and Hero Factory","name":"LEGO_and_Hero_Factory","origin":"local","path":"LEGO_and_Hero_Factory","refs":{"resource":"http://octopi/api/files/local/LEGO_and_Hero_Factory"},"size":37156674,"type":"folder","typePath":["folder"]},{"children":[],"display":"Battletech","name":"Battletech","origin":"local","path":"Battletech","refs":{"resource":"http://octopi/api/files/local/Battletech"},"size":7486762,"type":"folder","typePath":["folder"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"76"},"date":1628966459,"display":"Test.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":15.4,"width":160.109},"estimatedPrintTime":3287.989124694517,"filament":{"tool0":{"length":2404.4858600000043,"volume":0.0}},"printingArea":{"maxX":170.209,"maxY":200.0,"maxZ":15.4,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"e6c7024a9032f497588d4cd496d220e4cc64e903","name":"Test.gcode","origin":"local","path":"Test.gcode","prints":{"failure":0,"last":{"date":1628973191.228382,"printTime":6411.27686404399,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/Test.gcode","resource":"http://octopi/api/files/local/Test.gcode"},"size":6757502,"statistics":{"averagePrintTime":{"_default":6411.27686404399},"lastPrintTime":{"_default":6411.27686404399}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"16"},"date":1632508287,"display":"CE5_dice2_2.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":3.4,"width":127.65200000000002},"estimatedPrintTime":1233.1055367503698,"filament":{"tool0":{"length":1050.0259699999976,"volume":0.0}},"printingArea":{"maxX":137.752,"maxY":200.0,"maxZ":3.4,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"d195972d7cc180540ec68fe9331eb5c39de08c63","name":"CE5_dice2_2.gcode","origin":"local","path":"CE5_dice2_2.gcode","prints":{"failure":0,"last":{"date":1632510908.745564,"printTime":2498.6814645990003,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_dice2_2.gcode","resource":"http://octopi/api/files/local/CE5_dice2_2.gcode"},"size":2862438,"statistics":{"averagePrintTime":{"_default":2498.6814645990003},"lastPrintTime":{"_default":2498.6814645990003}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"17"},"date":1632511628,"display":"CE5_dice2_3.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":3.6,"width":127.898},"estimatedPrintTime":1319.9931303343606,"filament":{"tool0":{"length":1115.6209499999932,"volume":0.0}},"printingArea":{"maxX":137.998,"maxY":200.0,"maxZ":3.6,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"251649b08633fba512cc6470305f691dec72e010","name":"CE5_dice2_3.gcode","origin":"local","path":"CE5_dice2_3.gcode","prints":{"failure":0,"last":{"date":1632514269.024042,"printTime":2490.0292356869995,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_dice2_3.gcode","resource":"http://octopi/api/files/local/CE5_dice2_3.gcode"},"size":2432068,"statistics":{"averagePrintTime":{"_default":2490.0292356869995},"lastPrintTime":{"_default":2490.0292356869995}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"31"},"date":1630947480,"display":"Scale_Test_2.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":6.4,"width":182.287},"estimatedPrintTime":9425.514287474409,"filament":{"tool0":{"length":8499.672149999562,"volume":0.0}},"printingArea":{"maxX":192.387,"maxY":200.0,"maxZ":6.4,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"bf04abec7381a8b8897c3afae4e433abda2e2e21","name":"Scale_Test_2.gcode","origin":"local","path":"Scale_Test_2.gcode","prints":{"failure":1,"last":{"date":1630955289.528091,"success":false},"success":0},"refs":{"download":"http://octopi/downloads/files/local/Scale_Test_2.gcode","resource":"http://octopi/api/files/local/Scale_Test_2.gcode"},"size":11930368,"statistics":{"averagePrintTime":{},"lastPrintTime":{}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"109"},"date":1633039391,"display":"CE5_treasure_chest_4hours_59minutes.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":22.0,"width":140.963},"estimatedPrintTime":11068.979475508111,"filament":{"tool0":{"length":10372.456769999353,"volume":0.0}},"printingArea":{"maxX":151.063,"maxY":200.0,"maxZ":22.0,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"8e9dddfd9c2926a43f44f9e07ace0f7db8f29296","name":"CE5_treasure_chest_4hours_59minutes.gcode","origin":"local","path":"CE5_treasure_chest_4hours_59minutes.gcode","prints":{"failure":1,"last":{"date":1633047680.985811,"success":false},"success":0},"refs":{"download":"http://octopi/downloads/files/local/CE5_treasure_chest_4hours_59minutes.gcode","resource":"http://octopi/api/files/local/CE5_treasure_chest_4hours_59minutes.gcode"},"size":4390124,"statistics":{"averagePrintTime":{},"lastPrintTime":{}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"16"},"date":1632934723,"display":"CE5_dice2_6.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":3.4,"width":127.65200000000002},"estimatedPrintTime":1275.5724128392544,"filament":{"tool0":{"length":1095.747930000003,"volume":0.0}},"printingArea":{"maxX":137.752,"maxY":200.0,"maxZ":3.4,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"715281b95ffce2058639977ee70951d0d06a9fd3","name":"CE5_dice2_6.gcode","origin":"local","path":"CE5_dice2_6.gcode","prints":{"failure":0,"last":{"date":1632941340.930307,"printTime":2459.9506376140007,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_dice2_6.gcode","resource":"http://octopi/api/files/local/CE5_dice2_6.gcode"},"size":2463480,"statistics":{"averagePrintTime":{"_default":2459.9506376140007},"lastPrintTime":{"_default":2459.9506376140007}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"150"},"date":1630014626,"display":"CE5_short_claw.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":30.2,"width":137.607},"estimatedPrintTime":7443.209049232792,"filament":{"tool0":{"length":5914.148169999863,"volume":0.0}},"printingArea":{"maxX":147.707,"maxY":200.0,"maxZ":30.2,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"315e99a3968ae6a7423085687f36bd344dfd12dd","name":"CE5_short_claw.gcode","origin":"local","path":"CE5_short_claw.gcode","prints":{"failure":0,"last":{"date":1630030897.132505,"printTime":15753.956240850966,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_short_claw.gcode","resource":"http://octopi/api/files/local/CE5_short_claw.gcode"},"size":18494863,"statistics":{"averagePrintTime":{"_default":15753.956240850966},"lastPrintTime":{"_default":15753.956240850966}},"type":"machinecode","typePath":["machinecode","gcode"]},{"children":[],"display":"D&D Templates","name":"D-D_Templates","origin":"local","path":"D-D_Templates","refs":{"resource":"http://octopi/api/files/local/D-D_Templates"},"size":61790464,"type":"folder","typePath":["folder"]},{"children":[],"display":"Gavin's stuff","name":"Gavins_stuff","origin":"local","path":"Gavins_stuff","refs":{"resource":"http://octopi/api/files/local/Gavins_stuff"},"size":5290506,"type":"folder","typePath":["folder"]},{"children":[],"display":"Holiday Stuff","name":"Holiday_Stuff","origin":"local","path":"Holiday_Stuff","refs":{"resource":"http://octopi/api/files/local/Holiday_Stuff"},"size":13383294,"type":"folder","typePath":["folder"]},{"children":[],"display":"D&D Trays","name":"D-D_Trays","origin":"local","path":"D-D_Trays","refs":{"resource":"http://octopi/api/files/local/D-D_Trays"},"size":42156919,"type":"folder","typePath":["folder"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"16"},"date":1632514447,"display":"CE5_dice2_4.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":3.4,"width":127.911},"estimatedPrintTime":1334.1841048100468,"filament":{"tool0":{"length":1149.331959999993,"volume":0.0}},"printingArea":{"maxX":138.011,"maxY":200.0,"maxZ":3.4,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"c786ea11e5e4fb3b339635a3819f6b0961adaa0e","name":"CE5_dice2_4.gcode","origin":"local","path":"CE5_dice2_4.gcode","prints":{"failure":0,"last":{"date":1633017790.929764,"printTime":2485.006931704,"success":true},"success":2},"refs":{"download":"http://octopi/downloads/files/local/CE5_dice2_4.gcode","resource":"http://octopi/api/files/local/CE5_dice2_4.gcode"},"size":2042119,"statistics":{"averagePrintTime":{"_default":2472.609452167},"lastPrintTime":{"_default":2485.006931704}},"type":"machinecode","typePath":["machinecode","gcode"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"475"},"date":1629409259,"display":"CE5_Adrex_HornX2.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":95.2,"width":133.165},"estimatedPrintTime":7929.428855154842,"filament":{"tool0":{"length":7449.9344799999035,"volume":0.0}},"printingArea":{"maxX":143.265,"maxY":200.0,"maxZ":95.2,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"f0183a4ea2c9c0249cacaf595165018d0b30110f","name":"CE5_Adrex_HornX2.gcode","origin":"local","path":"CE5_Adrex_HornX2.gcode","prints":{"failure":2,"last":{"date":1629479537.657983,"success":false},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_Adrex_HornX2.gcode","resource":"http://octopi/api/files/local/CE5_Adrex_HornX2.gcode"},"size":9632562,"statistics":{"averagePrintTime":{"_default":12163.068203476025},"lastPrintTime":{"_default":12163.068203476025}},"type":"machinecode","typePath":["machinecode","gcode"]},{"children":[],"display":"Other stuff","name":"Other_stuff","origin":"local","path":"Other_stuff","refs":{"resource":"http://octopi/api/files/local/Other_stuff"},"size":38741462,"type":"folder","typePath":["folder"]},{"DisplayLayerProgress":{"totalLayerCountWithoutOffset":"475"},"date":1629479302,"display":"CE5_Adrex_Horn_Mirror.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":95.2,"width":125.804},"estimatedPrintTime":8021.057779051321,"filament":{"tool0":{"length":7453.025349999966,"volume":0.0}},"printingArea":{"maxX":135.904,"maxY":200.0,"maxZ":95.2,"minX":10.1,"minY":20.0,"minZ":0.0}},"hash":"1def0398652d7feb26e27c3d761bcbf86a077e6f","name":"CE5_Adrex_Horn_Mirror.gcode","origin":"local","path":"CE5_Adrex_Horn_Mirror.gcode","prints":{"failure":0,"last":{"date":1629492278.440622,"printTime":12478.841468409984,"success":true},"success":1},"refs":{"download":"http://octopi/downloads/files/local/CE5_Adrex_Horn_Mirror.gcode","resource":"http://octopi/api/files/local/CE5_Adrex_Horn_Mirror.gcode"},"size":9782008,"statistics":{"averagePrintTime":{"_default":12478.841468409984},"lastPrintTime":{"_default":12478.841468409984}},"type":"machinecode","typePath":["machinecode","gcode"]}],"free":21307527168,"total":30322888704}

**Comment by Model505** [comment]
I figured out it was the browser.
