### ISSUE TITLE
Cannot upgrade to 1.7.0

### ISSUE THREAD

**Issue by Thamone** [OctoPrint/OctoPrint#4255]
### The problem

There is a popup to upgrade to Octoprint 1.7.0. After I click and wait until it's done, I've got this error

[Octoprint_upgrade_error.txt](https://github.com/OctoPrint/OctoPrint/files/7327321/Octoprint_upgrade_error.txt)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

OctoPrint 1.6.1

### Operating system running OctoPrint

OctoPi 0.16.0

### Printer model & used firmware incl. version

SKR V1.3 & printer.firmware: Marlin 2.0.5.3

### Browser and version of browser, operating system running browser

Firefox 93.0 64bit, Manjaro linux

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20211012071120.zip](https://github.com/OctoPrint/OctoPrint/files/7327353/octoprint-systeminfo-20211012071120.zip
[Octoprint_upgrade_error.txt](https://github.com/OctoPrint/OctoPrint/files/7327357/Octoprint_upgrade_error.txt)
)
[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/7327358/octoprint.log)
[plugin_softwareupdate_console.log](https://github.com/OctoPrint/OctoPrint/files/7327359/plugin_softwareupdate_console.log)

Sorry, I don't know how to get this "Contents of the JavaScript browser console"

**Comment by Thamone** [comment]
> Follow the same link posted in #4250

I did follow the instruction from #4250 but it's still failed.
Do I need to start new issue?
Anyway, I will report at this thread first

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/7327958/octoprint.log)
[plugin_softwareupdate_console.log](https://github.com/OctoPrint/OctoPrint/files/7327960/plugin_softwareupdate_console.log)
![14:42:55_12_10_21](https://user-images.githubusercontent.com/28747875/136914129-a85163c9-b2bc-4c4c-8f45-989440d47a4f.jpg)
[Octoprint_upgrade_error.txt](https://github.com/OctoPrint/OctoPrint/files/7327966/Octoprint_upgrade_error.txt)

**Comment by cp2004** [comment]
The error message has changed, but it now seems to be the same as #4254. Which seems to be something broken down within pip, or your environment - can't really tell, but something broke that shouldn't have done.

**Comment by foosel** [comment]
Seems to be a pip bug fixed in later versions: https://github.com/pypa/pip/issues/6197
