### ISSUE TITLE
1.70 temp reporting issue?

### ISSUE THREAD

**Issue by rjacobsonjr** [OctoPrint/OctoPrint#4259]
When I send a new print, the bed temp target will often show the PLA temp, instead of the Bed temp target.
After a while, it settles down and reports the correct temps.

**Comment by cp2004** [comment]
This is not enough to make a bug report. Please fill in the [bug report template](https://github.com/OctoPrint/OctoPrint/issues/new?assignees=&labels=&template=bug_report.yml).
