### ISSUE TITLE
Octoprint + Arcwelder plug-in + Save to SD = no good

### ISSUE THREAD

**Issue by bthekid** [OctoPrint/OctoPrint#4266]
What happened: 
Prepare gcode using cura 4.11.0
Send to octoprint using the cura "print with octoprint" option 
Save to SD is enabled
Octoprint receives the command and begins writing 
Arc-welder plug in pops up that it has welded xxxx amount of arcs

Result:
Gcode that is created does not use arcwelder until xxxx lines into the program

I noticed octoprint not sending or receiving anything and went to look at the printer to see it stuck in the front right corner. 
I usually don't select save to SD, as in I'll load the program to the SD card at my PC then walk over to the printer. 

If anymore information is needed please let me know. 

This is off the SD card ()
G1 X21.051 Y81.56 E74.45154
G1 X21.223 Y81.327 E74.46459
G1 X21.631 Y81.086 E74.48594
G1 X22.137 Y80.986 E74.50918
G1 X22.202 Y80.982 E74.51212
G1 X24.232 Y80.978 225.48866
G3 X123.322 Y124.781 I-2.251 J-316537.065 E226.72851
G2 X119.418 Y126.992 I0.021 J4.591 E226.93951
G3 X118.108 Y128.658 I-3.893 J-1.711 E227.03606
G1 X117.588 Y128.958 E227.06311
G1 X116.791 Y129.218 E227.10088
G1 X116.223 Y129.282 E227.12664
G1 X114.112 Y129.283 E227.22177
G3 X112.221 Y127.796 I0.027 J-1.980 E227.33788

This is octoprint receiving code (This was to recreate the error)
Recv: ok
Send: N289 G1 X121.574 Y98.969 E23.72971*105
Recv: ok
Send: N290 G1 X119.155 Y98.177 E23.84441*109
Recv: ok
Send: N291 G1 X116.806 Y97.467 E23.955*99
Recv: ok
Send: N292 G1 X114.355 Y96.785 E24.06964*98
Recv: ok
Send: N293 G1 X111.975 Y96.181 E242 X103.242 Y112.203 I43.022 J-103.063 E240.47003*26
Recv: ok
Send: N294 G0 F12000 X103.292 Y112.56*72
Recv: ok
Send: N295 G1 F900 X105.785 Y112.163 E240.58379*61

**Comment by jneilliii** [comment]
This would be an issue specific to arcwelder plugin and not OctoPrint. You should report this issue on that plugin's GitHub issue tracker. Alternatively, I could recommend you use the arcwelder plugin in Cura available via the Marketplace, that way the file gets welded before sending at all.

**Comment by bthekid** [comment]
Thank you,
I wasnt sure where to report the issue to so I posted it here and to arcwelder's github.

> 
> 
> This would be an issue specific to arcwelder plugin and not OctoPrint. You should report this issue on that plugin's GitHub issue tracker. Alternatively, I could recommend you use the arcwelder plugin in Cura available via the Marketplace, that way the file gets welded before sending at all.
