### ISSUE TITLE
Special Characters in file names break file actions

### ISSUE THREAD

**Issue by PCx43** [OctoPrint/OctoPrint#4267]
### The problem

If there is a # in the file name of the gcode, Octo does nothing.
No deleting, no moving, nothing possible.
Just a backup without uploading and metadata, then restore and the file is gone. 

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.0

### Operating system running OctoPrint

0.18.0

### Printer model & used firmware incl. version

CCR10SPROV2

### Browser and version of browser, operating system running browser

all

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by foosel** [comment]
The issue form asked you to provide a system info bundle. That's missing. please provide one.

**Comment by jcbarstow** [comment]
To be clearer, I renamed the problem files in the shell session after I found them in the file system.
