### ISSUE TITLE
1.7.2  appears to break printing from Cura

### ISSUE THREAD

**Issue by kwalkerk** [OctoPrint/OctoPrint#4295]
After upgrading to 1.7.2 I can no longer print from Cura on my Mac.  Have restarted everything, no joy!

![Screen Shot 2021-11-02 at 4 45 45 PM](https://user-images.githubusercontent.com/488547/139949208-ca595cef-e62e-48f4-9d9f-8c2639c12ed0.png)

Here is the System Bundle:

[octoprint-systeminfo-20211102205317.zip](https://github.com/OctoPrint/OctoPrint/files/7463948/octoprint-systeminfo-20211102205317.zip)

**Comment by cp2004** [comment]
You're using 1.7.1, not 1.7.2.

1.7.2 was released to fix *exactly this issue*.

**Comment by kwalkerk** [comment]
Thank for being nice to an idiot.

Sorry

**Comment by cp2004** [comment]
No worries 🙂
