### ISSUE TITLE
Heating issues on 2 different printers after updates

### ISSUE THREAD

**Issue by Ravingbantha** [OctoPrint/OctoPrint#4304]
### The problem

I have 2 printers running Octoprint an Ender 3 (not Pro) and a CR-10. When the update for 1.7 came out I updated both printers between prints. The Ender 3 worked fine, but the CR-10 started having issues. I sent a print and as the bed was heating it would send an error message and then disconnect. The Error message read "Your printer's firmware reported an error. Due to that Octoprint will disconnect. Reported error: Heating failed, system stopped! Heater_ID: 0 - printer halted. kill() called!"

Then when 1.7.2 came out, I updated both again, and then the Ender 3 started having problems. I would send a print and about 5 minuets or so Octoprint would disconnect and under 'State' it says 'Offline after error' and under that in red it says 'Thermal Runaway, system stopped! Heater_ID: 0 - Printer halted. kill() called!'

I could really use some help on this issue.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.2

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

CR-10 and Ender 3 standard both with base firmware

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20211104230253.zip](https://github.com/OctoPrint/OctoPrint/files/7479371/octoprint-systeminfo-20211104230253.zip
[octoprint-systeminfo-20211104190452.zip](https://github.com/OctoPrint/OctoPrint/files/7479372/octoprint-systeminfo-20211104190452.zip)
)

**Comment by jneilliii** [comment]
The issue tracker is for reports, not getting support. Please reach out on the Discord server or Community Forum for help with your thermal runaway errors. OctoPrint is just reacting to what your printer's firmware is doing.
