### ISSUE TITLE
Temperatures are not read by Octoprint since update

### ISSUE THREAD

**Issue by Datur0n** [OctoPrint/OctoPrint#4306]
### The problem

Since the update from 7.1.0 to 7.2.0, the temperatures that are reported by my Ender 3 V2 aren't read/processed by Octoprint.
I can see in the terminal that they are reported by my printer in the correct from:
...
Send: N6557 G1 F1500 X90.296 Y77.285 E1477.79166*0
Recv:  T:205.00 /205.00 B:50.00 /50.00 @:86 B@:18
Recv: ok
Send: N6558 G0 F7500 X90.998 Y77.421*116
...

The temperature graph isn't showing anything and looks like this:

![Graph](https://user-images.githubusercontent.com/93767879/140495437-b6c14406-62fb-4046-b06f-93d7be3acdea.png)

And my dashboard plugin can't read it as well, and it doesn't read the fan speed as well:

![Dashboard](https://user-images.githubusercontent.com/93767879/140495694-52886670-dbfb-4192-9b03-93e32ffdab1e.png)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

7.2.0

### Operating system running OctoPrint

OctoPi

### Printer model & used firmware incl. version

Ender 3 V2 Marlin 2.0.x-bugfix

### Browser and version of browser, operating system running browser

Chrome

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20211105102118.zip](https://github.com/OctoPrint/OctoPrint/files/7482336/octoprint-systeminfo-20211105102118.zip)

/?#tab_plugin_dashboard:1 [Deprecation] The website requested a subresource from a network that it could only access because of its users' privileged network position. These requests expose non-public devices and servers to the internet, increasing the risk of a cross-site request forgery (CSRF) attack, and/or information leakage. To mitigate these risks, Chrome deprecates requests to non-public subresources when initiated from non-secure contexts, and will start blocking them in Chrome 92 (July 2021). See https://chromestatus.com/feature/5436853517811712 for more details.
packed_core.js?0d093a46:1244 Starting dependency resolution...
packed_plugins.js?1887b165:10538 ***********************************
packed_plugins.js?1887b165:10539    Hello From OctoEverywhere! 🚀   
packed_plugins.js?1887b165:10540 ***********************************
packed_plugins.js?1887b165:10544 OctoEverywhere: Current hostname detected as a .local domain. octopi.local
packed_plugins.js?1887b165:10544 OctoEverywhere: Local frontend port found [port:80 isHttps:false url:http://octopi.local/?#tab_plugin_dashboard] reporting to backend.
packed_core.js?0d093a46:1257 ... dependency resolution done
packed_core.js?0d093a46:1280 Initial application setup done, connecting to server...
packed_core.js?0d093a46:1081 Connected to the server
packed_core.js?0d093a46:1087 Triggering connect on all view models
packed_core.js?0d093a46:1089 Server (re)connect processed
packed_core.js?0d093a46:1280 Finalizing application startup
packed_core.js?0d093a46:1261 Going to bind 56 view models...
packed_plugins.js?1887b165:21136 octolapse.help.js - Binding help links to #octolapse_tab a.octolapse_help[data-help-url]
packed_core.js?0d093a46:1273 Did not bind view model BackupViewModel to target #wizard_plugin_backup since it does not exist
packed_core.js?0d093a46:781 Chrome Arc Fix disabled
packed_core.js?0d093a46:781 Chrome Arc Fix enabled
packed_core.js?0d093a46:1273 Did not bind view model UsageViewModel to target #wizard_plugin_tracking since it does not exist
packed_core.js?0d093a46:1273 Did not bind view model OctoeverywhereViewModel to target #wizard_plugin_octoeverywhere since it does not exist
packed_core.js?0d093a46:1273 Did not bind view model ThespaghettidetectiveWizardViewModel to target #wizard_plugin_thespaghettidetective since it does not exist
packed_core.js?0d093a46:1273 Did not bind view model SoftwareUpdateViewModel to target #softwareupdate_confirmation_dialog since it does not exist
packed_core.js?0d093a46:1273 Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate_update since it does not exist
packed_core.js?0d093a46:1273 Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate_settings since it does not exist
packed_core.js?0d093a46:1273 Did not bind view model bedlevelvisualizerViewModel to target #wizard_plugin_bedlevelvisualizer since it does not exist
packed_core.js?0d093a46:216 User banneveldt logged in
packed_core.js?0d093a46:1278 ... binding done
packed_core.js?0d093a46:1278 Application startup complete
4packed_plugins.js?1887b165:2200 Adding Buttons
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: be89841e663ebdc5b28256041a59c8b434b03821
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 2872fe8a63246b9a7feaab56d78f842f7806c0e0
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 6998a6bc91f15bdde16f10719eef36e3cf63b404
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 69ac517329404a14989dfb2798b1da067e7bd111
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 3f74c72c9ed1a8d824fdc9986021ac2dd7520d4a
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 5929a698256a9fa35a0e07a41dd796b4a533a0dc
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 197a36ceb7590a01bc7f5858cf62e66278a88bfe
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 2d32d974f33da91a1c7df84ab5177d566fa415f6
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 988f09b94402e01668274ea8d7583693fbbb0a69
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 1a7799da835dd20e0b33741542058667cd1c47de
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 11a2aed825d5e68a24ee51d42c64ddaf6e2e3d9f
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 668f324589f6188dfd67a77239818f36ef05b1d2
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 394ec33392be090ba10552e7f3232d85637040be
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 0aa6f178bc574f5fecf1bef00bda034106ce6afd
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: cfff4e97cee98d563ab5b07a0bce19a3188513db
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: ba4070de271f8deb53477f64ebc5cd1f75ab608c
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 245ab4eefc6507297684d1ca5987aa67a98fa54e
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: b12c5c017bdca21555ac0ddf5bd091a65983fbe9
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 22baf2a306faefc1cbda8b442dbec9247e3483f9
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 8b550d29d01ae77013e2afd86926e340f77abe3f
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: b50c4a6eb4b849cfb956f5958a393c7afc8c73f4
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: e03be37bec2794d1e8471f6c0db2fbeffa35a2b5
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 0fc07c93634cec3b68852fda902f37a1912b3e9c
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 5d86361f16b957ef1f42b015140414e119ccb0de
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: fe1a1e30e6a0dbbfe96743b5dfad75f008db5cea
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: aaaa24bd1d1ee695a075f27862d671aa3f3a03d7
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 98cc01799b7ddd9628a17e4153cde4f1204189f1
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 4d0af518941b1d48449fc2573afb0a4484ee70b7
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 8c76da11ae0c585682487ca198cd313da90fece7
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 1a1f4681ab8e7cc84f50934c6e0564c94edd04da
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: db9dc3e3141662d9284efe6d90886ac3da9c2c58
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: e210d4c8ea39664a57f8379dcb907a3afe7344ea
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 2ac68f9d98e493a4e00aae0c4965139dede1ee58
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 8e2310fa1bb74cbcd5d44f66a4c143049a752c44
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 841e1a526f61fe14421fc0b5368b8bebafd57c70
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 40374a43bb399d5545d55573ed0dd84390ee98ea
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: b5ff78803a04b832981c57554f11c55339edb7cd
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 7376a38edaafb0816c72d15e5849e30c254d660d
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: f6440f6ec9c3d6564ae278bb507c7bbe40d0ab74
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 4c292450b584bd2ea0fc1c0b45c98dec7b1adbf9
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 6b602fc8fed0812dfa1ad4e5c9794c4068c8a79d
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 77648ad4db4aa96f58392ac4465dac0b8eb37cb1
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 1439cace146e29dc29bc91ee3fda4cb9e277e8ad
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: a1f814dc3337383cfc180605c61d7b7d0071f230
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: d0e9bdf02793fb00ca1c499042abdfec4edefcd8
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 92b949002da54898c6d70a1b53047b6ea537612d
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: b2f67a8292497d3413add6a53b0486ca088fb857
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 180b9fe6439dd892126b28bb568b5fb27c954e1a
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 9692670f7427627f41f2d66b6baba82f8de17859
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 30d7e122ce1baa6f81e14908fea51428276d4bc6
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 13dad5422117828d603d5aef2f18b744af88a925
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: c9dc8dc127a33077148aeba914c28115e5c2ce16
packed_plugins.js?1887b165:2205 Adding Buttons for file with hash: 428a10825ac7c9731dc81764e415c2407d597b93
2packed_plugins.js?1887b165:21136 octolapse.help.js - Binding help links to .octolapse .webcam_settings a.octolapse_help[data-help-url]
6The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
packed_core.js?0d093a46:863 ConfiguredLoggers has not changed. Not saving.
![Graph](https://user-images.githubusercontent.com/93767879/140496314-befd2d14-04ca-4012-9e6d-174cd58fc1d1.png)
![Dashboard](https://user-images.githubusercontent.com/93767879/140496320-d8869211-d548-4d13-8de3-09fccfb57e04.png)

**Comment by cp2004** [comment]
Update OctoEverywhere to 1.3.8 - the release of 1.3.7 was broken. You may need to select 'advanced options' and then 'force check' to find it.
