### ISSUE TITLE
Support for long file names on SD card for printing only

### ISSUE THREAD

**Issue by danielgalasso** [OctoPrint/OctoPrint#4308]
When attempting to print from SD card in the printer, I can only print files in the root folder. Subfolders come back stating there's something wrong with the subfolder.  Not sure what to do about this. 

Terminal looks like this: 

Changing monitoring state from "Operational" to "Starting print from SD"
Send: M27
Recv: Not SD printing
Recv: ok P15 B3
Send: M23 /PRODUCTS/AIRPLA~1/NOSEGE~1/AVANTI~1.GCO
Recv: echo:Now fresh file: /PRODUCTS/AIRPLA~1/NOSEGE~1/AVANTI~1.GCO
Recv: open failed, File: PRODUCTS.
Recv: ok P15 B3
Send: M24
Recv: ok P15 B3
Changing monitoring state from "Starting print from SD" to "Printing from SD"
Recv:  T:23.71 /0.00 B:23.09 /0.00 @:0 B@:0
Send: M27
Recv: Not SD printing
[octoprint-systeminfo-20211107020922.zip](https://github.com/OctoPrint/OctoPrint/files/7491567/octoprint-systeminfo-20211107020922.zip)
![image](https://user-images.githubusercontent.com/64235230/140629732-166e5883-2d3e-451e-9a41-da631716fb33.png)

**Comment by foosel** [comment]
That's a bug in your firmware, not one in OctoPrint.
