### ISSUE TITLE
Wrong layer count

### ISSUE THREAD

**Issue by AJErazzor** [OctoPrint/OctoPrint#4311]
getting twice the amount of layers in layer count than there should be.
example a 40mm high print at .15 layer height gives me 532 layers but this should be half of that.

![image](https://user-images.githubusercontent.com/5545511/140834213-a76f13de-b6df-49ed-84d0-52514bf4c35f.png)
[octoprint-systeminfo-20211109095425.zip](https://github.com/OctoPrint/OctoPrint/files/7500718/octoprint-systeminfo-20211109095425.zip)

**Comment by jneilliii** [comment]
This is an issue with DisplayLayerProgress plugin as the core OctoPrint does not provide this information. I believe that there is already an issue about it posted and you just need to remove one of the regex lines.

https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/issues/240
