### ISSUE TITLE
[Request] Include Klipper's printer.cfg in backups

### ISSUE THREAD

**Issue by TonyGiannini** [OctoPrint/OctoPrint#4312]
### Describe the solution you'd like

Include Klipper's configuration file ~/printer.cfg in the zipped backup file.  Even better, include any .cfg and .conf files in ~/, i.e. avrdude_gpio.conf.

### Describe alternatives you've considered

It's not difficult to back up and restore the files manually so this is more of a convenience than anything.

### Additional context

I'm running on a Raspberry 3B Rev 1.2.
Please close this request if it's already been requested.

**Comment by jneilliii** [comment]
similar to my request #4195 which would allow plugins to do this, which would then allow for the OctoKlipper plugin to include it.

**Comment by foosel** [comment]
Let's tackle this overall as part of #4195.
