### ISSUE TITLE
[Request] Revamp the web UI styles

### ISSUE THREAD

**Issue by ShivamJoker** [OctoPrint/OctoPrint#4323]
### Describe the solution you'd like

I would like the web UI of octoprint to be modern and cleaner
I am looking forward to contribute by updating some CSS to give it a modern look

Although most of the code is written in jQuery I am not sure if it is possible to migrate to react.js

**Comment by cp2004** [comment]
In three lines you've managed to summarise years of discussion and effort to figure out a path forward. It's not feasible to just 'update some CSS' without breaking *everything* for 320+ plugins. OctoPrint will be getting a new UI at some point, maybe written using React. But there is no simple way forward in the ecosystem. There's a few issues already open #3527 #2420, it is already on the list.
