### ISSUE TITLE
[Request] Log action command pause

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4330]
### Is your feature request related to a problem? Please describe.

If a printer pauses the print without the user asking it to - for example, on the Prusa MK3S it will pause if the fan speeds are too low - it can leave users clueless. Likewise I guess if a filament sensor triggered.

OctoPrint logs the reason for pausing/cancelling from API calls and plugins, but it doesn't seem to from action commands. This would allow for a quick explanation. 'Pausing print on behalf of the printer (action command)' means one doesn't have to spend ages guessing/enabling serial.log and hoping it might happen again.

### Describe the solution you'd like

Log something like the message above, on pause from `// action:pause` from the printer.

### Additional context

https://discord.com/channels/704958479194128507/705046975669600298/916817893839216680

# Implementation help

*This may be a good first issue for a new contributor*

- Action command pauses have some tags set on the command here https://github.com/OctoPrint/OctoPrint/blob/53b9b6185781c07e8c4744a6e28462e96448f249/src/octoprint/util/comm.py#L2336-L2340
- This can be compared to log like the rest of the pause reasons here https://github.com/OctoPrint/OctoPrint/blob/53b9b6185781c07e8c4744a6e28462e96448f249/src/octoprint/util/comm.py#L1829-L1853

**Comment by evanwurden** [comment]
Is this still an issue? I see "Pausing on request of the printer..." logged when the printer is paused via action command.

**Comment by cp2004** [comment]
Indeed it is no longer an issue, since it was addressed in #4358. I hadn't realised that when adding the help for a contributor! Thanks for pointing that out.
