### ISSUE TITLE
need help with getting daVinci 1.0 Pro to respond to serial input

### ISSUE THREAD

**Issue by skytect** [OctoPrint/OctoPrint#4334]
### The problem

I'm trying to hook up OctoPrint to a daVinci 1.0 Pro and getting no response from the serial device.

What I did:
1. Install and run OctoPrint
```bash
mkdir octoprint
cd octoprint
pipenv install octoprint
pipenv run octoprint serve --port 12345 --safe
```
2. Open the "Terminal" tab
3. Run `ls /dev/tty.*` with the printer disconnected and connected and realise the serial port is `/dev/tty.usbmodem21101`
4. Try pressing "Connect" with both "Serial Port" set to "AUTO" and "/dev/tty.usbmodem21101"
5. Receive the following output when serial port is set to "/dev/tty.usbmode21101":
```
Performing autodetection with 7 port/baudrate candidates: /dev/cu.usbmodem21101@115200, /dev/cu.usbmodem21101@250000, /dev/cu.usbmodem21101@230400, /dev/cu.usbmodem21101@57600, /dev/cu.usbmodem21101@38400, /dev/cu.usbmodem21101@19200, /dev/cu.usbmodem21101@9600
Trying port /dev/cu.usbmodem21101, baudrate 115200
Connecting to port /dev/cu.usbmodem21101, baudrate 115200
Handshake attempt #1 with timeout 2.0s
Connected to: Serial<id=0x111ae3850, open=True>(port='/dev/cu.usbmodem21101', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=2.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Send: N0 M110 N0*125
Handshake attempt #2 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #3 with timeout 2.0s
Send: N0 M110 N0*125
Trying port /dev/cu.usbmodem21101, baudrate 250000
Handshake attempt #1 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #2 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #3 with timeout 2.0s
Send: N0 M110 N0*125
Trying port /dev/cu.usbmodem21101, baudrate 230400
Handshake attempt #1 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #2 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #3 with timeout 2.0s
Send: N0 M110 N0*125
Trying port /dev/cu.usbmodem21101, baudrate 57600
Handshake attempt #1 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #2 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #3 with timeout 2.0s
Send: N0 M110 N0*125
Trying port /dev/cu.usbmodem21101, baudrate 38400
Handshake attempt #1 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #2 with timeout 2.0s
Send: N0 M110 N0*125
Handshake attempt #3 with timeout 2.0s
Send: N0 M110 N0*125
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'read failed: [Errno 6] Device not configured' @ comm.py:_readline:3940
Please see https://faq.octoprint.org/serialerror for possible reasons of this.
Changing monitoring state from "Detecting serial connection" to "Offline after error"
Connection closed, closing down monitor
```

I have also tried manually connecting to the serial port with a serial monitor and also received no response from there.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.2

### Operating system running OctoPrint

macOS 12.1 Beta

### Printer model & used firmware incl. version

daVinci 1.0 Pro, 1.4.0

### Browser and version of browser, operating system running browser

Chrome Version 98.0.4736.0 (Official Build) dev (arm64)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20211208105800.zip](https://github.com/OctoPrint/OctoPrint/files/7673038/octoprint-systeminfo-20211208105800.zip)

I would appreciate any form of help I could get to get manually sending GCode over to the printer working and am willing to engage in a back and forth in this issue if necessary.

Oh, also XYZprint (the official slicer) does work and is able to connect to the printer both via WiFi and USB.

edit: Oh hmm XYZPrint shows that it's connected to `/dev/cu.usbmodem21101`

**Comment by jneilliii** [comment]
Based on [this](https://community.octoprint.org/t/octoprint-for-all-printers-form3-anycubic-ultimaker/13776/5?u=jneilliii) post, it seems that davinci may be using a proprietary system, which is why you have to use their slicer. We reserve the issue tracker for bugs, which this is not, so I recommend reaching out on the forum or Discord server to see if anyone wants to reverse engineer the communication layer for your printer.
