### ISSUE TITLE
New PRUSA Firmware screen display bug

### ISSUE THREAD

**Issue by martinglass** [OctoPrint/OctoPrint#4354]
Upgraded my Prusa MK3S+ to firmware v3.10 (prusa3d_fw_MK3S_3_10_0_4481.hex)

When starting a print from file in Octoprint, the LCD display on the Prusa shows white blocks instead of data, on many of the lines (not all).

After OctoPrint has finished printing, the display returns to normal.

I've attached photos to show the problem (the data that isn't white blocks flashes at about 1Hz).

![IMG_6310](https://user-images.githubusercontent.com/41255030/147469799-d4e57d60-db51-4352-a340-d1d4a3771ed4.JPG)

![IMG_6309](https://user-images.githubusercontent.com/41255030/147470882-02bfb6db-bd13-486f-8325-08ecff535113.JPG)

Here is the system info bundle...
[octoprint-systeminfo-20211227121638.zip](https://github.com/OctoPrint/OctoPrint/files/7780129/octoprint-systeminfo-20211227121638.zip)

**Comment by cp2004** [comment]
If it worked fine on the old firmware but not on the new one, why is this an OctoPrint issue?

**Comment by martinglass** [comment]
> If it worked fine on the old firmware but not on the new one, why is this an OctoPrint issue?

You're right. I've checked printing from SD Card and it happens that way too. So, it's not an OctoPrint issue.

Thanks.

I'll close this issue.

**Comment by martinglass** [comment]
I've checked printing from SD Card and it happens that way too. So, it's not an OctoPrint issue.
