### ISSUE TITLE
dashboard constantly has 'busy' rotating animation

### ISSUE THREAD

**Issue by r0dnay** [OctoPrint/OctoPrint#4374]
### The problem

dashboard constantly has 'busy' rotating animation

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

currently in print and need some plugins intact

### Version of OctoPrint

1.7.2

### Operating system running OctoPrint

W10 21H1 19043.1466

### Printer model & used firmware incl. version

MARLIN 2.0.9.3

### Browser and version of browser, operating system running browser

9.5.0.2 FIREFOX

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220118102028.zip](https://github.com/OctoPrint/OctoPrint/files/7891232/octoprint-systeminfo-20220118102028.zip)
![swirly octo dash](https://user-images.githubusercontent.com/97747057/149989496-6ab9f784-afbc-49a1-b5df-caa53994b559.JPG)

**Comment by foosel** [comment]
That's a third party plugin, not core OctoPrint. Please report this to the author of the dashboard plugin.
