### ISSUE TITLE
Rotate/Mirror options not applied to HLS webcam stream

### ISSUE THREAD

**Issue by crysxd** [OctoPrint/OctoPrint#4375]
### The problem

1. Setup HLS webcam in OctoPi
2. Enable the rotate option in settings
3. Go back to webcam

Expected: Image rotated
Actual: Image not rotated

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

maintenance branch

### Operating system running OctoPrint

OctoPi

### Printer model & used firmware incl. version

/

### Browser and version of browser, operating system running browser

Safari, Chrome

### Checklist of files to include below

- [X] [Systeminfo Bundle (always include!)](https://github.com/OctoPrint/OctoPrint/files/7894646/octoprint-systeminfo-20220119063500.zip)
- [X] [Contents of the JavaScript browser console (always include in cases of issues with the user interface)](https://github.com/OctoPrint/OctoPrint/files/7894641/console.log)
- [X] [Screenshots and/or videos showing the problem (always include in case of issues with the user interface)](https://user-images.githubusercontent.com/5859228/150077449-3cd9606c-31c7-4817-940a-b192f7e9753d.mov)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

Happy to pick this up myself! Just wanted to  raise the issue here so it is documented for others. Most likely also applies to RTSP

**Comment by cp2004** [comment]
1.8.0 has been released 🎉
