### ISSUE TITLE
Octoprint connects to "Nothing"

### ISSUE THREAD

**Issue by heregoesnothing3d** [OctoPrint/OctoPrint#4394]
Every bootup or restart octoprint connects to a ghost or something. All buttons that control the printer are grayed out as if nothing was connected. Hitting the 'Disconnect' button doesn't do anything for ~10 minutes. If i click the disconnect button and leave my cursor still, it will disconnect like I said after ~10 minutes. Super annoying and makes it really frustrating to start a print.
[octoprint-systeminfo-20220131180537.zip](https://github.com/OctoPrint/OctoPrint/files/7974815/octoprint-systeminfo-20220131180537.zip)

**Comment by cp2004** [comment]
Please fill in a [bug report](https://github.com/OctoPrint/OctoPrint/issues/new?assignees=&labels=&template=bug_report.yml) rather than a blank issue so we get all the information needed.
