### ISSUE TITLE
Standard output is unreadable on console

### ISSUE THREAD

**Issue by zaitcev** [OctoPrint/OctoPrint#4396]
### The problem

I didn't do a git pull for a few months and somehow the console output became colorized so much that it's basically unreadable. This was okay before, at least in October 2021.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

lI

### Printer model & used firmware incl. version

Linux, Fedora 35

### Browser and version of browser, operating system running browser

Firefox

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220131185951.zip](https://github.com/OctoPrint/OctoPrint/files/7974982/octoprint-systeminfo-20220131185951.zip)
![octocolor1](https://user-images.githubusercontent.com/227426/151892739-5ed53948-fbff-4c06-ba2d-3df959427b7b.jpg)

**Comment by cp2004** [comment]
The log output was colourised starting with 1.7.x. Took a peek at the code, it is setting 'INFO' to be white. On a white background, that definitely doesn't work so good...

Maybe a configurable flag could be used (`--no-colour` or something) to disable it, or I will test what happens if the 'INFO' colour is unset, so it would go back to being the 'default'.

**Comment by zaitcev** [comment]
I would think that killing colors altogether may be throwing out the baby with the bathwater. However, it is still preferable for my circumstances.

**Comment by cp2004** [comment]
Addressed by #4402

**Comment by zaitcev** [comment]
I'm sorry if I'm missing something, but it appears that the fixes were merged into branch "maintenance", which I'm using branch "master", so they are not available to me. Are the commits in danger of being forgotten in the maintenance branch?

**Comment by cp2004** [comment]
master is the current stable release, aka OctoPrint 1.7.3. When 1.8.0 is released, the work that is currently ongoing to be 1.8.0 that is happening on the maintenance branch will be merged into the master branch as the new stable release.

**Comment by foosel** [comment]
Also refer to the branching model described in the docs here: https://docs.octoprint.org/en/master/development/branches.html and linked to from the contribution guidelines.

**Comment by zaitcev** [comment]
Thanks for the explanation and the reference. I'll close the issue once I'm able to test.
