### ISSUE TITLE
webcam access is not restricted

### ISSUE THREAD

**Issue by rico001** [OctoPrint/OctoPrint#4401]
### The problem

Hello,
It seems webcam access is not restricted.
Problem: /webcam/..-URL's are accessable on HTTP-GET-Requests without user login or API-Key. I'm not sure that users are aware of this.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Anycubic i3 Mega S

### Browser and version of browser, operating system running browser

all common browsers

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

[octoprint-systeminfo-20220205080024.zip](https://github.com/OctoPrint/OctoPrint/files/8007616/octoprint-systeminfo-20220205080024.zip)

**Comment by fieldOfView** [comment]
The `/webcam' handling, and `mjpgstreamer` are not features of OctoPrint. They come with OctoPi, so your issue is with that repository. A quick search resulted in this feature request: https://github.com/guysoft/OctoPi/issues/292

**Comment by foosel** [comment]
For the record, this is also covered in the FAQ

https://community.octoprint.org/docs?topic=233

and OctoPrint also tells the user that exposing the instance in the public internet or other hostile networks is a really bad idea at multiple places, this being one of the reasons.

**Comment by cp2004** [comment]
And there is the warning at the top of the page here:
![image](https://user-images.githubusercontent.com/31997505/152637804-5afbc9b2-3118-415b-89a4-c9b3d4795d3f.png)

**Comment by rico001** [comment]
I added my cam with plug an play yesterday. I did not know this cam tab in settings. thx guys.
