### ISSUE TITLE
Octoprint is very slow on pi b+

### ISSUE THREAD

**Issue by chrineuh** [OctoPrint/OctoPrint#4407]
### The problem

I have put the orignial image on e pi b+ with the raspberry imager.

But the pi is very solw it tooks about 10min to restart octoprint, an one pugin called smart filament sensor i can not activate, after restart it is always deaktivatet

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1,7,3

### Operating system running OctoPrint

0.18.0

### Printer model & used firmware incl. version

Qidi X-Max

### Browser and version of browser, operating system running browser

Chrome and Firefox

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by foosel** [comment]
This is not a bug, this is expected and the reason why it's not recommended:

![image](https://user-images.githubusercontent.com/83657/152962114-7a70bc99-03f3-417d-b4f6-57648479e137.png)
