### ISSUE TITLE
Can't install any plugins

### ISSUE THREAD

**Issue by RYAN010101** [OctoPrint/OctoPrint#4411]
### The problem

I have not used OctoPrint in like 8 months and I started using it again. Works fine except I can't download any plugins. Any plugin I try to download just sits on the installing page and after like 30-45 seconds it says error, here's a copy and paste:

Installing plugin from https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere/archive/master.zip...
(30 seconds later)
Error!
Unexpected error while trying to install plugin from None

I don't know what to do, this seems to happen with any plugin I try to install. Do I try wiping my sd card and starting fresh?

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

I can't test it in safe mode because you can't install plugins in safe mode

### Version of OctoPrint

OctoPrint 1.6.1

### Operating system running OctoPrint

Python 3.7.3

### Browser and version of browser, operating system running browser

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
connectivity.connection_check: 1.1.1.1:53
connectivity.connection_ok: false
connectivity.enabled: true
connectivity.online: false
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: false
env.hardware.cores: 4
env.hardware.freq: 1500
env.hardware.ram: 1903988736
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 4 Model B Rev 1.4
env.plugins.pi_support.octopi_version: 0.18.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 20.3.3
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.6.1
systeminfo.generator: systemapi

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/8028452/octoprint.log)

[plugin_pluginmanager_console.log](https://github.com/OctoPrint/OctoPrint/files/8028453/plugin_pluginmanager_console.log)

[plugin_softwareupdate_console.log](https://github.com/OctoPrint/OctoPrint/files/8028454/plugin_softwareupdate_console.log)

[serial.log](https://github.com/OctoPrint/OctoPrint/files/8028455/serial.log)

[systeminfo.txt](https://github.com/OctoPrint/OctoPrint/files/8028456/systeminfo.txt)

[octoprint-systeminfo-20210703034701.zip](https://github.com/OctoPrint/OctoPrint/files/8028470/octoprint-systeminfo-20210703034701.zip)

**Comment by foosel** [comment]
Your OctoPrint instance isn't able to reach outside. It also thinks it's still July. I suggest you make sure it has the right date and time first (ntp might be failing for some reason). Feel free to open a support request for that on the forums, but this is not a bug, that's an environmental issue on your instance specifically.
