### ISSUE TITLE
No Filament Data on Octoprint with prusa slicer

### ISSUE THREAD

**Issue by Devilmorpheus** [OctoPrint/OctoPrint#4413]
### The problem

When I slice a STL in Prusa Slicer, I have the amount of Filament and the weight on the screen. After upload to Octoprint it‘s gone. It always says „0“

when I‘ll take The Cura Slicer it’s still there after the upload.

Does anybody know the reason for this Problem?

### Did the issue persist even in safe mode?

No, it did not persist (it's an issue with one of your installed plugins, don't report here)

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

Octopi  0.18.0

### Printer model & used firmware incl. version

Prusa MK3 and Mini

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

![C1DFAF44-2BA6-4135-8500-8BD6C45AA50A](https://user-images.githubusercontent.com/99393202/153382767-c91157f7-1895-4ebd-9e54-4863af016a79.jpeg)

**Comment by jneilliii** [comment]
> No, it did not persist (it's an issue with one of your installed plugins, don't report here)

General questions like this should be asked in the community forum or on discord, the issue tracker is specifically for bugs and feature requests.
