### ISSUE TITLE
Persist checkbox states in UI for gcode viewer, terminal filters, and whatever checkboxes there might be that make sense to be remembered...

### ISSUE THREAD

**Issue by szafran81** [OctoPrint/OctoPrint#443]
Hi,

It would be if the OctoPrint would remember the values that are entered in the GUI (eg. temp offsets, extrude length etc.)

Szafran

**Comment by foosel** [comment]
Also related: #58 #225

**Comment by MoonshineSG** [comment]
save terminal active filters now available: https://github.com/MoonshineSG/OctoPrint-ActiveFilters

**Comment by foosel** [comment]
Most of this is probably implemented for a long time now, and if anything is still missing requires a new request.
