### ISSUE TITLE
[Request] add a UI button to swap between Octoprint instances (IPs) in the same network

### ISSUE THREAD

**Issue by LidorBaum** [OctoPrint/OctoPrint#4436]
### Is your feature request related to a problem? Please describe.

I have 2 Raspberri Pis running Octoprint on 2 printers. I am willing to have a nice option to swap between them in browser, instead of writing the IP in the URL.

### Describe the solution you'd like

If you know the WLED library, there is also a button to swap between instances of WLED in the same network by IP address, very easy and intuitive.

**Comment by OllisGit** [comment]
Hi @LidorBaum, 
do you mean something like this:
![image](https://user-images.githubusercontent.com/24205767/159093990-07ec83fc-9be5-46fb-ab5e-40dc3a1ee800.png)
![image](https://user-images.githubusercontent.com/24205767/159094161-c8972dc0-935a-4192-a092-7950d11551bf.png)

Maybe I need an additional option "open in new tab"...will see.

**Comment by LidorBaum** [comment]
@OllisGit Hi, exactly this! I can not find it in the octoprint plugins, nor in your repo (its empty), is it released yet?

**Comment by fieldOfView** [comment]
> Maybe I need an additional option "open in new tab"...will see.

I would do that with the normal CTRL+click.

What could be an interesting feature is to use bonjour discovery to populate the list automatically.

**Comment by OllisGit** [comment]
Hi,
I change the plugin name to "BookmarkManager" and released the first version.

https://github.com/OllisGit/OctoPrint-BookmarkManager

It now looks like this:
![image](https://user-images.githubusercontent.com/24205767/159559571-89a5bf3a-3150-43f4-be71-17ea253b7a3c.png)

PS. the  "bonjour discovery" feature is also tracked in the repo ;-)
