### ISSUE TITLE
Wide Screen support - HomePage Tab options[Request]

### ISSUE THREAD

**Issue by jseaz73** [OctoPrint/OctoPrint#4441]
### Is your feature request related to a problem? Please describe.

It would be super cool if I had the details of the Dashboard, the Gcode viewer (or pretty G code) and then the webcam @ the same time ... 

### Describe the solution you'd like

Options to change the layout or number of "Tiles" on the the DB

**Comment by jneilliii** [comment]
Consolidated Tabs plugin,  widescreen plugin,  combined temp control plugin.

**Comment by cp2004** [comment]
Since this is possible with the above plugins, the request can be closed.
