### ISSUE TITLE
[Request] Webcam (re)start script

### ISSUE THREAD

**Issue by fhteagle** [OctoPrint/OctoPrint#4451]
### Is your feature request related to a problem? Please describe.

I was recently having trouble with a 3rd party webcam, for several issues that were not really the fault of octoprint. However, to troubleshoot required a ton of reboots, as I am not familiar with how the entire webcam stack works yet. 

So, my request is a button, command line script, or similar to (re)initialize the webcam stack as if a reboot occurred. This would facilitate faster troubleshooting, minimize chances of microsd failure on power cycling, etc.

I did look around briefly for this, but did not find it easily. If it already exists, please write up or link to instructions that already exist, to help others find it easier as well.

Thanks! 

### Describe the solution you'd like

So, my request is a button, command line script, or similar to (re)initialize the webcam stack as if a reboot occurred. This would facilitate faster troubleshooting, minimize chances of microsd failure on power cycling, etc.

### Describe alternatives you've considered

A ton of rebooting (works, but cumbersome).

Looked around on my octoprint instance and searched the net, but did not stumble upon such a thing.

### Additional context

Octoprint rocks, thanks for this project and what it enables us to do.

**Comment by jneilliii** [comment]
You can achieve this with [System Commands.](https://docs.octoprint.org/en/master/configuration/config_yaml.html#system).

```
system:
  actions:
  - action: restartwebcam
    command: sudo service webcamd restart
    name: Restart Webcam
```
