### ISSUE TITLE
[1.8.0rc1] Fatal startup error in settings, "can only concatenate str (not "int") to str"

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint#4454]
### Problem

Had one instance update fine, had another instance not do so well with the following when I try to manually start octoprint via `~/oprint/bin/octoprint serve`. Will try to grab more details later today as I have to get to work right now. 

```
pi@flsun:~ $ ./oprint/bin/octoprint serve
2022-03-14 08:41:05,384 - octoprint.startup - CRITICAL - Could not initialize settings manager: can only concatenate str (not "int") to str
2022-03-14 08:41:05,384 - octoprint.startup - CRITICAL - There was a fatal error starting up OctoPrint.
Could not initialize settings manager: can only concatenate str (not "int") to str
There was a fatal error starting up OctoPrint.
```

_Originally posted by @jneilliii in https://github.com/OctoPrint/OctoPrint/issues/4452#issuecomment-1066741782_

### Solution

Probably caused by the new flattened setting hierarchy not handling `int` keys properly, need to sprinkle in some `str` conversions.

**Comment by foosel** [comment]
Can confirm that the issue are integer keys in the settings hierarchy which makes the settings startup fail in the flattening code of the new hierarchy implementation.

**Comment by foosel** [comment]
Fix ready for 1.8.0rc2

**Comment by benlye** [comment]
Same problem here.  Rolling back to 1.7.3 and awaiting 1.8.0rc2.

**Comment by foosel** [comment]
Should come today, currently in the process of tackling #4456

**Comment by foosel** [comment]
Might become tomorrow, found another issue in the new settings backend.

**Comment by foosel** [comment]
1.8.0rc2 has been released.
