### ISSUE TITLE
[1.8.0rc1] Gcode viewer rendering ahead of progress & stalling on layer change while progress catches up

### ISSUE THREAD

**Issue by mod38** [OctoPrint/OctoPrint#4459]
### The problem

After upgrading to 1.8.0 RC1, the gcode viewer doesn't work properly. At first I thought it was freezing up but when  observed it for some time I saw that the progress bar below the viewport was moving too quickly and when it reached 100% the display stopped updating until the start of the next layer. 

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.0 RC1

### Operating system running OctoPrint

OctoPi 1.18.0

### Printer model & used firmware incl. version

Prusa Mini

### Browser and version of browser, operating system running browser

Firefox and Chrome on Windows 10 PC but also Chrome on a Raspberry Pi 4B and on a Samsung Tab2S Android tablet

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220315135122.zip](https://github.com/OctoPrint/OctoPrint/files/8253894/octoprint-systeminfo-20220315135122.zip)

I also downgraded to 1.7.3 to check and there was no problem with that version.

**Comment by foosel** [comment]
@mod38 could you also provide a gcode file with which you can reproduce this? I cannot currently reproduce this and would like to make sure I have at least a file which definitely causes problems on your end.

**Comment by mod38** [comment]
[Gear_bookmark_0.15mm_PLA_MINI_10m.gcode.zip](https://github.com/OctoPrint/OctoPrint/files/8254327/Gear_bookmark_0.15mm_PLA_MINI_10m.gcode.zip)
(I had to zip as gcode files are not accepted
![gcode_error](https://user-images.githubusercontent.com/11555722/158402859-cdcc574f-c997-4e5f-9057-2c8265cba8db.jpg)
)

**Comment by foosel** [comment]
Yeah, good thing I asked for that file, definitely something weird going on in there and my local test files are working just as expected. Thanks!

**Comment by foosel** [comment]
Nope, something about how this file is sliced just unearthed a bug in how the parsed data structure the gcode viewer creates is handed over from a worker to the actual UI. Half the layer contents never arrive. Currently trying to figure out why

**Comment by foosel** [comment]
I think I finally got it, at least I can no longer reproduce and other test files are still working as expected as well. Fix ready for 1.8.0rc2

**Comment by mod38** [comment]
Great! Sorry to be trouble/ glad to be of assistance!

**Comment by foosel** [comment]
Absolutely no trouble (well, apart from the initial reluctance to open a ticket 😉)! The RC phase is meant to unearth stuff like this, so I'm glad your files turned out to be structured in such a way that this precise bug was triggered and thus could be hunted down BEFORE this went stable, even though the bug itself caused me some more grey hair 😂

**Comment by foosel** [comment]
1.8.0rc2 has been released.
