### ISSUE TITLE
1.8.0rc2 needs refresh after powering on printer

### ISSUE THREAD

**Issue by bullestock** [OctoPrint/OctoPrint#4469]
### The problem

I use the OctoRelay plugin to power my printer on and off. After upgrading to rc2, OctoPrint says "No serial port found" and does not react to powering the printer on. I need to click 'refreshing' before I can connect - this was not necessary before.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

If I disable plugins, I cannot power my printer on

### Version of OctoPrint

1.8.0rc2

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Ender 5 Pro, Marlin

### Browser and version of browser, operating system running browser

Firefox, Arch Linux

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220319162109.zip](https://github.com/OctoPrint/OctoPrint/files/8309629/octoprint-systeminfo-20220319162109.zip)

**Comment by foosel** [comment]
Yes. New feature, can be switched off through the settings, please read the changelog when installing an RC.
