### ISSUE TITLE
Change the position that is displayed on the leveling screen 35x35 should be the base...

### ISSUE THREAD

**Issue by fkamaral** [OctoPrint/OctoPrint#4485]
### Is your feature request related to a problem? Please describe.

please, change the Y axis position to have the 35 option at the bottom of the screen.
![image](https://user-images.githubusercontent.com/6277354/162645413-31d02676-1caf-4858-87c4-acc0b9bdaf23.png)

### Describe the solution you'd like

Just invert that, and we will see the bed at the same position that we are looking into it!

### Describe alternatives you've considered

don't do anything.
[octoprint-systeminfo-20220411000141.zip](https://github.com/OctoPrint/OctoPrint/files/8460742/octoprint-systeminfo-20220411000141.zip)

### Additional context

not sure if other people look at the bed the same way I do, but if they do, it will make sense to them either!

**Comment by jneilliii** [comment]
This should be posted in the plugin's GitHub repo not in OctoPrint's
