### ISSUE TITLE
Can't change folder paths on 1.8.0rc4

### ISSUE THREAD

**Issue by PowerWiesel** [OctoPrint/OctoPrint#4486]
### The problem

Can't change folder paths on 1.8.0rc4

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.0rc4

### Operating system running OctoPrint

OctoPi 0.18.0

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220411065930.zip](https://github.com/OctoPrint/OctoPrint/files/8461442/octoprint-systeminfo-20220411065930.zip)
![Bildschirmfoto vom 2022-04-11 07-57-30](https://user-images.githubusercontent.com/11167590/162673732-10d33d5f-983d-4d29-a8f4-803ecc427de8.png)

**Comment by foosel** [comment]
Fixed, 1.8.0rc5 is out.
