### ISSUE TITLE
GCODE Viewer reports wrong number of layers

### ISSUE THREAD

**Issue by pc-bastler** [OctoPrint/OctoPrint#4495]
### The problem

In GCODE Viewer one more layer than in Cura is reported.

Also the print does start at layer 2 in the viewer.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

Raspian Bullseye

### Printer model & used firmware incl. version

Ender 3V2

### Browser and version of browser, operating system running browser

Safari 15.4, macOS 12.3.1

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

The attached GCODE file is just an example, it appears with every GCODE file, I prin
[octoprint-systeminfo-20220423112703.zip](https://github.com/OctoPrint/OctoPrint/files/8546606/octoprint-systeminfo-20220423112703.zip)
[CE3PRO_pnmBusinessCardHolder.gcode.zip](https://github.com/OctoPrint/OctoPrint/files/8546608/CE3PRO_pnmBusinessCardHolder.gcode.zip)
![Bildschirmfoto 2022-04-23 um 11 31 39](https://user-images.githubusercontent.com/46841479/164889021-cfc1a5fb-7e47-440d-af74-a1efbd82be5f.png)
t

**Comment by cp2004** [comment]
At the start of your gcode file, there is a 'layer' that looks like a prime line:

![image](https://user-images.githubusercontent.com/31997505/164890934-ed2fa338-574f-4928-8451-d06f5f66ce4e.png)

The next layer is what you would probably consider as the 'first' layer, but it is at a different Z height, so technically it is not. The Z height goes 0.3 (prime line), 0.2 (actual model), 0.32, 0.44 for the first 4 layers in the actual gcode.

This is probably not counted by Cura as my guess would be it is part of your start gcode script that is added on to the model after it is sliced.
