### ISSUE TITLE
[Request] remember 'suppress' options in the Terminal tab

### ISSUE THREAD

**Issue by jj-uk** [OctoPrint/OctoPrint#4499]
### Is your feature request related to a problem? Please describe.

Each time I refresh octopi in the browser (Google chrome), the suppress checkboxes are cleared.

To reproduce:
Open the terminal screen. (http://octopi/#term)
Check some boxes.
Refresh the browser.

### Describe the solution you'd like

Remember the previous state of the checkboxes and autoscroll settings.
![image](https://user-images.githubusercontent.com/10943625/164972150-047ea33d-d404-4dea-a16b-b4d646dd42cc.png)

**Comment by jneilliii** [comment]
Install active filters extended plugin.

https://plugins.octoprint.org/plugins/active_filters_extended/
