### ISSUE TITLE
Ender 5 - Octoprint - RPi | remaining time NULL when I preheat the printer

### ISSUE THREAD

**Issue by DcFamas** [OctoPrint/OctoPrint#4501]
### The problem

Hey there,
I'm using and RPI 3b+, Octoprint v. with my Creality Ender 5.

Whenever I preheat the printer in the menu (to change the filament) the remaining time will not be calculated.
My steps are:

- Turn printer on
- Preheat PLA in the settings
- change filament manually
- start print in Octoprint through Ultimater Cura

When I just turn the printer on and start the print, the time will be calculcated correctly. 

![grafik](https://user-images.githubusercontent.com/35306967/165114154-a23a6889-cafa-4149-9413-84a7dc408311.png)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Ender 5

### Browser and version of browser, operating system running browser

Chrome/Firefox/Edge

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220425164821.zip](https://github.com/OctoPrint/OctoPrint/files/8555610/octoprint-systeminfo-20220425164821.zip)

**Comment by kantlivelong** [comment]
Hi @DcFamas,

If I understand correctly you are setting the temperature (from either OctoPrint or the printers LCD) before starting any print job and the time estimate "Print Time Left" is not displaying.  Does it actually say NULL or something else? 

Right now OctoPrint doesn't provide time estimates outside of an active print job but the idea sounds interesting.

**Comment by DcFamas** [comment]
Hi @kantlivelong 
not exactly.

- I set the temperature through the printers LCD, in my case the "preheat PLA" menu
- then I start a regular printjob via. Octoprint
- now ocotoprint doesn't give any Print Time Left information, check out my screenshot "Dauer: 00:02:99" but the "Verbleibend" is just a read circle

It just happens when I first preheat the printer. When I just start the print, everything works fine.

Best regards

**Comment by foosel** [comment]
@DcFamas Does this still happen on OctoPrint 1.8.6? I cannot see anything hinting at issues with the estimation calculation in your log.

If it does, then please enable `serial.log`, reproduce the issue, create a new systeminfo bundle and upload it here.

**Comment by DcFamas** [comment]
Sorry, I haven't attached the printers LCD anymore. :/

**Comment by foosel** [comment]
In that case, lets close this so it doesn't clutter the bug tracker. If someone else runs into it, they can create a new report, or we can reopen this one.
