### ISSUE TITLE
[Request] Backup for plugins and its configurations

### ISSUE THREAD

**Issue by ganti** [OctoPrint/OctoPrint#4502]
### Is your feature request related to a problem? Please describe.

My SD-Card broke, and I had to setup everything fresh. I had a backup, but the backup contains by design no plugins and its settings.

### Describe the solution you'd like

What about backup a list of plugins, which will be recommended for install.
Each plugin may contain a backup folder, where its settings can be stored
With this a plugin maintainer could save the configurations in their way, and could restore it their way.

### Describe alternatives you've considered

I could dump the whole SD-card from time to time to have a full backup avaliable

**Comment by jneilliii** [comment]
That is incorrect. The backup does contain a plugin list to allow for reinstall on restore and all plugin's data folder contents as well as settings stored in config.yaml will be restored as well.
