### ISSUE TITLE
Octoprint docker container missing vcgencmd command

### ISSUE THREAD

**Issue by hemna** [OctoPrint/OctoPrint#4507]
### The problem

Running the official https://hub.docker.com/r/octoprint/octoprint container 
results in comlaints in octoprint for missing 'vcgencmd' command when I login to the UI.

The error message
```
OctoPrint cannot check for throttling situations reported by your Pi. vcgencmd doesn't work as expected. Make sure the system user OctoPrint is running under is a member of the "video" group.
```

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

running in a container

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

Host os is raspi Raspbian GNU/Linux 11 \n \l

### Printer model & used firmware incl. version

doesn't matter

### Browser and version of browser, operating system running browser

brave on macos

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220509125130.zip](https://github.com/OctoPrint/OctoPrint/files/8651782/octoprint-systeminfo-20220509125130.zip)

**Comment by cp2004** [comment]
This is due to the fact it is a docker container, it doesn't have access to the host environment in the same way. The repository for the docker container 'port' of OctoPrint is https://github.com/OctoPrint/octoprint-docker, and it looks like there's some suggestions already on https://github.com/OctoPrint/octoprint-docker/issues/207 of how to make it work.
