### ISSUE TITLE
I cannot use octopi with this issues

### ISSUE THREAD

**Issue by Ab2dx** [OctoPrint/OctoPrint#4508]
### The problem

hi
I'm new to the world of 3D printing and I downloaded update E3V2-ManualMesh-5x5-v4.2.2-v2.0.1.bin from JyersUl

On my ender 3v2 printer with a 4.2.2 board it worked without problems until I connected my raspberry pi 3 b

With 5V stripped USB cable
*I cut the 5 V wired inside the USB cable *

And I installed the octoprint system, the latest version and I thought everything was fine,  and he is fine really sometimes , I can see my printer see my WebCam knowing all information about the nozzle or the bed but  guess what  problems  just started

When I  connect The system sometimes, error screen appears in the printer bearing the code M112
So I need to restart the printer or either the raspberry pi to have a connection

And IF I want to Print AND OCTOPRINT ?  Is Connected

all weird problems appear like fire

I cannot print at all because of errors that occur during printing and frequent stops with unrelated problems.

 It is also not possible to cancel printing completely from the printer itself or from the external system, even despite the separation of OCTO, the printer remains in the printing cycle without exit without stopping, Slow to respond, freezes for a moment even sometimes even if I succeeded in canceling,
From the printer screen and I disconnected from the octopi l The printer continue printing with nothing  this circle of problem did not stop 
until I shut down the printer

Then, the error code M112 appears!! Again

 I don't want to give it up, but I'm completely unbalanced with OCTOPRINT , 

I only use it for WebCam :( 

So what is the solution for that ? 

### Did the issue persist even in safe mode?

No, it did not persist (it's an issue with one of your installed plugins, don't report here)

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

Octopi

### Printer model & used firmware incl. version

Ender 3 V2 , E3V2-ManualMesh-5x5-v4.2.2-v2.0.1.bin from JyersUl

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by jneilliii** [comment]
This is a firmware issue, not OctoPrint issue. I'd ask for help on community forum or Discord server. Also, since you're using Jyers firmware you may want to look [here](https://github.com/Jyers/Marlin/wiki/OctoPrint-Settings).
