### ISSUE TITLE
Weird behavior when updating 1.7.3 to 1.8.0

### ISSUE THREAD

**Issue by marsroverdriver** [OctoPrint/OctoPrint#4514]
### The problem

My initial attempt to upgrade to from 1.7.3 to 1.8.0 through the Web interface failed (Python version is 3.7.3). This error is in the log:

"""
```
2022-05-19 20:39:58,517 - octoprint.plugins.softwareupdate - ERROR - Update of octoprint can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 2090, in _perform_update
    else:
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 115, in perform_update
    _log_message(
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/util/pip.py", line 208, in execute
    CommandlineCaller.__init__(self)
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/util/commandline.py", line 244, in call
    # thread
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/util/commandline.py", line 236, in process_stdout
    }
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/util/commandline.py", line 230, in process_lines
    kwargs.update(
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/util/pip.py", line 498, in _preprocess_lines
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/util/pip.py", line 517, in _preprocess
    # This is horribly ugly and I'm sorry...
  File "/usr/local/cache/OctoPrint/venv/lib/python3.7/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return to_bytes(_ANSI_REGEX.sub("", to_unicode(line)))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-44: ordinal not in range(256)

```
"""
[octoprint-systeminfo-20220519204459.zip](https://github.com/OctoPrint/OctoPrint/files/8735823/octoprint-systeminfo-20220519204459.zip)

When I retried in Safe Mode, I got a different symptom: it immediately said it succeeded ("The update finished successfully") -- there was no apparent attempt to download the update -- and there was a yellow dialog in the upper right that read "Updating ... Now updating, please wait" with a spinning gear icon. I gave it ten minutes, but it never exited, and nothing was using CPU on my Pi as reported by htop.

I opened a connection in another browser tab, where OctoPrint seemed to be working and claimed to have updated to 1.8.0. <shrug> Of the choices below, it seemed like "Yes, it did persist" was the least bad, but the symptoms were different in Safe Mode, so I wasn't sure of the best choice there.

![image](https://user-images.githubusercontent.com/1007953/169448039-bf5c8592-0672-4f19-a7b3-558f757d5c43.png)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.3

### Operating system running OctoPrint

MXRPi_22.03.08 (MX Linux)

### Printer model & used firmware incl. version

Disconnected from my printer ATM

### Browser and version of browser, operating system running browser

Chrome 100.0.4896.127, Devuan GNU/Linux 4 (chimaera)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

JavaScript console content:

"""
packed_libs.js?7111420c:4063 Less has finished and no sheets were loaded.
packed_core.js?17695fbf:1304 Starting dependency resolution...
packed_core.js?17695fbf:1317 ... dependency resolution done
packed_core.js?17695fbf:1340 Initial application setup done, connecting to server...
packed_core.js?17695fbf:1135 Connected to the server
packed_core.js?17695fbf:1140 Triggering connect on all view models
packed_core.js?17695fbf:1142 Server (re)connect processed
packed_core.js?17695fbf:1340 Finalizing application startup
packed_core.js?17695fbf:1321 Going to bind 38 view models...
packed_core.js?17695fbf:1333 Did not bind view model BackupViewModel to target #wizard_plugin_backup since it does not exist
packed_core.js?17695fbf:806 Chrome Arc Fix disabled
packed_core.js?17695fbf:806 Chrome Arc Fix enabled
packed_core.js?17695fbf:1333 Did not bind view model UsageViewModel to target #wizard_plugin_tracking since it does not exist
packed_core.js?17695fbf:1333 Did not bind view model SoftwareUpdateViewModel to target #softwareupdate_confirmation_dialog since it does not exist
packed_core.js?17695fbf:1333 Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate_update since it does not exist
packed_core.js?17695fbf:1333 Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate_settings since it does not exist
packed_core.js?17695fbf:228 User maxwell logged in
packed_core.js?17695fbf:1338 ... binding done
packed_core.js?17695fbf:1338 Application startup complete
packed_core.js?17695fbf:1268 Error calling onTabChange on view model ControlViewModel : Unknown stream type 
callViewModelIf @ packed_core.js?17695fbf:1268
5The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
11packed_core.js?17695fbf:1268 Error calling onBrowserTabVisibilityChange on view model ControlViewModel : Unknown stream type 
callViewModelIf @ packed_core.js?17695fbf:1268
"""

**Comment by jneilliii** [comment]
https://community.octoprint.org/t/i-cannot-install-uninstall-update-plugins-update-octoprint-or-restore-a-backup-i-get-a-unicodeencodeerror-latin-1-codec-cant-encode-characters/42684?u=jneilliii
