### ISSUE TITLE
OctoPrint 1.8.0 - adding "Read-only Access" subgroup to the "Guests" group leads to "too many redirects" browser error

### ISSUE THREAD

**Issue by joshwills** [OctoPrint/OctoPrint#4516]
### The problem

Discovered on an image that had been updated from OctoPrint 1.7.3 to 1.8.0, but tested and reproduced on the latest image "OctoPi 0.18.0 & OctoPrint 1.8.0 SHA256: 3bc0e09ceea9f7b19fd8bead56ad09605e93c34d3aa87910674b0dc18df70e7f ".

Process:

- Flash image to SD card
- Boot Pi4 2GB with SD card
- Navigate to octopi.local
- Run through initial setup wizard
- After finishing the wizard, logout of OctoPrint
- Refresh the page to verify the login window shows up
- Login
- Navigate to **Settings**, **Access Control**
- Under the **Groups** tab, edit the **Guests** group
- Under the **Subgroups** tab, check **Read-only Access**
- Save/Confirm out of all menus
- Log out of OctoPrint
- Refresh the page to verify that now the login page is never loaded

To recover from this state, need to SSH to the Pi, stop the OctoPrint service, edit groups.yaml to remove the "readonly" subgroup from the "guests" group, then start the OctoPrint service.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.0

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Not applicable - reproducible with printer connected or not

### Browser and version of browser, operating system running browser

Multiple computers and browsers tested, but two specific examples:  "Vivaldi 5.2.2623.46 (Stable channel) (Pending update 5.2.2623.48) (64-bit) " and "Firefox 100.0.2 (64-bit)" both on "Windows 10 Version 21H2 (Build 19044.1706)"

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [x] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220520194902.zip](https://github.com/OctoPrint/OctoPrint/files/8743475/octoprint-systeminfo-20220520194902.zip)

https://www.youtube.com/watch?v=ZE0eDQHOzPc is a video showing the basic reproducing steps - that's on the same OctoPi 0.18.0 image as documented above.

This is the saved HAR file from the network recording tab:
[chromewebdata-guestPermissionIssue.zip](https://github.com/OctoPrint/OctoPrint/files/8743507/chromewebdata-guestPermissionIssue.zip)

The only javascript console log is about a Chrome deprecation: "crbug/1173575, non-JS module files deprecated."

**Comment by cp2004** [comment]
Confirmed - this didn't happen before 1.8.0. To be honest, when I found out it used to work I was surprised that it was a feature before considering that it allows people to setup access without *any* security. But it did work.
