### ISSUE TITLE
Order events on event manager and add "custom name" column

### ISSUE THREAD

**Issue by pracovnik** [OctoPrint/OctoPrint#4518]
### Is your feature request related to a problem? Please describe.

I got a lot of events in event manager and there is no auto-order in the list to it look not nice.

![image](https://user-images.githubusercontent.com/40662523/169824184-1854e14e-e509-4e55-8c09-675a429756fc.png)

### Describe the solution you'd like

(1)
I would like to ask you to add one new column as "Display name" and hide the command column (show command as bubble when hovering mouse over)

(2)
Add a kind of generic table, which has also ordering by columns

> event name
> (add new column) display name
> command , not shown in table, if display name will exist>
> enabled/disabled
> buttons for edit/delete 

### Describe alternatives you've considered

Manually click on the page till I have it in nice order.... or change it in config.yaml file.

[octoprint-systeminfo-20220523150456.zip](https://github.com/OctoPrint/OctoPrint/files/8754748/octoprint-systeminfo-20220523150456.zip)

**Comment by foosel** [comment]
1.9.0 has been released.
