### ISSUE TITLE
This version of the Python environment (3.7.5) is not supported for direct updates.

### ISSUE THREAD

**Issue by elpeter25** [OctoPrint/OctoPrint#4523]
### The problem

For the 1.8.1 version Python 3.7.5 I just installed for upgrading to 1.8.0 is not enough. Well I had to do a fresh install for the 1.8.0 with python 3.7 as I wasn't able to upgrade in any other way. I have a custom set up. Ubuntu on a NUC running multiple instances of octoprint.
Today I receive the following error:

This version of the Python environment is not supported for direct updates.

And I'm using latest Python 3.7 for ubuntu so... how is this even possible?

See screenshot bellow:
![2022-05-25 08_07_56-](https://user-images.githubusercontent.com/37652763/170192802-1b9d223f-e38b-4088-b148-2ea2f6782588.png)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.0

### Operating system running OctoPrint

Ubuntu 18.04.6 LTS

### Printer model & used firmware incl. version

N/A

### Browser and version of browser, operating system running browser

N/A

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220525082226.zip](https://github.com/OctoPrint/OctoPrint/files/8768437/octoprint-systeminfo-20220525082226.zip)

**Comment by cp2004** [comment]
When you open the software update settings, it should give you more details of what exactly is not up-to-date enough. It is not necessarily Python, it could be pip or setuptools as well.

**Comment by elpeter25** [comment]
Thanks for that, didn't know it :)

Now it's even better :P
![2022-05-25 09_16_03-0% 09_16 (operational)](https://user-images.githubusercontent.com/37652763/170203277-d1771065-1265-4a8f-9484-32e8d5bc9bc9.png)

**Comment by elpeter25** [comment]
Voilá! It worked :)

Thanks for pointing that out for me!!
![2022-05-25 09_20_48-0% - ()](https://user-images.githubusercontent.com/37652763/170204240-cd2c715a-626a-42e2-afa7-800ba3d7d3e9.png)

**Comment by cp2004** [comment]
👍
