### ISSUE TITLE
[Request] Show Material name for a GCode file in Octoprint

### ISSUE THREAD

**Issue by spanzetta** [OctoPrint/OctoPrint#4535]
### Describe the solution you'd like

Assuming that in Cura (or any other slicer) you have selected a Material before slicing your 3D file, I think it would be useful to show the Material name defined in the slicer.. so you can easily select the corresponding material in Octoprint before starting to print..

This is particularly useful when you use different materials (with different printing characteristics, like PLA vs PETG) and you have many different projects ..

**Comment by cp2004** [comment]
OctoPrint doesn't know what material you have selected in Cura, it is just reading the generated gcode file, it doesn't have a way of finding this information.

Some alternatives:
* There are plugins for Cura that will automatically put details about the file in the file name
* If Cura prints this information in the gcode file somewhere, or you can add it to the start gcode, then use [this plugin ExtraFileInfo](https://plugins.octoprint.org/plugins/extrafileinfo/) to add parsing for it and display it.
