### ISSUE TITLE
G02 or G03 are not interpreted as arcs in the gcodeviewer

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4582]
### The problem

G2 and G3 commands are correctly rendered as arcs, however G02 and G03 commands are not and just render as direct straight lines. Discovered while testing #4580 

### Contribution help

*This issue may be suitable for a first-time contributor to fix & test*

Check the parsing of movement commands to see why G02/G03 commands are ignored

https://github.com/OctoPrint/OctoPrint/blob/a2e9aefe9c8a51120931e9b14bb95ebf9ea6c7f5/src/octoprint/plugins/gcodeviewer/static/js/viewer/worker.js#L405-L487

### Additional information & file uploads

[octoprint-systeminfo-20220718155606.zip](https://github.com/OctoPrint/OctoPrint/files/9132967/octoprint-systeminfo-20220718155606.zip)

**Comment by kForth** [comment]
This seems to be a result of the following lines:

https://github.com/OctoPrint/OctoPrint/blob/a2e9aefe9c8a51120931e9b14bb95ebf9ea6c7f5/src/octoprint/plugins/gcodeviewer/static/js/viewer/worker.js#L482-L485

https://github.com/OctoPrint/OctoPrint/blob/a2e9aefe9c8a51120931e9b14bb95ebf9ea6c7f5/src/octoprint/plugins/gcodeviewer/static/js/viewer/renderer.js#L1074

The `.charAt(1)` in both checks will return `0` for `G02` and `G03` commands, meaning `direction` doesn't get set here and will be `undefined` when it's time to render.

I've created PR #4587 to fix this.

**Comment by foosel** [comment]
1.9.0 has been released.
