### ISSUE TITLE
[Request] Install plugin button is not obviously disabled 

### ISSUE THREAD

**Issue by iKrushYou** [OctoPrint/OctoPrint#4611]
### Describe the solution you'd like

i was trying to install a plugin for the first time and there is currently a print going

I did not notice the warning saying that plugin management will be disabled while printing right away and spent 5 or so minutes debugging, different browser, searching the internet, reading the HTML source only to finally see the warning and realize that the buttons are intentionally disabled. 

Can the buttons be made more obviously disabled? I suppose it's the theme's doing but the buttons look enabled to me 

Or, there should be a tooltip saying that it's disabled for x reason 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1500721/183275034-ca6ad45c-ebbe-4fa7-a531-3a2e7cd4de73.png">

**Comment by jneilliii** [comment]
This may be a moot point in a future release as plugin installs will be able to be queued similar to plugin/OctoPrint updates added in 1.8.0.

**Comment by cp2004** [comment]
Addressed with #4620
