### ISSUE TITLE
Whitespace not trimmed in username creation

### ISSUE THREAD

**Issue by TennisRunner** [OctoPrint/OctoPrint#4621]
### The problem

Created an account called "Admin ".
Now every time I log in, I have to include the empty space since it wasn't trimmed during the account creation process. 

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.1

### Operating system running OctoPrint

Android

### Printer model & used firmware incl. version

Ender 3

### Browser and version of browser, operating system running browser

Firefox or Chrome

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

Thats about it

**Comment by cp2004** [comment]
As the PR #4631 does - I don't think whitespace should be silently trimmed, but rather not accepted in the first place.

**Comment by foosel** [comment]
Agreed, and the input fields for creation in wizard and settings should reflect that accordingly by switching to error state if there's leading or trailing whitespace. Or whitespace in the first place.

**Comment by 040medien** [comment]
I updated my PR as per the suggested changes. I didn't disallow names with spaces in the middle, because this is not causing issues and seems like a valid use case, e.g. for "Firstname Lastname".

**Comment by foosel** [comment]
PR merged (thanks!), will be part of 1.9.0.
