### ISSUE TITLE
JS Client: onEventFileDeselected event is not executed if printer is disconnected

### ISSUE THREAD

**Issue by NilsRo** [OctoPrint/OctoPrint#4623]
### The problem

1. Like to show additional information for file selected in printerStateViewModel
2. Using onEventFileSelected and onEventFileDeselected to show/hide this information
3. onEventFileDeselected should be executed if no file is selected anymore but it is not fired anytime e.g. is a printer is disconnecting (but the file is not selected anymore...)
![image](https://user-images.githubusercontent.com/51311453/185318197-dfe136d1-799b-493e-9fb2-082f1a7e6542.png)

![image](https://user-images.githubusercontent.com/51311453/185318862-63bb95fe-bfb7-46a1-a452-64f35a2f5f45.png)
![image](https://user-images.githubusercontent.com/51311453/185319451-354e4e89-a4d3-476d-a378-4f69f29286a6.png)

PS. Perhaps my understanding of the documentation is wrong but my expectation is that the event should be fired every time a file is not selected anymore not not only of the user issued a deselection of a file directly...

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

My plugin is disabled then...

### Version of OctoPrint

1.8.1

### Operating system running OctoPrint

Windows 10

### Printer model & used firmware incl. version

Virtual Printer and Anycubic Mega S

### Browser and version of browser, operating system running browser

Firefox 103.0.2 (64-Bit)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[console-export-2022-8-18_8-52-34.txt](https://github.com/OctoPrint/OctoPrint/files/9368301/console-export-2022-8-18_8-52-34.txt)
[octoprint-systeminfo-20220818085348.zip](https://github.com/OctoPrint/OctoPrint/files/9368310/octoprint-systeminfo-20220818085348.zip)

**Comment by foosel** [comment]
I wasn't sure if that was a bug or rather a feature working differently than expected, but then came to the conclusion that yes, the way it's expected to work here by you definitely makes more sense than "this only fires if for some reason the file is actively deselected, for which there exists no UI and which can only happen in rare cases" 😅

So this is now fixed for 1.9.0.
