### ISSUE TITLE
Flip webcam on HLS camera causes some Web UI to become not interactable.

### ISSUE THREAD

**Issue by pawelkw** [OctoPrint/OctoPrint#4640]
### The problem

Using the webcam feature with the following settings.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1320997/189477985-ab28e90a-b037-4669-baa2-e6d385402092.png">
Causes this:
![image](https://user-images.githubusercontent.com/1320997/189478008-9b2efd27-cc41-47c4-a856-ef71754edc1d.png)
Elements obscured by this transparent HTML element are not clickable (so you can't access Temperature, Terminal, Settings, Power, etc). Deleting the associated tag and it's `<div>` parents manually in the browser dev mode resolves it. 

Tested browsers:
Safari: 15.5 (17613.2.7.1.8)
Firefox: 105.0b9 (64-bit

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

OctoPrint 1.8.2 Python 3.8.13 

### Operating system running OctoPrint

Ubuntu Server

### Printer model & used firmware incl. version

n/a

### Browser and version of browser, operating system running browser

Firefox 105.0b9 (64-bit), MacOS 12.4

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20220910093941.zip](https://github.com/OctoPrint/OctoPrint/files/9539967/octoprint-systeminfo-20220910093941.zip)

**Comment by foosel** [comment]
@botflakes that doesn't sound like the same issue, and also like something you should rather report to the octolapse issue tracker.

**Comment by botflakes** [comment]
@foosel Octolapse was just an example. Same thing happens with every other plugin. The only "popup" menu that loads normally is the Settingsmenu from OctoPrint and the Notificationcenter

**Comment by foosel** [comment]
@botflakes Do you have the webcam flipped and rotated as stated by OP? If yes, then please test safe mode, if it persists provide a full system info bundle like OP. If you don't have the camera flipped/rotated this is not the same issue. If it vanishes in safe mode it's caused by a plugin.

**Comment by botflakes** [comment]
Will test when the Print is done. I'll keep you updated

**Comment by foosel** [comment]
@pawelkw After not being able to reproduce with MJPG I saw you have this happening with an HLS source. Can you please test if setting `https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8` as your webcam URL allows you to reproduce this? Because for me it doesn't.

**Comment by pawelkw** [comment]
@foosel 
<img width="1728" alt="Screenshot 2022-09-15 at 09 55 49" src="https://user-images.githubusercontent.com/1320997/190348160-e6dc93d2-e436-4355-9ab6-cbdc05a61152.png">

At first it worked correctly, right after setting it (including not blocking UI element). Then after a few reloads it doesn't stream anymore - black screen as you see here + the original bug is back (UI elements blocked as you see on the screenshot).

**Comment by foosel** [comment]
I cannot reproduce this against 1.9.0.dev, no matter how often I reload. Webcam integration in 1.9.0 has been extracted into a plugin however, so maybe that automatically fixed it. I'll tag this as fixed for now, but with `needs testing`. Please, once 1.9.0rc1 hits, test this again on your end. If you can still reproduce it, we'd need to take a second look at this.

**Comment by foosel** [comment]
1.9.0 has been released.
