### ISSUE TITLE
Event

### ISSUE THREAD

**Issue by fly74** [OctoPrint/OctoPrint#4660]
### Is your feature request related to a problem? Please describe.

Hello developers,

is there an event in eventmanager to fire at (x) percent of the actual print?

Greetings.

### Describe the solution you'd like

event PrintPercent

### Describe alternatives you've considered

Plugin OctoText, but it is only for mailing.

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs and feature requests. See also the [Contribution Guidelines](https://github.com/OctoPrint/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
