### ISSUE TITLE
[Request] "File Already Exists" dialogue - Add information on old/new files

### ISSUE THREAD

**Issue by Clumpton** [OctoPrint/OctoPrint#4681]
### Is your feature request related to a problem? Please describe.

When you upload a gcode file to Octoprint and a file of the same name is already present a "File Already Exists" dialogue is show offering  to Cancel, Rename or Overwrite it. (see screenshot)
![file exists dialogue](https://user-images.githubusercontent.com/59048696/200374800-88f7138f-aab9-4116-b7d7-46487cfdef38.jpg)
There is no indication of the age, size or upload date/time of the pre-existing file, this could lead to confusion or loss of a precious gcode file.

### Describe the solution you'd like

The "File Already Exists" dialogue would show additional file information to help decide whether it is safe to overwrite.
For example:
**Existing file foobar.gcode:**
- Size 250 kb
- Date 2021-12-25 15:35:20
- Uploaded 3 weeks ago

**New file foobar.gcode:**
- Size 721 kb
- Date 2022-1107 18:30

### Describe alternatives you've considered

I've considered being more careful and remembering old files, but I'm a wrinkly and my memory fails me :-)

**Comment by max246** [comment]
I have made a PR for this https://github.com/OctoPrint/OctoPrint/pull/4720

**Comment by Clumpton** [comment]
> I have made a PR for this #4720

Thanks for that!

**Comment by foosel** [comment]
Implemented by #4721, will be in 1.10.0

**Comment by Clumpton** [comment]
Thanks for that 

⁣Get TypeApp for Android ​

**Comment by foosel** [comment]
1.10.0 has been released.

**Comment by Clumpton** [comment]
Nice implementation, thanks again.
