### ISSUE TITLE
[Request] Warn users about missing `wheel` package

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4682]
### Is your feature request related to a problem? Please describe.

A new warning has popped up in pip:

https://github.com/pypa/pip/issues/8559

Basically every plugin uses setup.py (and there's work to be done to switch that to pyproject.toml at some point here), and while the vast majority probably have the wheel package, maybe some don't. To avoid potential issues installing plugins/updates in the future, I wonder if a warning could be added to the SW update page or plugin manager gently mentioning that wheel is not installed. I don't think an intrusive warning is necessary here just yet, but it might preempt some issues?

### Describe the solution you'd like

err... I got carried away in the previous box.

### Describe alternatives you've considered

Suffering with support questions?

### Additional context

See linked issue, and also #4552 for the pyproject.toml stuff.

**Comment by foosel** [comment]
Makes sense. Also reading through the linked pip issue, isolated builds will become the norm, so #4552 just got a huge priority boost.

**Comment by foosel** [comment]
Hm... should we maybe just make `wheel` part of OctoPrint's requirements? Then it should get installed automatically if it's currently missing for whatever reason.

**Comment by cp2004** [comment]
That does make more sense than a warning, yeah!

**Comment by foosel** [comment]
`wheel` is now part of OctoPrint's requirements. For now without a version pin.
