### ISSUE TITLE
Octoprint "drop to upload file" when switching to firefox window

### ISSUE THREAD

**Issue by mashuptwice** [OctoPrint/OctoPrint#4683]
### The problem

1. open octoprint in firefox
2. leave tab open and switch to a different window
3. switch back to firefox
4. octoprint opens "drop to upload file" without a file dragged

![Screenshot_20221109_195029](https://user-images.githubusercontent.com/54219098/200918996-745ba7ff-4bcb-4e37-9b09-457fee360d38.png)

https://user-images.githubusercontent.com/54219098/200918904-5c603cce-0ac9-4c14-8b18-5b4b9f6ed37c.mp4

**Notes:**

The issue does not occur if the tab was not visible and I switch to octoprint from within firefox. 

It might be worth noting that I am using octoprint on a thinkpad convertible, I could imagine the touchscreen or wacom AES being misinterpreted. 

It happens regardless of the mouse pointer and previous touch or stylus position. 

Does not happen with other browsers. 

### Did the issue persist even in safe mode?

YES, it does. 

### Version of OctoPrint

1.8.6

### Operating system running OctoPrint

Raspberry 3B+, Debian/Raspberry OS kernel 5.10.103-v7+, used Octopi image

### Printer model & used firmware incl. version

MKS Tinybee, Marlin

### Browser and version of browser, operating system running browser

Mozilla Firefox 106.0.5, 6.0.7-arch1-1 KDE Wayland, plasmashell 5.26.3

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

~~Does not occur when developer tools / javascript console is open.~~ It does happen.
Console shows no new entry when the issue occurs.
Console content:

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
HTTP “Content-Type” of “text/html” is not supported. Load of media resource https://10.0.0.20/? failed. 2 [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
Cannot play media. No decoders for requested formats: text/html, text/html [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
Starting dependency resolution... [packed_core.js:1305:521](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Calling OctoPrintClient.getRequestHeaders with additional headers as the first parameter is deprecated. Please consult the docs about the current signature and adjust your code accordingly. [packed_client.js:8:467](https://10.0.0.20/static/webassets/packed_client.js?e6252517)
... dependency resolution done [packed_core.js:1318:5](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Initial application setup done, connecting to server... [packed_core.js:1341:867](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Connected to the server [packed_core.js:1136:456](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Triggering connect on all view models [packed_core.js:1141:240](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Server (re)connect processed [packed_core.js:1143:5](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Finalizing application startup [packed_core.js:1341:243](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
The resource at “https://10.0.0.20/static/vendor/font-awesome-5.15.1/webfonts/fa-brands-400.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
The resource at “https://10.0.0.20/static/vendor/font-awesome-5.15.1/webfonts/fa-regular-400.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
The resource at “https://10.0.0.20/static/vendor/font-awesome-5.15.1/webfonts/fa-solid-900.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
The resource at “https://10.0.0.20/static/vendor/font-awesome-3.2.1/fonts/fontawesome-webfont.woff” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
Going to bind 48 view models... [packed_core.js:1322:39](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Did not bind view model BackupViewModel to target #wizard_plugin_backup since it does not exist [packed_core.js:1334:44](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Did not bind view model UsageViewModel to target #wizard_plugin_tracking since it does not exist [packed_core.js:1334:44](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Did not bind view model SoftwareUpdateViewModel to target #softwareupdate_confirmation_dialog since it does not exist [packed_core.js:1334:44](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate_update since it does not exist [packed_core.js:1334:44](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate_settings since it does not exist [packed_core.js:1334:44](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Use of Mutation Events is deprecated. Use MutationObserver instead. [packed_plugins.js:241:148031](https://10.0.0.20/static/webassets/packed_plugins.js?524ef4d1)
User mashuptwice logged in [packed_core.js:229:614](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Login mechanism: http [packed_core.js:234:35](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
... binding done [packed_core.js:1339:150](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Application startup complete [packed_core.js:1339:442](https://10.0.0.20/static/webassets/packed_core.js?389582e5)
Error: Promised response from onMessage listener went out of scope [ExtensionMessagingService.js:89:34](moz-extension://070f0d9b-d5d5-4f1e-9210-57df9395ebe9/scripts/services/ExtensionMessagingService.js)
HTTP “Content-Type” of “text/html” is not supported. Load of media resource https://10.0.0.20/? failed. 2 [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
Cannot play media. No decoders for requested formats: text/html, text/html [10.0.0.20](https://10.0.0.20/?#tab_plugin_dashboard)
```
The last two lines look suspicious, but appear right after loading the page and way before triggering the issue. 
[octoprint-systeminfo-20221109201336.zip](https://github.com/OctoPrint/OctoPrint/files/9974401/octoprint-systeminfo-20221109201336.zip)

**Comment by jneilliii** [comment]
are you using keyboard shortcuts for switching applications, wasn't clear from the video.

**Comment by jneilliii** [comment]
I just tested firefox 106.0.5 (64-bit) on windows and cannot reproduce this issue. tried both switching using the task bar and shortcut keys. I do know that if you have text selected and move the mouse on the page it will also show that drop overlay, so I'm wondering if that's what's happening here for you with the waacom, etc.?

**Comment by mashuptwice** [comment]
@jneilliii it happens both with with keyboard shortcuts, as well as when clicking on the task bar. 

What do you mean by text selected? Like select and drag it into the open window, just selected or selected and copied to the clipboard?

**Comment by mashuptwice** [comment]
Welp, I've just experienced the same on google search results. This might be an upstream thing then!

Tested Mozilla Firefox 106.0.3, the issue does not occur in this version. 

Upgraded to Mozilla Firefox 106.0.5 again, the issue does not occur! 

Closing this as not reproducible.

**Comment by mashuptwice** [comment]
I'll reopen this issue, as it keeps happening. Downgrading to different Firefox versions did not help.

**Comment by foosel** [comment]
Cannot reproduce this either. I use Firefox as my main browser myself. It might be a touchscreen issue, however I don't have access to one anymore. So that's going to need someone to look at who can reproduce this I fear.

**Comment by mashuptwice** [comment]
Narrowed it down, it is an [upstream KDE bug.](https://bugs.kde.org/show_bug.cgi?id=446111)
