### ISSUE TITLE
Chrome displays "Out of memory" -error when using cam

### ISSUE THREAD

**Issue by asdasddffgthhjtreresf** [OctoPrint/OctoPrint#4684]
### The problem

Latest release of octoprint shows Aw, Snap! Something went wrong while displaying this webpage. Error code: Our of memory
This happens when using Control -tab with cam. 

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

I have long print going on so can't test safe mode.

### Version of OctoPrint

1.8.6

### Operating system running OctoPrint

The ready-to-go Raspberry Pi image with OctoPrint Version 0.18.0

### Browser and version of browser, operating system running browser

Chrome Version 107.0.5304.107 (Official Build) (64-bit)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20221112015323.zip](https://github.com/OctoPrint/OctoPrint/files/9993688/octoprint-systeminfo-20221112015323.zip)

**Comment by foosel** [comment]
> I have long print going on so can't test safe mode.

Cool, then please test in safe mode once that print is done and then report back here.

**Comment by cp2004** [comment]
@asdasddffgthhjtreresf did you ever get a chance to test this again? Are you using the standard mjpg streaming, or experimental HLS/WebRTC?

**Comment by ReverendRhyme** [comment]
My Octo is also unusable all of a sudden while printing. If I'm not printing it runs great.

You cannot navigate through the interface without massive lag. 

Eventually resulting in an "out of memory" error. This happens in Chrome and Edge. Both are using the latest version.

**Comment by cp2004** [comment]
@ReverendRhyme, are you perhaps able to pick up the unanswered question here, of testing it in safe mode? And this error only happens when the webcam is being shown, yes?

**Comment by ReverendRhyme** [comment]
> 
I'll see If I can reproduce in Safemode once my print is done. It only crashes out while printing with the cam shown. I can have the camera view online while no print is going, and everything works as you would expect.

**Comment by ReverendRhyme** [comment]
Well, everything seems ok in Safemode. So one of the plugins must be responsible.

**Comment by cp2004** [comment]
That does make it most likely a plugin issue. If you find out which plugin it is, please let us know in case someone else comes across this, and it can be reported to the plugin author as an issue. Unless @asdasddffgthhjtreresf ever replies, this issue can probably be closed soon.

**Comment by foosel** [comment]
Closing due to lack of response.

**Comment by 3DStreetFurniture** [comment]
I get the same and can test this for you @foosel 
![image](https://github.com/OctoPrint/OctoPrint/assets/110367979/505fca72-64c2-4660-b9b5-8dc3e529b4a0)
