### ISSUE TITLE
Modernize versioneer or maybe even replace it?

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint#4685]
### The problem

OctoPrint currently uses an ancient & heavily adjusted [versioneer](https://github.com/python-versioneer/python-versioneer) build that is [bundled](https://github.com/OctoPrint/OctoPrint/blob/master/versioneer.py).

That version of versioneer only supports setuptools, which long term will cause problems in switching OctoPrint to `pyproject.toml` (at some point `setup.py` will either go away or at the very least become increasingly more difficult to cater to, `pyproject.toml` based build configurations are what pip is currently pushing towards).

### The solution

There are three options I currently see:

1. Update versioneer to the latest release, which supports `pyproject.toml` as well as `setup.py`. However, our customization with `.versioneer-lookup` that basically creates virtual tags to use for version generation based on the currently checked-out branch is not available in that. That would have to be ported if we want to keep our current branching scheme.

2. Update versioneer and switch to the use of _release branches_ instead of `.versioneer-lookup`. We would no longer have `maintenance` and `devel` but rather something like `1.9.0` and `2.0.0` as development branches for the respective version. It might even make sense to stop supporting installing stable OctoPrint directly from `master` and instead use that as bugfix prep branch for the latest tag. 

3. Like 2, but switching to PyPA's own `setuptools_scm`.

For reference:

  - [versioneer](https://github.com/python-versioneer/python-versioneer)
  - [setuptools_scm](https://github.com/pypa/setuptools_scm)

I'm honestly currently not sure which of the options I prefer.

**Comment by cp2004** [comment]
To add to this issue - OctoPrint almost works under Python 3.12, but versioneer uses `SafeConfigParser` which has been deprecated for a while & removed in 3.12. (At least that's going off the top of my head).

It's easily fixable, but it means that the pip install process is no longer Python 2 compatible so you don't get the nice error message. Some more advanced error handling could probably make it work, I remember having a poke before. At some point we will have to jump ship there I guess, it is widely known that OctoPrint isn't Py2 compatible anymore but there are still some people running older versions that it would be nice to not have them start saying updating/installing is broken.

**Comment by foosel** [comment]
The `SafeConfigParser` issue has been fixed in a922ff8973a08f9c5f4617dbdaf91cfb04b387d9, so that's no longer in the way for Python 3.12.

Meanwhile I still have not made a decision on which way to go here.

**Comment by foosel** [comment]
In the end I decided to replace it with a small tool. Enter [`_version.py` now living in the source tree](https://github.com/OctoPrint/OctoPrint/blob/maintenance/src/octoprint/_version.py), heavily influenced by [miniver](https://github.com/jbweston/miniver) but adjusted to allow the use of virtual tags. It *should* result in pretty much the same versioning behaviour as versioneer so far did, but of course I might have overlooked some corner cases. We'll see.
