### ISSUE TITLE
api POST request body chunked transfer-encoding is empty at endpoint

### ISSUE THREAD

**Issue by msrasheed** [OctoPrint/OctoPrint#4688]
### The problem

I am trying to make a call to the `/api/login` endpoint as a POST request, chunked transfer encoding. 
See the following code for an example.
```python
import json
import requests

ip = "10.0.1.67"
api_key = "<api_key>"

def gen():
    yield bytes(json.dumps({"passive": True}), 'utf-8')

resp = requests.post(f'http://{ip}:5000/api/login', headers={
  "X-Api-Key": api_key, 
  "Content-Type": "application/json"}, 
  data=gen())
print(resp.content)
```
Returns a 404 error saying 
```json
{"error":"The browser (or proxy) sent a request that this server could not understand."}
```

After debugging for a bit, this can be remedied by removing the `Trasnfer-Encoding` header before sending it to the WSGI entrypoint for flask. Otherwise there is no data to parse when [`request.get_json()`](https://github.com/OctoPrint/OctoPrint/blob/7659c811f5ac9bc01a3d07662a056968fa0db426/src/octoprint/server/api/__init__.py#L294) executes and it throws the error.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.6

### Operating system running OctoPrint

Linux 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20221201175948.zip](https://github.com/OctoPrint/OctoPrint/files/10135003/octoprint-systeminfo-20221201175948.zip)

**Comment by foosel** [comment]
PR #4689 fixing this has been merged (thanks!), fix will be in 1.9.0.
