### ISSUE TITLE
The temperature offset does not work

### ISSUE THREAD

**Issue by MarshMalloW0007** [OctoPrint/OctoPrint#4695]
### The problem

In my code, for the first layer, the temperature of the nozzle is 185°C and for the bed 10°C.
For the following layers, the temperature of the nozzle is 180°C and for the bed 5°C.
I put the offset at 40 to obtain 225/50° C for the first layer and 220/45° C for the other layers.

The preheating phase goes well and the temperatures are respected.
![01](https://user-images.githubusercontent.com/45604136/208252440-38306443-c7f0-4013-8c67-c21638310ec7.jpg)

During the printing of the first layer, the temperature of the nozzle goes down to that of the gcode, 185° C and goes up again to 220° C starting from the second layer.
![02](https://user-images.githubusercontent.com/45604136/208252454-b7f5c8f0-d4c5-4260-b8f0-974e17ea502c.jpg)
![03](https://user-images.githubusercontent.com/45604136/208252470-0946c22b-2028-40ef-ba33-65c63add4d07.jpg)
![04](https://user-images.githubusercontent.com/45604136/208252498-a4ab942d-b209-4ec4-9805-8afcc871966b.jpg)

The temperature of the bed is not impacted by this "bug".
![05](https://user-images.githubusercontent.com/45604136/208252506-b56988db-6936-491f-8417-a1289c3aeae0.jpg)

I tested on two installations of Octopi and the screenshots are made with the virtual printer

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

OctoPrint 1.8.6 

### Operating system running OctoPrint

OctoPi 1.0.0

### Printer model & used firmware incl. version

Tevo Tornado 1.1.19 and VIRTUAL Printer of OctoPrint

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20221217175659.zip](https://github.com/OctoPrint/OctoPrint/files/10252218/octoprint-systeminfo-20221217175659.zip)
[ForChoiceFilament-OS185_10-gcode.zip](https://github.com/OctoPrint/OctoPrint/files/10252219/ForChoiceFilament-OS185_10-gcode.zip)

**Comment by cp2004** [comment]
Can confirm, it is triggered because you have `M109 R185` in your gcode and it doesn't look like OctoPrint's offsets support this gcode. You have both these commands in your start gcode which is unnecessary as they do the same thing for heating up:

```
M109 S185 
M109 R185
```
Just using M109 S185 would do the same thing and avoid the issue of the temperature offset not being applied.

**Comment by cp2004** [comment]
PR #4696 addresses this issue.
