### ISSUE TITLE
[Request] display Z position in status box

### ISSUE THREAD

**Issue by oregszun** [OctoPrint/OctoPrint#4715]
### Is your feature request related to a problem? Please describe.

To check the Z posiotion of the extruder I need to check the terminal, where hard to find due the huge amount of lines sent per secs.

### Describe the solution you'd like

Put the Z position in the status box. E.g. Z position: 12.20mm beside the progress percentage.

### Describe alternatives you've considered

Display the Z position somewhere (control, terminal, etc.)

**Comment by foosel** [comment]
There's a plugin for that: https://plugins.octoprint.org/plugins/displayz/
