### ISSUE TITLE
Unable to detect/connect to printer

### ISSUE THREAD

**Issue by tx3m** [OctoPrint/OctoPrint#4718]
### The problem

1. Octoprint running
2. Power-up printer
3. Try to connect
4. Connection failed, see logs
5. 
[octoprint-systeminfo-20230127115144.zip](https://github.com/OctoPrint/OctoPrint/files/10518525/octoprint-systeminfo-20230127115144.zip)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

Version 1.8.6

### Operating system running OctoPrint

Windows

### Printer model & used firmware incl. version

Longer LK4 Pro with Marlin 2

### Browser and version of browser, operating system running browser

Firefox

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by cp2004** [comment]
This issue tracker is for bugs & feature requests for OctoPrint. For help and support in using OctoPrint, plugins, your printer and your general setup please get in touch on the [community forums](https://community.octoprint.org) or the [discord server](https://discord.octoprint.org) - there are helpful people are around that can answer your questions.
