### ISSUE TITLE
on_file_upload hook sometimes starts with a slash with e.g. arc welder plugin 

### ISSUE THREAD

**Issue by NilsRo** [OctoPrint/OctoPrint#4719]
### The problem

If a file is copied by arc welder plugin it correctly runs through all hooks again. But on_file_upload hook (and perhaps some else) contains a / in the beginning which is dropped in later events. Also this is not the common behavior uploading through the GUI or API with e.g. Cura.

```
    # Hook after file upload for pre-processing
    def on_file_upload(self, path, file_object, links=None, printer_profile=None, allow_overwrite=True, *args, **kwargs):
        cleaned_path = str(path).lstrip("/")
        self._filedata[cleaned_path] = filedata
        ...
```

As a result there was an issue with the handling between the events if some information was stored on the path used. So as the path looses the / later I have to cleanse it manually to have it aligned in my plugin.

For plugins in general it would be helpful if the path is cleaned to show the same format in every event.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

Plugins not running, but its related to OctoPrints API

### Version of OctoPrint

1.8.6

### Operating system running OctoPrint

Windows & Linux

### Printer model & used firmware incl. version

Anycubic Mega S

### Browser and version of browser, operating system running browser

Opera 94.0.4606.76, Windows 11 x64

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20230128230418.zip](https://github.com/OctoPrint/OctoPrint/files/10528388/octoprint-systeminfo-20230128230418.zip)

From development system but it is the same with actual OctoPI instance in use.

![image](https://user-images.githubusercontent.com/51311453/215293139-bbe4701a-8694-460f-a64d-d71eb025a80d.png)

**Comment by foosel** [comment]
This took a while to understand and get around to, but I now pushed some changes that should hopefully solve this on all file manager methods and normalize paths in hooks and events to those without leading `/`.

Some testing with various plugins and workflows would be good though.
