### ISSUE TITLE
Print quality via Octoprint significantly worse than directly from SD-Card - Ender-5 S1

### ISSUE THREAD

**Issue by TomMuc1** [OctoPrint/OctoPrint#4734]
### The problem

print quality via octoprint (usb-c) significantly worse than directly from sd-card with exactly the same g-code file.
this is not only the case with the attached example file but with every file.

to be honest i have no idea how something like this is even possible since the raspi here is actually just a big usb-c connected sd-card

-> raspberry pi 4 model b rev 1.2 2gb
-> octopi installation via raspberry imager
-> no time lapse or similar active

### Did the issue persist even in safe mode?

yes - checked it now - same problem in safe mode

### If you could not test in safe mode, please state why

now tested - see above

### Version of OctoPrint

OctoPrint 1.8.6 Python 3.7.3 OctoPi 0.18.0

### Operating system running OctoPrint

raspbian buster

### Printer model & used firmware incl. version

creality ender-5 s1 /  fw 1.0.5z

### Browser and version of browser, operating system running browser

safari macos 13.2.1

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [x] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [x] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20230216225509.zip](https://github.com/OctoPrint/OctoPrint/files/10761282/octoprint-systeminfo-20230216225509.zip)
[E5 S1-rabbit.gcode.zip](https://github.com/OctoPrint/OctoPrint/files/10761289/E5.S1-rabbit.gcode.zip)
![left-octo_right-sdcard](https://user-images.githubusercontent.com/31601862/219496885-2a297798-4768-4db1-a209-39f082c073b0.jpg)

**Comment by wakeupcairo** [comment]
any update abut this bug?

**Comment by Sveeeeeen** [comment]
Facing the same issue, but my Raspi 4 B has 8GB of ram.

**Comment by foosel** [comment]
If you are still seeing this against current versions, then please enable [`serial.log`](https://faq.octoprint.org/serial-log), reproduce the issue, create another system info bundle and attach it here. Stuttering and quality issues can be rooted in communication issues, and sadly your provided logs don't contain any serial output to check for issues like that.

**Comment by foosel** [comment]
Closing due to lack of response.
