### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Jama85** [OctoPrint/OctoPrint#4745]
### Describe the solution you'd like

Hello

is it possible to add onvif support?

**Comment by foosel** [comment]
For questions or other kind of help or support, please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
