### ISSUE TITLE
Temperature graph legend is "minutes since round number" ( -3 -8 -13  changes to -4 -9 -14...)

### ISSUE THREAD

**Issue by disconn3ct** [OctoPrint/OctoPrint#4747]
### The problem

The temperature graph legend is "since a round number". At 15:43, the legend starts with "-3" (15:40) but has no other relation to wall time.

This graph should have a static legend of 0, -5, -10... with the preheat change moving left. The legend itself should not change:
![image](https://user-images.githubusercontent.com/397465/223226300-322f2de1-2a4a-4640-ae6b-ed14a5298efe.png)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.7

### Operating system running OctoPrint

Octopi 1.0.0

### Printer model & used firmware incl. version

MKS3+

### Browser and version of browser, operating system running browser

Chromium, PopOs

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by foosel** [comment]
This is now implemented by the above commit:

![image](https://github.com/OctoPrint/OctoPrint/assets/83657/42505ba3-bba8-47f6-8dcb-faa561528e14)

Will be part of 1.10.0

**Comment by foosel** [comment]
1.10.0 has been released.

**Comment by disconn3ct** [comment]
A quick look says this is fixed. Thanks!
