### ISSUE TITLE
[1.9.0rc2] 500 Internal Server Error

### ISSUE THREAD

**Issue by JoGrob** [OctoPrint/OctoPrint#4763]
### What is the problem?

Octoprint does not properly start up. octopi.local gives "500 Internal Server Error"
with redirected url
http://octopi.local/login/?redirect=%2F%3F&permissions=STATUS,SETTINGS_READ

Maybe this is causes by deleting the cookies in webbrowser, so autologin can't remeber webbrowser???

### What did you already try to solve it?

i've tried booting octopi several times.
I've tried several webbrowsers Edge and Firefox.

### Have you tried running in safe mode?

can't get in save mode.

### Did running in safe mode solve the problem?

n/a

### Systeminfo Bundle

can't download

### Additional information about your setup

octoprint.log shows some ERROR Exception on /login/ [GET]

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

can't enter gui

### Version of OctoPrint

1.9.0rc2

### Operating system running OctoPrint

octopi 1.0.0

### Checklist of files to include below

- [ ] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint.log](https://github.com/OctoPrint/OctoPrint/files/10969126/octoprint.log)

**Comment by foosel** [comment]
Fix ready for 1.9.0rc3

**Comment by foosel** [comment]
1.9.0rc3 is out.
