### ISSUE TITLE
Typo in German language: Model vs Modell

### ISSUE THREAD

**Issue by JoGrob** [OctoPrint/OctoPrint#4769]
### The problem

There are some typos in German language translation.
Wrong: Model
Right: Modell

See example in "GCode Viewer"
![Model_vs_Modell](https://user-images.githubusercontent.com/59739587/226622294-7a58bc00-4d91-4352-b1ca-b730ae7583c3.png)

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.0rc2

### Operating system running OctoPrint

OctoPi 1.0.0

### Printer model & used firmware incl. version

n/a

### Browser and version of browser, operating system running browser

n/a

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads
[octoprint-systeminfo-20230321143329.zip](https://github.com/OctoPrint/OctoPrint/files/11028877/octoprint-systeminfo-20230321143329.zip)

**Comment by foosel** [comment]
1.10.0 has been released.
