### ISSUE TITLE
cura settings editor from within octoprint

### ISSUE THREAD

**Issue by qharley** [OctoPrint/OctoPrint#477]
I like the new cura integration.... a lot! ;-)

Currently have to change the configfiles manually for different print configurations.
It is working for me, but confusing the living daylights out of everyone else

1) normal user should be able to select one of a set of preconfigured configs at print time, with mouse over info (layer, support etc)
2) power users should be able to create new config files for normal users to use

I know some if this might be planned already.

**Comment by george-vieira** [comment]
This is pretty old and still open, is this implemented somewhere? I can't see anything anywhere atm
