### ISSUE TITLE
[1.9.0rc3] Typo in new webcam visibility API

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4776]
### The problem

Testing out creating a webcam plugin and using the new API to enable it when visible.

It is looking for `onWebcamVisbilityChange`, but this should be `onWebcamVisibilityChange`:

https://github.com/OctoPrint/OctoPrint/blob/ed798e4c6f473ed15bfd8ff583f3913b18ab716c/src/octoprint/static/js/app/viewmodels/control.js#L69-L75

`visbility` -> `visibility` is the correct spelling. Baffled me for a second as to why it was complaining it couldn't find the function, then I read it very carefully and spotted this.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.0rc3

### Operating system running OctoPrint

OctoPi 1.0.0

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by foosel** [comment]
Ouch, well spotted, that could have become a new "Referer" incident. Fix ready for 1.9.0rc4
