### ISSUE TITLE
[1.9.0rc3] Typo in classic webcam snapshot hook

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4782]
### The problem

The below setting looks a bit... mixed up

https://github.com/OctoPrint/OctoPrint/blob/ed798e4c6f473ed15bfd8ff583f3913b18ab716c/src/octoprint/plugins/classicwebcam/__init__.py#L137

`rosnapshotSslValidationtate90` ➡️  `snapshotSslValidation`

I'll send in a PR

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.0rc3

### Operating system running OctoPrint

All

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by foosel** [comment]
Fixed in #4785

**Comment by foosel** [comment]
1.9.0rc4 has been released.
