### ISSUE TITLE
Octoprint Will not update

### ISSUE THREAD

**Issue by clementdumet** [OctoPrint/OctoPrint#4786]
### The problem

Whenever I try to update my Octoprint it throws an error.
Below I have attached the log files from this occurrence.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.2

### Operating system running OctoPrint

Docker Container on Raspberry Pi

### Printer model & used firmware incl. version

Prusa Mini Latest

### Browser and version of browser, operating system running browser

Google Chrome Latest

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[plugin_softwareupdate_console.log](https://github.com/OctoPrint/OctoPrint/files/11154618/plugin_softwareupdate_console.log)
[octoprint (1).log](https://github.com/OctoPrint/OctoPrint/files/11154619/octoprint.1.log)
[octoprint-systeminfo-20230405022331.zip](https://github.com/OctoPrint/OctoPrint/files/11154620/octoprint-systeminfo-20230405022331.zip)

**Comment by cp2004** [comment]
This kind of issue is best placed on the [community forums](https://community.octoprint.org) or discord(https://discord.octoprint.org) server, where there are a lot more people who might be able to help you. There are only limited eyes on the issue tracker & so for help fixing this error and getting OctoPrint updated, please post there.

I suspect you might need to pull an updated version of the container - I'm not completely sure on your setup, but it looks like you need https://github.com/OctoPrint/octoprint-docker/pull/236. Anyway, someone from the community would hopefully be able to help you through that.
