### ISSUE TITLE
Webcam stream unavailable in Docker, due to the Stream-URL missing

### ISSUE THREAD

**Issue by MaWalla** [OctoPrint/OctoPrint#4788]
### The problem

The webcam stream is not working on a fresh setup with Docker and port mapping. Manually setting the Stream-URL to `/webcam/?action=stream` solves that issue, but I think the expected behavior is to have it work out-of-the-box.

Meanwhile the Octoprint App provides a rather strange value, where IP and port seem to be merged (the IP is 192.168.2.8 and the port is 82):
![octoprint-app](https://user-images.githubusercontent.com/50621495/230905917-d19dc679-12da-480e-856b-118a9895e233.png)

I first thought the issue is related to the instance having its port mapped from 80 to 82, but the issue persists with octoprint exposed on port 80 as well

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.8.7

### Operating system running OctoPrint

Debian 11 (with Docker)

### Browser and version of browser, operating system running browser

Firefox 111.0.1 on Linux

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20230410123037.zip](https://github.com/OctoPrint/OctoPrint/files/11190471/octoprint-systeminfo-20230410123037.zip)
![2023-04-10_14-34](https://user-images.githubusercontent.com/50621495/230902393-364171f0-0f32-4bf9-950b-754db5538e9e.png)

(while I'm using the Dark Reader browser plugin, to have the page in dark mode, it also occurs without it)

**Comment by cp2004** [comment]
The docker container (assuming the one you used is https://github.com/OctoPrint/octoprint-docker) should have this configured by default & last time I checked does, but maybe it can be broken sometimes. Please send the issue there - OctoPrint itself has no default streaming provider so it doesn't make sense to have this configured by default for all users of OctoPrint when it is specific to the docker setup. The docker container provides the mjpg-streamer setup, so this is an issue with that instead.

> Meanwhile the Octoprint App

There is no 'OctoPrint App', OctoPrint only has a UI accessed via your browser. All other mobile apps etc. are 3rd party projects and so please direct this query to whichever app you have installed & are using.
