### ISSUE TITLE
[1.9.0rc4] Webcam view doesn't work if only 1 webcam plugin is available

### ISSUE THREAD

**Issue by r3Fuze** [OctoPrint/OctoPrint#4791]
### The problem

The webcam view in the control tab does not work if only 1 webcam source is available (Classic Webcam)

The view is just a black square with no option to pick a webcam source when hovering.

Pressing the "test" buttons in the Classic Webcam plugin settings works fine.

Installing another webcam plugin makes the Classic Webcam work as well as the new plugin. I only tested with [OctoPrint-Testpicture](https://github.com/OctoPrint/OctoPrint-Testpicture)

Disabling the new plugin and restarting stops the Classic Webcam view from working again.

I couldn't verify if installing another webcam plugin in safe mode works since safe mode disables third party plugins.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.0rc4

### Operating system running OctoPrint

OctoPi 0.17.0

### Browser and version of browser, operating system running browser

Firefox 112, Chrome 112, Windows 10

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20230412162142.zip](https://github.com/OctoPrint/OctoPrint/files/11212453/octoprint-systeminfo-20230412162142.zip)
[firefox-console-export-2023-4-12_16-22-30.txt](https://github.com/OctoPrint/OctoPrint/files/11212455/firefox-console-export-2023-4-12_16-22-30.txt)
![Screenshot 2023-04-12 162355](https://user-images.githubusercontent.com/840291/231488269-cce0fc7b-19ec-49db-b0ab-d4090e6bae40.png)
![Screenshot 2023-04-12 162523](https://user-images.githubusercontent.com/840291/231488634-2947a1d5-9fd7-4500-831c-3627ce88bdb6.png)
![Screenshot 2023-04-12 162731](https://user-images.githubusercontent.com/840291/231489345-c1babea1-1c74-485b-991c-187fbcfa2444.png)

**Comment by mild-lemon** [comment]
same problem here, browser Firefox 112.0 on OSX.
running 1.9.0rc4 on OctoPi
this is a **regression** wrt 1.9.0rc3

**Comment by LightningShark25** [comment]
Have not tested with a second plugin, but can confirm
Only one plugin 1.9.0rc4 on edge, the webcam in the control box is a black window.

Going to the webcam test url - I can see the webcam stream properly.

**Comment by foosel** [comment]
Yeah, it's probably caused by some changes in 1.9.0rc4 that hooks into the selected camera and pushes that into local storage, my guess is it's running into issues there if only one camera is installed (ironically, I was debugging a problem with webcam switching at the same time as developing this, and thus had the testpicture camera plugin installed, so never noticed)

**Comment by foosel** [comment]
Fix ready for 1.9.0rc4

**Comment by foosel** [comment]
Wonderful! Then this can be closed ☺️
