### ISSUE TITLE
Canceling single oboject

### ISSUE THREAD

**Issue by MrBrain295** [OctoPrint/OctoPrint#4802]
### Is your feature request related to a problem? Please describe.

Sometimes during multi-object printing I need to cancel a single object but I can't.

### Describe the solution you'd like

PrusaSlicer can label lines of Gcode by object so Octoprint could hypothetically not send just those lines.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by jneilliii** [comment]
This is achievable with the cancel object plugin I believe.
