### ISSUE TITLE
Biqu Bx probe error since last update.

### ISSUE THREAD

**Issue by aka1ceman** [OctoPrint/OctoPrint#4807]
### The problem

Since last update now printer will not probe and reports probing error.
If I print directly with printer (Not using octoprint) it works perfectly fine.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

Version 1.8.7

### Operating system running OctoPrint

WINDOWS 10

### Printer model & used firmware incl. version

Biqu Bx 

### Browser and version of browser, operating system running browser

firefox

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by cp2004** [comment]
Please use the [community forums](https://community.octoprint.org) or [Discord server](https://discord.octoprint.org) for help with your printer and general setup - a probing error is generated by the printer, not OctoPrint.
