### ISSUE TITLE
Octopi dosen't detect printer. Lack of CH341 driver

### ISSUE THREAD

**Issue by varefaz** [OctoPrint/OctoPrint#4828]
### The problem

My ender 3 S1 printer is easily seen by my PC but not by octoprit.I tried to reinstall everything octopi several times, I tried two different cables and with both I can connect to the PC. I didn't install the plugin but I tried safe mode anyway.I can't get the printer to be detected in any way.The only thing I noticed is that the PC communicates with the printer via the CH341 driver.
The story is this: I was already using octoprint. But to power the raspberry pi 3b+ from the printer, the Ender's motherboard burned out on the USB side (i didn't exclude the 5v wire, i forgot to do). So I couldn't use raspberry anymore. In the meantime that the new motherboard arrived, I updated octopi and now nothing works anymore.

what i have tried: delete ch341 driver, compile and install new driver, different cable, different port, try to see ttyUSB0 in ls /dev 
no ch341 connected or disconnected with dmesg.
guide that i follow 
http://www.weedo3dprinter.com/doku.php/x40/updatech340
https://learn.sparkfun.com/tutorials/how-to-install-ch340-drivers/linux

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

OctoPrint 1.9.0 Python 3.9.2 OctoPi 1.0.0

### Operating system running OctoPrint

octopi

### Printer model & used firmware incl. version

ender 3 s1 professional fw Firmware 20230522

### Browser and version of browser, operating system running browser

chrome, win11, android, putty ssh

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [x] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

![photo_2023-06-09_13-14-01](https://github.com/OctoPrint/OctoPrint/assets/17839917/8f59b5d3-a3e7-456f-8460-e8f384c54e72)
![photo_2023-06-09_13-14-12](https://github.com/OctoPrint/OctoPrint/assets/17839917/ea6c0cd0-4415-4d35-b1fb-f7c2c3f44b05)
you can see the folder version where i have put the compiled driver.

[octoprint-systeminfo-20230609131634.zip](https://github.com/OctoPrint/OctoPrint/files/11705687/octoprint-systeminfo-20230609131634.zip)

**Comment by foosel** [comment]
This doesn't sound like a general issue with Octo**Print** but more like a problem with your specific setup. Please get in touch on the [community forum](https://community.octoprint.org). The bug tracker is reserved for bugs, feature requests and brainstorming tickets. See also the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md). Thank you! :)
