### ISSUE TITLE
octoprint.service script deprecated

### ISSUE THREAD

**Issue by mad73923** [OctoPrint/OctoPrint#4839]
### The problem

When using the provided service script in scripts/octoprint.service, we get a warning the call is outdated:

```
Jun 30 10:18:22 octoprint systemd[1]: Starting The snappy web interface for your 3D printer...
Jun 30 10:18:22 octoprint systemd[1]: Started The snappy web interface for your 3D printer.
Jun 30 10:18:23 octoprint octoprint[2297]: Starting the server via "octoprint" is deprecated, please use "octoprint serve" from now on.
Jun 30 10:18:28 octoprint octoprint[2297]: 2023-06-30 10:18:28,118 - octoprint.startup - INFO - ******************************************************************************
Jun 30 10:18:28 octoprint octoprint[2297]: 2023-06-30 10:18:28,125 - octoprint.startup - INFO - Starting OctoPrint 1.9.1
Jun 30 10:18:28 octoprint octoprint[2297]: 2023-06-30 10:18:28,126 - octoprint.startup - INFO - ******************************************************************************
```

The script is referenced in this thread:
https://community.octoprint.org/t/setting-up-octoprint-on-a-raspberry-pi-running-raspberry-pi-os-debian/2337

I'll provide a PR shortly.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.1

### Operating system running OctoPrint

Armbian

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20230630103307.zip](https://github.com/OctoPrint/OctoPrint/files/11914587/octoprint-systeminfo-20230630103307.zip)

**Comment by foosel** [comment]
Thanks for the PR, I just merged it! The fix will be in 1.10.0 👍️
