### ISSUE TITLE
[Request] "Moveable" PROGRESS BAR position

### ISSUE THREAD

**Issue by bolsoncerrado** [OctoPrint/OctoPrint#4846]
### Is your feature request related to a problem? Please describe.

I run a farm where I open multiple Octoprint tabs in a single browser.

With the recent addition of slicer thumbnails I have to scrolldown past the thumbnails to find out a "quick way" to see the print progress of each printer.

### Describe the solution you'd like

It would be great a setting to determine the position of the PROGRESS BAR, for example BEFORE the thumbnails would be great!

### Describe alternatives you've considered

Tried to look for plugins but no joy.

**Comment by jneilliii** [comment]
I need to see a screenshot of this. Sounds like you've moved your state panel in the sidebar? You should consider UI Customizer that allows you to position things around there UI.

**Comment by bolsoncerrado** [comment]
<img width="2879" alt="Captura de pantalla 2023-07-07 a las 13 54 51" src="https://github.com/OctoPrint/OctoPrint/assets/10992914/de1c8210-552d-49f7-88ac-37023f26dd72">

**Comment by bolsoncerrado** [comment]
UI Customizer looks a bit overkill for this "simple" change?

**Comment by jneilliii** [comment]
Oh, I see. You haven't moved the state panel, you're just using a super tiny window for each instance. Why don't you scale the state panel image in soccer thumbnails settings?

**Comment by bolsoncerrado** [comment]
Tried but it looks "weird"...

<img width="389" alt="Captura de pantalla 2023-07-07 a las 14 09 47" src="https://github.com/OctoPrint/OctoPrint/assets/10992914/0ec6b39d-da3e-4bf9-8f88-6f4a5e63eece">

**Comment by jneilliii** [comment]
As this is an issue related to a plugin I don't think core OctoPrint is the right place to make this request. Without the customization of my plugin you wouldn't have this issue and wouldn't need to move the progress bar. Would be happy to make it an option in Slicer Thumbnails though if you make the request over there.

**Comment by bolsoncerrado** [comment]
Got it, makes sense, thanks.
