### ISSUE TITLE
USB Webcam stopped working with latest raspian updates

### ISSUE THREAD

**Issue by oxivanisher** [OctoPrint/OctoPrint#4855]
### Short description
Debian package `camera-streamer-raspi` has broken dependencies in current version.

I hope this is the right place for this, since strictly speaking its not a Octoprint problem but for its dependencies.

### Detailed analysis
With the current debian packages (still on raspian 11, bullseye), the `camera-streamer-raspi` package has broken dependencies. I think this was introduced with the following updates, since it worked without a issue before (`/var/log/apt/history.log`):
```plaintext
[..]
Start-Date: 2023-07-19  12:49:47Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold dist-upgradeUpgrade: python3-picamera2:armhf (0.3.9-1, 0.3.12-1), libcamera-apps-lite:armhf (0~git20230301+54a781d-1, 1.2.1-1), libcamera0:armhf (0~git20230302+923f5d70-1, 0~git20230707+2783c8d8-1), python3-libcamera:armhf (0~git20230302+923f5d70-1, 0~git20230707+2783c8d8-1)
Remove: camera-streamer:armhf (0.2+transitional), camera-streamer-raspi:armhf (0.2.1~bullseye-1)
End-Date: 2023-07-19  12:49:53
[..]
```

I followed this trail to come to this conclusion:
1) I checked jurnalctl for errors: `journalctl -u camera-streamer-usb@default.service`
    ```plaintext
    [..]
    Jul 20 01:25:48 prusamk4 systemd[1]: Starting camera-streamer default...
    Jul 20 01:25:48 prusamk4 systemd[1]: Started camera-streamer default.
    Jul 20 01:25:48 prusamk4 sh[1950]: /bin/sh: 1: exec: /usr/bin/camera-streamer: not found
    Jul 20 01:25:48 prusamk4 systemd[1]: camera-streamer-usb@default.service: Main process exited, code=exited, status=127/n/a
    Jul 20 01:25:48 prusamk4 systemd[1]: camera-streamer-usb@default.service: Failed with result 'exit-code'.
    Jul 20 01:25:58 prusamk4 systemd[1]: camera-streamer-usb@default.service: Scheduled restart job, restart counter is at 8.
    Jul 20 01:25:58 prusamk4 systemd[1]: Stopped camera-streamer default.
    [..]
    ```

1) I tried to install the `camera-streamer` and `camera-streamer-stack` manually:
    ```bash
    prusamk4 ~ # apt install camera-streamer-stack
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     camera-streamer-stack : Depends: camera-streamer
    E: Unable to correct problems, you have held broken packages.

    prusamk4 ~ # apt install camera-streamer
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     camera-streamer-raspi : Depends: libcamera0 (= 0~git20230302+923f5d70-1) but 0~git20230707+2783c8d8-1 is to be installed
    E: Unable to correct problems, you have held broken packages.
    ```

1) Trying to fix it with `--fix-broken` does not fix the problem either:
    ```bash
    prusamk4 ~ # apt --fix-broken install camera-streamer-stack
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     camera-streamer-stack : Depends: camera-streamer
    E: Unable to correct problems, you have held broken packages.

    prusamk4 ~ # apt --fix-broken install camera-streamer
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     camera-streamer-raspi : Depends: libcamera0 (= 0~git20230302+923f5d70-1) but 0~git20230707+2783c8d8-1 is to be installed
    E: Unable to correct problems, you have held broken packages.
    ```

1) I guess the `camera-streamer-stack` has to be recompiled for the new versions? But I am not shure about this. Also I have two identical Octoprint setups for two printers and it is the same problem on both.

### Did the issue persist even in safe mode?

Yes, it did persist

### If you could not test in safe mode, please state why

This is a problem not on the Octoprint level, but with its OS dependencies.

### Version of OctoPrint

1.9.2

### Operating system running OctoPrint

1.0.0 (The systems where completely reinstalled just 3 weeks ago or so)

### Printer model & used firmware incl. version

Prusa MK4 and Prusa MK3 (irrelevant)

### Browser and version of browser, operating system running browser

Vivaldi (irrelevant)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20230720110534.zip](https://github.com/OctoPrint/OctoPrint/files/12104207/octoprint-systeminfo-20230720110534.zip)

**Comment by foosel** [comment]
> I hope this is the right place for this, since strictly speaking its not a Octoprint problem but for its dependencies.

Sorry to say it's not, the correct place would (likely?) be the OctoPi-UpToDate repo, but there it already has been mentioned in the relevant feedback ticket: https://github.com/OctoPrint/OctoPi-UpToDate/issues/6#issuecomment-1643298897
