### ISSUE TITLE
[Request] Support displaying Marlin SOC temp on graph

### ISSUE THREAD

**Issue by ansonl** [OctoPrint/OctoPrint#4865]
### Is your feature request related to a problem? Please describe.

Right now Marlin SOC temp can only be read in the terminal as the temperature reported as S:XX.XX. It's hard to track it during printing and over time.

### Describe the solution you'd like

Display SOC temp as another temperature in Octoprint like Chamber temp,etc.

### Describe alternatives you've considered

Log M105 temps that have S before them, but it's basically redoing the graph. 

### Additional context

https://github.com/MarlinFirmware/Marlin/pull/25642 implemented the ability to read SOC temperature.

**Comment by jneilliii** [comment]
This can be accomplished with my Plotly Temp Graph plugin. Pretty sure it will report anything that comes across the response from M105.

**Comment by kantlivelong** [comment]
Top Temp could also be a viable option if you're open to it being displayed in it's own view.

**Comment by ansonl** [comment]
Top Temp worked for me since I'm already using the Tempsgraph plugin for a zoomable and croppable temp graph on the main temp tab. 

For anyone else finding this, SoC temp can be set up in Top Temp with Type `From printer` and Regexp `S:(\d*.\d*)`

**Comment by jneilliii** [comment]
For reference, Plotly Temp Graph plugin is not the same as tempsgraph, but did have all those features as well.
