### ISSUE TITLE
[Request]: add dimension to dimension numbers

### ISSUE THREAD

**Issue by openPhiL** [OctoPrint/OctoPrint#4866]
### Is your feature request related to a problem? Please describe.

Hi. 
I found this description here to be useful in a case I just had to look into, but then I realize, I don't know which dimension value is what dimesion. 
![image](https://github.com/OctoPrint/OctoPrint/assets/43743230/e5ea6009-ef48-4040-a4ca-1a57fde8846e)

I am wondering, if it would be possible to add the dimensions to the values. Seems like a quickwin. It is not really important I assume, but it would be helpful nevertheless. 

### Describe the solution you'd like

Here are my paint-skills: 
![image](https://github.com/OctoPrint/OctoPrint/assets/43743230/08996fd4-17f1-469b-9e20-fa70b2828ad5)

**Comment by foosel** [comment]
Implemented by the above PR by @evanwurden (thanks!), now merged, ready for 1.10.0.
