### ISSUE TITLE
Unknown opcode

### ISSUE THREAD

**Issue by Dynom** [OctoPrint/OctoPrint#4889]
### The problem

The print stopped because of:
```
Something crashed inside the serial connection loop, please report this in OctoPrint's bug tracker:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/comm.py", line 2313, in _monitor
    if line.startswith("echo:busy:") or line.startswith("busy:"):
SystemError: unknown opcode
```

```python
##~~ busy protocol handling
if line.startswith("echo:busy:") or line.startswith("busy:"):
    # reset the ok timeout, the regular comm timeout has already been reset
    self._ok_timeout = self._get_new_communication_timeout()
```

I've not run into this issue before, even though I've printed a few things already with this (Version 1.9.2) OctoPrint release, and also the same gcode.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

It happened just once, after I re-started the print everything went fine.

### Version of OctoPrint

1.9.2

### Operating system running OctoPrint

Raspbian GNU/Linux 11 (bullseye), Build 2023.07.18.111854, based on OctoPi 1.0.0, running on Raspberry Pi 2 Model B Rev 1.1

### Printer model & used firmware incl. version

Anycubic Vyper (Running 2.4.5, stock)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

Relates to https://github.com/OctoPrint/OctoPrint/issues/4669
OctoPi Build 2023.07.18.111854, based on OctoPi 1.0.0, running on Raspberry Pi 2 Model B Rev 1.1

[octoprint-systeminfo-20230924083529.zip](https://github.com/OctoPrint/OctoPrint/files/12707994/octoprint-systeminfo-20230924083529.zip)

**Comment by foosel** [comment]
I can sadly only repeat what I already posted in #4669:

> From the looks of the log excerpts above however, something gets seriously messed up in the Python process. "Unknown opcode" sounds like it either has some corrupt code its dealing with (ever shut off the Pi without a proper shutdown procedure first?) or some other fishy thing is going on. It's certainly not something within the control of OctoPrint, and the code location also doesn't make a lot of sense here.
>
> You might want to try if a [reinstall](https://community.octoprint.org/t/how-to-reinstall-octoprint/36628) fixes it.

To add to that: this particular error means that something in the compiled bytecode is messed up. That can be a bug, but if it happens randomly that strongly hints at some corruption or just a fluke due to browning out or whatnot.

So I fear there's nothing I can do here. I'm happy to investigate this if it happens reproducibly, but if it only happened once, it's impossible to analyse.
