### ISSUE TITLE
Octoprint freezes after Update to current stable OctoPi 1.0.0 with OctoPrint Release Candidate 1.9.2

### ISSUE THREAD

**Issue by cyberbob1200** [OctoPrint/OctoPrint#4891]
### The problem

-Update the RaspBerry Pi Zero 2 W to current stable OctoPi 1.0.0 with OctoPrint Release Candidate 1.9.2 
-Octoprint start with AnyCubic i3 Mega S Printer connected
-if I press Up/Down , Left/Right or other Features, Octoprint freezes until i Power Off the Printer
-ping via the ip adress is also not possible
-start a new print job from file will work , but no steering is possible, an the cam also not working
-No Addons are installed, clean and other SD Card installation is also done

### Did the issue persist even in safe mode?

No, it did not persist (it's an issue with one of your installed plugins, don't report here)

### Version of OctoPrint

1.9.2

### Operating system running OctoPrint

1.0.0 (Build 2023.07.20.144556)

### Printer model & used firmware incl. version

AnyCubic i3 Mega S , Marlin 1.1.0-RC8

### Browser and version of browser, operating system running browser

Google Chrome Version 117.0.5938.132 (Offizieller Build) (64-Bit)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-logs.zip](https://github.com/OctoPrint/OctoPrint/files/12794728/octoprint-logs.zip)
[octoprint-systeminfo-20231003180600.zip](https://github.com/OctoPrint/OctoPrint/files/12794729/octoprint-systeminfo-20231003180600.zip)

**Comment by foosel** [comment]
> ### Did the issue persist even in safe mode?
> 
> No, it did not persist (it's an issue with one of your installed plugins, don't report here)

I'm confused. Did you actually test in safe mode?

Your log shows this repeatedly:

```
2023-10-03 17:57:22,045 - octoprint.util.comm - ERROR - Unexpected error while reading from serial port
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/comm.py", line 4081, in _readline
    ret = self._serial.readline()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/comm.py", line 6832, in readline
    c = self.read(1)
  File "/home/pi/oprint/lib/python3.9/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2023-10-03 17:57:22,050 - octoprint.util.comm - ERROR - Please see https://faq.octoprint.org/serialerror for possible reasons of this.
```

So the serial connection to your printer breaks down, which means OctoPrint can't work. That's something that is happening outside of the control of OctoPrint, it basically gets the rug pulled from under its feet. There's an FAQ entry describing possible reasons and their mitigations: https://faq.octoprint.org/serialerror

> -if I press Up/Down , Left/Right or other Features, Octoprint freezes until i Power Off the Printer

Please clarify *where* you press that? Printer or OctoPrint?

> -start a new print job from file will work , but no steering is possible, an the cam also not working

Again, from OctoPrint or on the printer? 

> Update the RaspBerry Pi Zero 2 W to current stable OctoPi 1.0.0 with OctoPrint Release Candidate 1.9.2

"Update" sounds like you were running OctoPrint previously in another version on another version of OctoPi but possibly against the same printer. Is that indeed the case? If so, what version of OctoPrint was that?

Tbh, all in all that sounds more like a support request that should first be taken to the forums on https://community.octoprint.org before opening a bug report, as currently there's no bug visible to be reported in the provided logs. Please get in touch on the forums.
