### ISSUE TITLE
Newest update

### ISSUE THREAD

**Issue by Corocc** [OctoPrint/OctoPrint#4925]
### The problem

Newest update has ruined my printer
I have a savol sv06 plus, was working fine prior to update,it will print but the quality is shocking, try to do an xyz cube and right side basically looks like its trying to do a pyramid.
Have leveled and reset bed several times, reflashed my pi, even given the machine a deep clean.. basically pulled it apart 
Did a print on a flash card worked fine and came out amazing but second i pluged octo back it, back to problems 

Same problem after a reflash tells me yous did something in the code

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.3

### Operating system running OctoPrint

Octopi

### Printer model & used firmware incl. version

Savol sv06 plus on latest firmware

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [X] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

![17036427446027709304538815145448](https://github.com/OctoPrint/OctoPrint/assets/154943064/7828f28e-d459-4884-8965-27263827feb9)
![17036427761615209895677299403109](https://github.com/OctoPrint/OctoPrint/assets/154943064/a7e2b02d-b12c-44ee-b383-d2deb9d8778e)
![17036427947361168632205201143970](https://github.com/OctoPrint/OctoPrint/assets/154943064/761f8323-9c4c-44f7-955a-0a58e8ff00fb)

**Comment by Corocc** [comment]
No that is a security risk
Have provided you sufficient details for something visible to anyone
Open a direct line of chat please

**Comment by jneilliii** [comment]
OctoPrint only sends the commands in the gcode to your printer. 

> No that is a security risk
don'ts see how, you can edit the files within the zip prior to uploading to redact any personal information.

>Have provided you sufficient details for something visible to anyone
not without the logs we can't tell what's going on. would recommend enabling serial.log in this situation as well to verify the commands being sent to your printer.

> Open a direct line of chat please
feel free to jump on the [discord](https://discord.octoprint.org) server, there is a support-printer channel just for this purpose.
