### ISSUE TITLE
Raspberry pi 5 support

### ISSUE THREAD

**Issue by softmarshmallow** [OctoPrint/OctoPrint#4933]
Can we have a official thread working on raspberry pi 5, a issue or a branch?
When do you think it will be available? thank you :)
What is the current dirty-hack to run on raspberry pi 5 ?

**Comment by jneilliii** [comment]
Wrong repo for this ask, that's an OctoPi request. There are nightly builds

https://unofficialpi.org/Distros/OctoPi/nightly/2024-01-16_2023-12-11-octopi-bookworm-armhf-lite-1.1.0.zip
