### ISSUE TITLE
[1.10.0rc1] drag and drop upload not working

### ISSUE THREAD

**Issue by jneilliii** [OctoPrint/OctoPrint#4939]
### The problem

When dragging a gcode file onto the UI the overlay doesn't show and upload never happens. 

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.10.0rc1

### Operating system running OctoPrint

OctoPi 1.1.0 (nightly bookworm build) and OctoPi 0.18.0 (build 2022.10.18.093204)

### Printer model & used firmware incl. version

Virtual Printer

### Browser and version of browser, operating system running browser

Google Chrome Version 121.0.6167.87 (Official Build) (64-bit)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240131192605.zip](https://github.com/OctoPrint/OctoPrint/files/14118792/octoprint-systeminfo-20240131192605.zip)

[192.168.126.109-1706747235133.log](https://github.com/OctoPrint/OctoPrint/files/14118800/192.168.126.109-1706747235133.log)

https://github.com/OctoPrint/OctoPrint/assets/5249455/6903086f-1ddc-4204-9fa2-2d2ff75343d3

**Comment by larp-welt** [comment]
I have the same problem...

[octoprint-systeminfo-20240201233649.zip](https://github.com/OctoPrint/OctoPrint/files/14132206/octoprint-systeminfo-20240201233649.zip)

**Comment by foosel** [comment]
I'll look at this on Monday :+1:

**Comment by jaymcd** [comment]
Same issue here

**Comment by jneilliii** [comment]
I think this may be a race condition with settings load. My previous PR that enabled the option in settings was definitely working, but now seems that the `feature_enableDragDropUpload` observable is detected as undefined on serverConnect when the drag and drop binding is taking place.

**Comment by jneilliii** [comment]
possible solution might be to do the `self._enableDragNDrop(true);` in an observable subscription to `feature_enableDragDropUpload`, and pass along the boolean from new value?

**Comment by jaymcd** [comment]
In my case, will test if it had anything to do with UI customizer as that seems to be acting weird well. Many settings don't take.JayOn Feb 3, 2024, at 12:32 PM, jneilliii ***@***.***> wrote:﻿
possible solution might be to do the self._enableDragNDrop(true); in an observable subscription to feature_enableDragDropUpload, and pass along the boolean from new value?

**Comment by jneilliii** [comment]
It doesn't make a difference with UI Customizer or not. The issue exists in safe mode, which has no plugins running.

**Comment by foosel** [comment]
1.10.0rc2 has just been released :+1:
