### ISSUE TITLE
When the service starts, a test file will be created in the directory to ensure that the directory is normal. Can the fixed file name be changed to a random file name?

### ISSUE THREAD

**Issue by easonjim** [OctoPrint/OctoPrint#4949]
### Describe the solution you'd like

Because when using a shared public directory, if the same multiple octoprints are started, competition for the same file will cause startup failure, and the public directory startup detection will fail, causing configuration restoration.

**Comment by jneilliii** [comment]
> Because when using a shared public directory, if the same multiple octoprints are started, competition for the same file will cause startup failure, and the public directory startup detection will fail, causing configuration restoration.

this is a misconfigured setup because the basedir as a whole should not be shared between instances.
