### ISSUE TITLE
Request: even for any Gcode or adding arguments to system commands ?

### ISSUE THREAD

**Issue by sn00zerman** [OctoPrint/OctoPrint#495]
Hello,

I'm looking for a way, to control some system commands with arguments.
I'm thinking of 2 possibilities:
1. Most obvious: add the possibility to add arguments to system commands.
   (I now have the possibility to turn my LEDs on and off, but I want to do some PWM'ing,
   so I can for example add the percentage that my LEDs should be on, via wiringPi PWM functionality)
   Also, I'm currenly building a "large" 3D printer (55 x 55 x 55 cm print-volume), and want
   to be able to control multiple fans with this method. (e.g. FAN1=30%, FAN2=75%,FAN3=50%,FAN4=100,FAN5=0%)
   I can add commands per 10% in my system command dropdown, but this would make this menu very large. (.e.g 9 Fans, 1 BLUE LED control, 1 RED LED control, 1 GREEN LED control = 12 devices x 10 items (1 item per 10%) = 120 menu-items !)
2. This could also be done via G-code events, but I need to be able to intercept
   certain G-codes, and can't use only the default defined events.
   I case of a generic G-code event, I want to be able to pass the G-code arguments as
   arguments to my commands ...

thank you,
keep up the good work,
Kris

**Comment by bzed** [comment]
@sn00zerman does https://plugins.octoprint.org/plugins/gcodesystemcommand what you want?

**Comment by cp2004** [comment]
The mentioned plugin does allow you to run system commands from gcode, or the plugin system itself allows for a wide range of options reacting to most things you can think of.
