### ISSUE TITLE
[Request] Remote website

### ISSUE THREAD

**Issue by TyTyDaCodingGuy** [OctoPrint/OctoPrint#4959]
### Describe the solution you'd like

Now I don't know how plausible this is but maybe you could implement a hidden option to run a remote website so you could access OctoPrint from afar. I like to be able to start remote prints and watch my prints from afar but the webcam streaming always sucks. So what I am suggesting is you add a way to run a website off the raspberry pi or computer where it connects to octoprint.org or another website where as you can access OctoPrint without slow webcam streaming.

**Comment by cp2004** [comment]
There are many solutions already for remote access, the majority of which can be accessed via plugins.

https://plugins.octoprint.org/topics/remote_access/
