### ISSUE TITLE
GCode Viewer is disabled after re-upload

### ISSUE THREAD

**Issue by smurfix** [OctoPrint/OctoPrint#4978]
### The problem

* upload a file to OctoPrint via Prusa Slicer
* load file
* observe nice gcode preview
* re-upload the same file, or upload a different file with the same name
* OctoPrint updates the data (size etc.) of the loaded file
* … but the gcode viewer is now empty.

To recover, I need to reload the browser window.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.10-0rc3

### Operating system running OctoPrint

Debian

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240328221240.zip](https://github.com/OctoPrint/OctoPrint/files/14795707/octoprint-systeminfo-20240328221240.zip)

**Comment by foosel** [comment]
First thought this was a regression, but I can also reproduce this on 1.9.3, so no regression on 1.10.0 and thus will have to go into a bugfix release.

**Comment by foosel** [comment]
Good news I guess, we need another RC for 1.10.0 after all, and I'll include this fix in that.

**Comment by foosel** [comment]
Fixed in 1.10.0rc4.
