### ISSUE TITLE
cannot connect through web interface

### ISSUE THREAD

**Issue by atfam** [OctoPrint/OctoPrint#4979]
### The problem

cannot connect through web interface 

it works then it doesn't work

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### Version of OctoPrint

the newest multi camera stack

### Operating system running OctoPrint

OctoPi

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

I can't retrieve Systeminfo Bundle :(

currently

**Comment by foosel** [comment]
No system info bundle, no testing in safe mode, completely unclear what the issue even is and to boot no OctoPrint version.

I'm happy to help you, but I can't work with this. Please request a reopen once you've tested in safe mode, provided a system info bundle (including an enabled serial.log please) and can provide full steps on how to reproduce and what errors exactly you are seeing.
