### ISSUE TITLE
PSU Control Plugin Power off Options - idle timeout not working

### ISSUE THREAD

**Issue by wseifert** [OctoPrint/OctoPrint#4982]
### The problem

with Octoprint  1.10.0rc3 the PSU Control Plugin Power off Options - idle timeout is no longer working

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

Plugin in safe mode not active

### Version of OctoPrint

     OctoPrint 1.10.0rc3 Python 3.9.2 OctoPi* 1.0.0cam (build 2023.10.09.154319)

### Operating system running OctoPrint

OctoPi 1.0.0

### Printer model & used firmware incl. version

Prusa MK4

### Browser and version of browser, operating system running browser

Firefox 124.0.1 x64

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by wseifert** [comment]
[octoprint-systeminfo-20240402101151.zip](https://github.com/OctoPrint/OctoPrint/files/14833648/octoprint-systeminfo-20240402101151.zip)

**Comment by foosel** [comment]
Thank you for the report, but that's an issue with a third party plugin which needs to get reported to the plugin repository, as I can do absolutely *nothing* about it given that it's not my plugin.
