### ISSUE TITLE
Update to 1.10.0 fails because of netifaces2

### ISSUE THREAD

**Issue by IchSchreiGleich** [OctoPrint/OctoPrint#4997]
### The problem

Updating an already running instance with `./venv3.9/bin/python -m pip install --upgrade octoprint` fails with

```
Compiling netifaces v0.1.0 (/tmp/pip-install-dyyhyxi9/netifaces2_a4e6ec59b8ba427f8cc87b285b0ddf70)
      error[E0599]: no method named `as_netlink_addr` found for union `SockaddrStorage` in the current scope
        --> src/linux.rs:82:49
         |
      82 |                 if let Some(net_link) = address.as_netlink_addr() {
         |                                                 ^^^^^^^^^^^^^^^ help: there is a method with a similar name: `as_link_addr`

      error[E0599]: no method named `as_vsock_addr` found for union `SockaddrStorage` in the current scope
        --> src/linux.rs:87:51
         |
      87 |                 if let Some(vsock_addr) = address.as_vsock_addr() {
         |                                                   ^^^^^^^^^^^^^ help: there is a method with a similar name: `as_link_addr`

      error[E0599]: no method named `as_alg_addr` found for union `SockaddrStorage` in the current scope
        --> src/linux.rs:96:49
         |
      96 |                 if let Some(alg_addr) = address.as_alg_addr() {
         |                                                 ^^^^^^^^^^^ method not found in `SockaddrStorage`
```

My environment is
```bash
CARGO_BUILD_TARGET=x86_64-unknown-freebsd
RUSTUP_HOME=~/.rustup
CARGO_HOME=~/.cargo
PATH=$CARGO_HOME/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
```

Maybe this is a topic for https://github.com/SamuelYvon/netifaces-2 ?

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.3

### Operating system running OctoPrint

FreeBSD 14.0 p6

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240426171230.zip](https://github.com/OctoPrint/OctoPrint/files/15132348/octoprint-systeminfo-20240426171230.zip)

**Comment by foosel** [comment]
Yes, this should rather get directed at the third party dependency, it's outside of my control and nothing I can help you with.
