### ISSUE TITLE
Pause bug

### ISSUE THREAD

**Issue by JimZuber** [OctoPrint/OctoPrint#50]
When I attempt to resume a paused print job, I start receiving line number errors immediately after I resume the print job. It appears the OctoPrint is a bit confused once a job is resumed. See output from terminal below. Note that lines are either duplicated or skipped after starting wtih N586. I am running a Raspberry Pi and it doesn't appear to matter where in the job I trigger the pause. Everything works perfect until I resume the pause.

Send: N582G1 X9.89 Y55.18 E69.8197_116
Recv: ok T:199.46 B:3.00 @:50
Send: N583G1 X9.71 Y53.77 E69.9429_124
Recv: ok
Send: N584G1 X9.84 Y53.82 E69.9548_125
Changing monitoring state from 'Printing' to 'Paused'
Recv: ok
Recv: ok
Changing monitoring state from 'Paused' to 'Printing'
Send: N585G1 X9.95 Y53.89 E69.9659_116
Send: N586G1 X20.44 Y60.78 E71.0593_75
Recv: ok
Send: N586G1 X20.44 Y60.78 E71.0593_75
Send: N587G1 X20.57 Y60.8 E71.0708_127
Recv: ok
Send: N589G1 X22.7 Y60.11 E71.2656_118
Send: N589G1 X22.7 Y60.11 E71.2656_118
Send: N590G1 X23.16 Y59.96 E71.3074_77
Send: N592G1 X24.07 Y59.65 E71.3918*71
Recv: Error:Line Number is not Last Line Number+1, Last Line:586

BTW, I really, really like the work done on this program!  

Jim

**Comment by kmbecker13** [comment]
Just saw this post and i'm seeing behavior very similar to what jakeebel posted about on March 23...after hitting pause, raising z height and changing filaments - once i hit resume, the printer goes super slow at the new z-height and then finally drops down to the correct one a little while later.  Is that normal?

**Comment by Salandora** [comment]
Yes thats normal.

**Comment by eric-schleicher** [comment]
2019 on version  1.3.9 having just notices i'm having this issue.
