### ISSUE TITLE
cannot invalidate application tokens

### ISSUE THREAD

**Issue by disconn3ct** [OctoPrint/OctoPrint#5001]
### The problem

Users cannot invalidate application tokens

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.10.0

### Operating system running OctoPrint

dietpi

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

2024-04-28 11:02:45,911 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin appkeys
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/server/api/__init__.py", line 162, in pluginCommand
    response = api_plugin.on_api_command(command, data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/plugins/appkeys/__init__.py", line 381, in on_api_command
    if user_for_key is None or user_for_key.user_id != user_id:
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'user_id'

**Comment by disconn3ct** [comment]
This is probably a security issue in truth, but the barrier to entry is pretty high.

**Comment by jneilliii** [comment]
I am unable to reproduce this issue, where in the system are you pressing the delete key on the application key?

**Comment by disconn3ct** [comment]
Username to User Settings to Application Keys. Click the trash icon and it pops up with the confirmation. Clicking 'proceed' results in a 500
![image](https://github.com/OctoPrint/OctoPrint/assets/397465/af6c15b1-2bcb-4895-87b2-00b3902f90d5)

The user is *not* an administrator (operator only). It looks like the administrator/initial user can delete tokens successfully.

**Comment by foosel** [comment]
Logged in as a user I can reproduce this. There must have gone something wrong during a refactoring.

**Comment by foosel** [comment]
Fix is ready for 1.10.1 (even though the build currently fails for other reasons).

**Comment by disconn3ct** [comment]
Confirmed working. Thanks!
