### ISSUE TITLE
Typo in german translation: Verbindunden

### ISSUE THREAD

**Issue by anwile** [OctoPrint/OctoPrint#5002]
### The problem

In file src/octoprint/translations/de/LC_MESSAGES/messages.po line 6340 reads "Verbindunden" - should be "Verbunden".
Snippet is displayed in dashboard.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

clearly typo

### Version of OctoPrint

1.10.0

### Operating system running OctoPrint

OctoPi* 1.0.0cam (build 2023.10.09.154319)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240429170905.zip](https://github.com/OctoPrint/OctoPrint/files/15151232/octoprint-systeminfo-20240429170905.zip)

**Comment by foosel** [comment]
Fix ready for 1.10.2.
