### ISSUE TITLE
[Request] Improve layout of main Temp chart

### ISSUE THREAD

**Issue by mcstoufer** [OctoPrint/OctoPrint#5003]
### Is your feature request related to a problem? Please describe.

The x-axis labels of past time intervals are bit too noisy. The default `120` values is just a spray of hyphens, values and redundant `min` labels.
Visibility could be improved.

I'm using a current Chrome browser on Mac OS. The issue does not alleviate itself when the window is stretched horizontally.  Reducing the total interval to "70" does make the layout more consistent. Setting it to '240' completely blows out the layout.

### Describe the solution you'd like

* Decrease the kerning between the "-" and the value.
* Reduce all the `min` labels down to one axis label centered horizontally on the axis below the interval markers.
* 
<img width="565" alt="Screen Shot 2024-04-29 at 10 44 51 AM" src="https://github.com/OctoPrint/OctoPrint/assets/2081083/1b5e7e8c-e8ab-4991-8c93-29054f2d40ea">

**Comment by foosel** [comment]
Just to clarify something here, the default is **30** minutes, not 120:

![image](https://github.com/OctoPrint/OctoPrint/assets/83657/14f4cc5a-c90e-403a-a949-47a4d7445f2a)

However, I agree that it also still look sensible above that, so I'll look what I can do here.

**Comment by foosel** [comment]
Ready for 1.10.1.
