### ISSUE TITLE
[Request] make timezone for achievements more prominent

### ISSUE THREAD

**Issue by jonyo** [OctoPrint/OctoPrint#5007]
### Is your feature request related to a problem? Please describe.

When I first saw achievements, the time based ones were wrong. I got TGIF on a Thursday, "night owl" in the afternoon, etc.

There was no indication in the achievement that it was based on specific timezone. I found the timezone setting eventually, but for the first week or so I didn't look that close and just thought it was a new feature that was a little buggy. And I did not see any CTA to set the timezone (that I can remember).

### Describe the solution you'd like

2 possible things:

1. Call to action to set the timezone in the UI.  Maybe as a notification or something. 
2. Ability to reset just the time/date based achievements - it bugged me I had a bunch for the wrong thing so I cleared the plugin data, and that cleared all my achievements not just time/date ones. So it would be cool to have some way in the UI to reset all time related.  Orrr... Better yet, add a "reset this achievement" on individual ones to remove it if you want. (maybe that action needs the special permissions, making you enter password 😂 )

### Describe alternatives you've considered

- Another idea, expanding on the first one more: You could have a "setting the timezone" achievement! Name it something snazzy though. Maybe `Keeping Time(zone)` or something?  ¯\\\_(ツ)\_/¯ 
- Maybe all time related achievements are "locked" until you specifically set the timezone and confirm it. And some sort of CTA to bring it to your attention.
- If you don't lock them, at least show something in the UI saying `Timezone: ___` in gray in the achievements list under each achievement that is affected, with link taking you to edit the plugin's settings... Maybe it would show on the achievement unlock notice as well, if I had seen that I would have probably fixed it right away.
- Add a "use local timezone" button that would use JS to get the localized timezone (though I know from experience that can be tricky... maybe it is easier these days though I haven't tried in a while).

**Comment by foosel** [comment]
I've done this:

- timezone information, "time based" indicator and link to configuration in achievements overview
  ![image](https://github.com/OctoPrint/OctoPrint/assets/83657/dbd2a6ac-5adf-4881-a2b9-2e0acfde89e8)
- ability to reset time based or all achievements from the settings
  ![image](https://github.com/OctoPrint/OctoPrint/assets/83657/b7c2ca9f-8bfa-40b9-8843-2b425dfeea56)
- offer to reset all time based achievements on change of the configured timezone
  ![image](https://github.com/OctoPrint/OctoPrint/assets/83657/a02c75c9-0dbc-40ab-9222-b62bd1722a62)

Using the client side timezone wouldn't work - there might not be a client connected at the time the achievement is unlocked, so I have to rely on the server time. I tried squeezing a link to the config into time based achievement unlock notifications, but everything I tried to achieve that just looked horrible.

Will be in 1.10.1

**Comment by jonyo** [comment]
The screenshot look great, I like that chino of solutions. The option to reset all from the settings page is good touch as well, not everyone would think to try clearing the plug-in data on a different part of the ui.

:tada:
