### ISSUE TITLE
Prusa I3 Mk2s Z motors always on

### ISSUE THREAD

**Issue by Level3301** [OctoPrint/OctoPrint#5012]
### The problem

Raspberry Pi 4 running AArch64 (Archlinux for Arm based computers), OctoPrint runs as a separate web application on the Pi.
The Pi is connected via usb to the Prusa i3 mk2s printer running latest firmware.

I am worried about Z axis motor failure. It seems that the motors are always powered, since they're warm on touch. Other motors aren't.

I tried sending M84, M18 codes manually but it seems to have no effect. (GCode for powering off the PSU does nothing.)

I did not have this problem before using OctoPrint.

Help is appreciated.

Thank you

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

No third party plugins in use.

### Version of OctoPrint

1.10.0

### Operating system running OctoPrint

AArch64 (6.8.7-1-aarch64-ARCH) (Achlinux for Arm based computers)

### Printer model & used firmware incl. version

Prusa i3 mk2s, latest firmware 3.2.3

### Browser and version of browser, operating system running browser

Brave (1.65.123) on Archlinux (6.8.7-arch1-2)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20240507175401.zip](https://github.com/OctoPrint/OctoPrint/files/15239127/octoprint-systeminfo-20240507175401.zip)

**Comment by cp2004** [comment]
Please post on the [community forums](https://community.octoprint.org) or [discord server](https://discord.octoprint.org) to get help from the community. This issue tracker is reserved for bug reports and feature requests, and is only monitored by a small number of people. You will get better help from the community on the forums or discord server.
