### ISSUE TITLE
[Request] Confirm deleting of file

### ISSUE THREAD

**Issue by BloodyIron** [OctoPrint/OctoPrint#5025]
### Is your feature request related to a problem? Please describe.

We need a "are you sure?" confirmation dialogue when deleting files for extremely obvious reasons (do you really need me to explain why?)

### Describe the solution you'd like

We need a "are you sure?" confirmation dialogue when deleting files for extremely obvious reasons (do you really need me to explain why?)

**Comment by foosel** [comment]
Duplicate of #833
