### ISSUE TITLE
This just doesn't work

### ISSUE THREAD

**Issue by roda37** [OctoPrint/OctoPrint#5032]
How hard is it to make a simple instructions on how to run this, you have over 2000 files in this repository and there is no main file that you run to start the damn thing. This is the problem with programming, people like you complicate everything. I tried pip method, setup.py method even the yay method and all fail spectacularly. Every time I reinstalled my os and tried installing this thing it always failed. How hard is it to write simple concise program that actually launches..

**Comment by cp2004** [comment]
Hello @roda37! Happy Friday to you too.

Please check the Readme at https://github.com/OctoPrint/OctoPrint for some brief instructions.

For more detailed and recommended installation methods see the instructions on https://octoprint.org/download.

Hope you have a great weekend!

Charlie
