### ISSUE TITLE
Automatic connection -detection issue

### ISSUE THREAD

**Issue by Woytacze** [OctoPrint/OctoPrint#5053]
### The problem

I had a issue with one of our Prusa Mk3 with 3.11 firmware (modified for PT100 and 450C). I had to restart printer after failed print.
And when I tried to reconnect with retry option on Touch screen or AUTO option in web interface it started testing different baud rates to detect printer. When it hit correct one I saw screen on printer restarting (as usuall). But octoprint did not detect comunication and continue with testing different baud rates. After two loops (and two printer screen restarts) it reported printer not detected. Several tries with same result. It seem that timer for auto detection is bit short. I had to set baud rate manualy in web interface and then I was able to connect to printer.
[octoprint-systeminfo-20240902102938.zip](https://github.com/user-attachments/files/16835570/octoprint-systeminfo-20240902102938.zip)

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

I dont have access to a printer at this moment.

### Version of OctoPrint

1.10.2

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Prusa MK3S 3.11 with enabled PT100 and max temp 450C

### Browser and version of browser, operating system running browser

Firefox 115.13.0esr, Win 10

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by foosel** [comment]
> It seem that timer for auto detection is bit short.

If it's too short to work with your printer, then just increase it, it's configurable ;)

Settings > Serial Connection > Intervals & timeouts > Timeouts > Autodetection timeout

If you know your baudrate and port however, I'd recommend to just leave that configured as the default, that way everything will just go faster and should usually work on the first try.

I'm closing this now as there's no immediate TODO here. If you need further assistance, please reach out at the official support forum (https://community.octoprint.org) or - if you rather prefer chat - the Discord (https://discord.octoprint.org).
