### ISSUE TITLE
Temperature tab: target temperature fields looks like username/pw to bitwarden

### ISSUE THREAD

**Issue by AndKe** [OctoPrint/OctoPrint#5081]
### The problem
Bitwarden autoi-fill overlays the temperature box
please see: 
![image](https://github.com/user-attachments/assets/967c29ce-ca98-401b-9e5e-e0ae38021af3)

to reproduce: install bitwarden, - maybe need to have bitwarden store the PW for Octoprint.

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

irrelevant

### Version of OctoPrint

1.10.3

### Operating system running OctoPrint

Linux

### Printer model & used firmware incl. version

N/A

### Browser and version of browser, operating system running browser

Vivaldi, Linux

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20241119084537.zip](https://github.com/user-attachments/files/17812198/octoprint-systeminfo-20241119084537.zip)

**Comment by foosel** [comment]
It's a simple `<input type="number">`. If Bitwarden decides to mark this up as a username/password field, even though it's not marked up as such and even a number-only input, that's a problem with Bitwarden and nothing I can change. I suggest you open this up as an issue with Bitwarden. KeepassXC-Browser doesn't appear to have this issue.
