### ISSUE TITLE
Request: Notepad area for parts

### ISSUE THREAD

**Issue by gregoryfenton** [OctoPrint/OctoPrint#519]
One of the great things about OctoPrint is the ability for others to see your print in action.

Could a feature be added that allows notes to be typed in by the admin so others can get more information about the print such as model information, web page et cetera?

Only a small thing but being able to give background information may be a useful feature.

RFCs and input welcomed

Greg

**Comment by nicolinux** [comment]
+1
Here is another use case for this feature:
When you slice something and upload the .gcode file, you don't necessarily what was in the gcode file. Were there three objects or only two? With this feature one could quickly jot down some info about the object like purpose, count and so on. This information is valuable later when the object is printed again through OctoPrint.

**Comment by cp2004** [comment]
There's the StickyPad plugin for notes on the web interface, or the PrintJobHistory plugin that allows for detailed information to be recorded about each print.
