### ISSUE TITLE
Connection Indicator

### ISSUE THREAD

**Issue by marvinstuart** [OctoPrint/OctoPrint#527]
It would be a nice feature to have an indicator telling us how many active persons are connected to octoprint web. The reason why i ask this is that as i allow persons access my octoprint web watch my parts print, However i never can tell if someone is connected or not 

Actually i use very crude approach by manually start octoprint via putty and then if someone other than me connects i will see the following in the terminal (very crude)  

2014-07-30 21:29:21,952 - octoprint.server.util - INFO - New connection from client: 63.168.X .X

A cleaner approach would be awesome

**Comment by jneilliii** [comment]
I'll take a stab at this one, seems relatively easy enough to keep track of ClientOpened/ClientClosed events.

**Comment by jneilliii** [comment]
That was fun, here's a plugin that will add a sidebar panel to OctoPrint showing a list of active connections.

![image](https://user-images.githubusercontent.com/5249455/150648216-dcd20a00-c206-494c-a4c4-5ff6bdbae4c4.png)

https://github.com/jneilliii/OctoPrint-ActiveConnections
