### ISSUE TITLE
second extruder temp "off"

### ISSUE THREAD

**Issue by dq3dbiz** [OctoPrint/OctoPrint#555]
Hi guys, I just set up a Rpi with the last develop version ( 1.2.0-dev-118-gfbd9440 ) of Octoprint, everything goes well apart the 2nd extruder temp graph. I had enabled the "Support Target......." options, so now I can see the target temp line on the graph correctly but the current temp is still "off".
If I try to change manually the extruder via Gcode command "T1" the graph show the temp for the tools 1 correctly. There is something I can do to solve this issue or the problem is already well know and I need just to wait?

**Comment by dq3dbiz** [comment]
just sorry for the delay (little delay), here it is my serial.log

http://pastebin.com/8MSJrgCJ

**Comment by foosel** [comment]
Something is wrong with your firmware. It doesn't report the temperature for any but the first extruder. OctoPrint can't show data it doesn't get from the firmware. Properly recompile your firmware or ask your printer's vendor for help.

**Comment by dq3dbiz** [comment]
I'm asking to my printer's vendor if there is a firmware version with this
feature, but I think it will be difficult if just one person ask for it...
there is someone else  here around that have figured out the same issue?

On Wed, Feb 11, 2015 at 7:43 PM, Gina Häußge <notifications@github.com>
wrote:

> Something is wrong with your firmware. It doesn't report the temperature
> for any but the first extruder. OctoPrint can't show data it doesn't get
> from the firmware. Properly recompile your firmware or ask your printer's
> vendor for help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/foosel/OctoPrint/issues/555#issuecomment-73938171>.
>



-- 
DQ3D
Via Manzoni 3
33080 Zoppola PN Italy
P.Iva       01761670932

Tel:  +39 3922424304

DQ3D.biz - www.facebook.com/DQ3D.biz - *info@dq3d.biz <info@dq3d.biz>*

**Comment by dq3dbiz** [comment]
Printer's vendor wrote me how to modify the firmware to be able to read
both temp, and it works out! There is a solution, that is quite simple, but
I think is better that if someone is interested will contact the printer's
vendor support.

I think there is another printer that will be added to the list.

thanks Gina Häußge for helping me

On Thu, Feb 12, 2015 at 10:18 AM, Daniel Quattrin <infodq3d@gmail.com>
wrote:

> I'm asking to my printer's vendor if there is a firmware version with this
> feature, but I think it will be difficult if just one person ask for it...
> there is someone else  here around that have figured out the same issue?
>
> On Wed, Feb 11, 2015 at 7:43 PM, Gina Häußge <notifications@github.com>
> wrote:
>
>> Something is wrong with your firmware. It doesn't report the temperature
>> for any but the first extruder. OctoPrint can't show data it doesn't get
>> from the firmware. Properly recompile your firmware or ask your printer's
>> vendor for help.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/foosel/OctoPrint/issues/555#issuecomment-73938171>.
>>
>
>
>
> --
> DQ3D
> Via Manzoni 3
> 33080 Zoppola PN Italy
> P.Iva       01761670932
>
> Tel:  +39 3922424304
>
> DQ3D.biz - www.facebook.com/DQ3D.biz - *info@dq3d.biz <info@dq3d.biz>*
>



-- 
DQ3D
Via Manzoni 3
33080 Zoppola PN Italy
P.Iva       01761670932

Tel:  +39 3922424304

DQ3D.biz - www.facebook.com/DQ3D.biz - *info@dq3d.biz <info@dq3d.biz>*
