### ISSUE TITLE
[Question] Calling a Script from the Webgui

### ISSUE THREAD

**Issue by sydios** [OctoPrint/OctoPrint#566]
Hi,

i build a pan / tilt camera rig for my Raspberry Cam so i can check the print when i am out.
I have created some scripts (shell) for pre defined positions for the cam. Is it posible to 
create some buttons on the webgui which will call those scripts, so i don't have to logon via ssh 
anymore?

thanks in advance,

syd

**Comment by boelle** [comment]
i want to do the same, but i want the controls to be in controls section and not in system

can that be done? example:

controls:
  actions:
  - name: Pan Left
    action: Pan Left
    command: sudo python panleft.py
