### ISSUE TITLE
[request] Build Log

### ISSUE THREAD

**Issue by issackelly** [OctoPrint/OctoPrint#575]
I'd like to keep track of what I build, how it came out, and what the settings and materials were. As much of this that can be automated from the slicing or the gcode, or even just select/input boxes as possible would be great. This feels like an enormous feature. Right now I'm keeping track by taking photos and writing things in a notebook.

**Comment by cp2004** [comment]
Is possible with a plugin: PrintJobHistory. Records most if not all of the information you're describing there.

https://plugins.octoprint.org/plugins/PrintJobHistory/
