### ISSUE TITLE
ioloop issue

### ISSUE THREAD

**Issue by imrahil** [OctoPrint/OctoPrint#606]
1. What were you doing?
   Just printing. Then switched to "Gcode viewer" tab. 
2. What did you expect to happen?
   see Gcode view :)
3. What happened instead?
   Machine stopped.
4. Branch & Commit or Version:
   devel branch
5. Printer model & used firmware incl. version
   MendelMax with Marlin
6. Link to octoprint.log on gist.github.com
   https://gist.github.com/imrahil/b7448c034a933f4ef852
7. I love cookies :)

**Comment by droidmunkey** [comment]
This is not resolved, it happened to me today
