### ISSUE TITLE
[request] Clear button next to "Search" field.

### ISSUE THREAD

**Issue by scp38** [OctoPrint/OctoPrint#629]
1. What were you doing?
   Narrowed the selection of gcode files in the file list by typing some characters into the "Search" field. 
2. What did you expect to happen?
   To cancel the selection (and see the full list again) I'd rather click on a "Clear" button (X) next to the "Search" field than...
3. What happened instead?
   ... than having to manually delete the content in the "Search" field.
4. Branch & Commit or Version:
   any recent devel. e.g. Version: 1.2.0-dev-254-g9a7733c (devel branch)
5. Printer model & used firmware incl. version
   any (e.g. Felix 3.0 Duo)
6. Link to octoprint.log on gist.github.com or pastebin.com:
   n/a
7. Link to contents of terminal tab on gist.github.com or pastebin.com:
   n/a

BTW: "I love cookies".

**Comment by rspeed** [comment]
I tried modifying the template so the `type` of the input is "search", but it had no effect on my machine. Rather mystified by this.

**Comment by Findus23** [comment]
According to this Answer there is no browser, which uses this input type:
http://stackoverflow.com/a/11589805

But this page mentions, that WebKit has implemented it. 
http://css-tricks.com/webkit-html5-search-inputs/

If you add 
```html
<input type=search results=5 name=s>
```
the browser shows a magnifying glass, a button to clear and a drop down menu, with recent searches.
But they have to be saved by adding autosave:
```html
<input type=search results=5 autosave=some_unique_value name=s>
```
But I haven't tested if this really works in Chrome.

**Comment by Findus23** [comment]
I have tested it now and it works in Chromium 39 (Linux).
![bildschirmfoto vom 2015-01-05 10 06 24](https://cloud.githubusercontent.com/assets/6266037/5611134/9f76c26c-94c2-11e4-91d1-726ab2722062.png)

But when I test it in Octoprint, only the magnifying glass appears. 
![bildschirmfoto vom 2015-01-05 10 08 32](https://cloud.githubusercontent.com/assets/6266037/5611154/e25c6b72-94c2-11e4-8b99-01bc8ecbc3ac.png)

According to this page Bootstrap resets the webkit css:
http://stackoverflow.com/questions/13956868/html5-search-input-does-not-work-with-bootstrap

So when I add this CSS
```css
input[type="search"]::-webkit-search-cancel-button {
-webkit-appearance: searchfield-cancel-button;
}
```
the clear button appears and works.
![bildschirmfoto vom 2015-01-05 10 08 56](https://cloud.githubusercontent.com/assets/6266037/5611191/5eb943ca-94c3-11e4-85c0-dd14cc9be0d4.png)

**Comment by LazeMSS** [comment]
Fixed in current stable version - tested in Firefox, Chrome and Edge
